[package]
name = "anti_sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.62.0", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_UI_Shell",
]}

walkdir = "2.3"
quote = "1.0"
syn = { version = "2.0", features = ["full", "fold", "visit-mut", "visit"] }
rand = "0.9" # Version locked for consistency
base45 = "3.1.0"
base32 = "0.5.1"
base64 = "0.22.1"
base85 = "2.0.0"
bs58 = "0.5.1"
proc-macro2 = "1.0"
regex = "1.10"
aes = "0.8.4"
hex = "0.4.3"
getrandom = "0.3" # locked for consistency with rand 0.9
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
# --- Your existing build dependencies ---
walkdir = "2.3"
quote = "1.0"
syn = { version = "2.0", features = ["full", "fold", "visit-mut", "visit"] }
rand = "0.9" # Version locked for consistency
base45 = "3.1.0"
base32 = "0.5.1"
base64 = "0.22.1"
base85 = "2.0.0"
bs58 = "0.5.1"
proc-macro2 = "1.0"
regex = "1.10"
aes = "0.8.4"
hex = "0.4.3"
getrandom = "0.3" # locked for consistency with rand 0.9
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = []
full-detection = []
minimal = []
