@echo off
setlocal enabledelayedexpansion
chcp 65001 >nul
set "m_I_IOIIII0l=goto"
set "p1_lIl0IIIlO_=m_I_IOIIII0l"
set "p2__I000_O0I0=p1_lIl0IIIlO_"
set "m_IOOO_I_I0I=chcp"
set "p1_I_I__OO__l=m_IOOO_I_I0I"
set "p2__OO_0_I0ll=p1_I_I__OO__l"
set "m_l0_l____0l=title"
set "p1_OO_0I_lOIO=m_l0_l____0l"
set "p2_OlIOlIlI0l=p1_OO_0I_lOIO"
set "m__ll_0__I0O=echo"
set "p1_llllOl_OI0=m__ll_0__I0O"
set "p2__00_Ol0I00=p1_llllOl_OI0"
set "m_IO_O_0_I0O=call"
set "p1___ll0_IO_O=m_IO_O_0_I0O"
set "p2_OIl0IO0I0l=p1___ll0_IO_O"
set "m_O_I0lOOIIO=set"
set "p1__lI_lllO0I=m_O_I0lOOIIO"
set "p2__00OlIl00_=p1__lI_lllO0I"
set "m__OIl_l0l_O=pause"
set "p1_I__lIlOll0=m__OIl_l0l_O"
set "p2_I00OOOIlII=p1_I__lIlOll0"
set "m_l_0_O0I_I_=rem"
set "p1__I0l0__OlO=m_l_0_O0I_I_"
set "p2____0O_I0Il=p1__I0l0__OlO"
set "m_lIlI0_l_I0=exit"
set "p1__I_l_lOOlO=m_lIlI0_l_I0"
set "p2_Ol_O_O00OO=p1__I_l_lOOlO"
set "v_l_Ol_Ol0_l__=OOI0I_OIlOO_"
set "v_l_IO0IOlIlO0=LB_EXIT_I_Illl0l"
set "pool_lOOO__Ol=_zNw3Wtr0ma6h.b9MOUvLK5cI1nY@E8RjGBuFikX:dHg/fp-ClJTyZxQ24oA\ePDsVSq7"
set /a "Il0IlO=(-5+27)" & rem TNeD-1OM/H[dNUqPu3
set /a "IO__l0=(0*5)"
for /f "tokens=2 delims==" %%A in ('set Il0IlO') do for /f "tokens=2 delims==" %%C in ('set IO__l0') do call set "pool_lOOO__Ol=%%pool_lOOO__Ol:~%%A%%%%%%pool_lOOO__Ol:~%%C,%%A%%"
set /a "lI00I_=((((11*5)+3)-42)+39)" & rem Fs[EO]-P#W/=@Hzf
set /a "I0_l0l=((0*5)*6)"
for /f "tokens=2 delims==" %%A in ('set lI00I_') do for /f "tokens=2 delims==" %%C in ('set I0_l0l') do call set "pool_lOOO__Ol=%%pool_lOOO__Ol:~%%A%%%%%%pool_lOOO__Ol:~%%C,%%A%%"
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:u=#RCKVNCQG#%%" & rem EnkmW?_m@S
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:E=u%%"
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:#RCKVNCQG#=E%%"
set /a "OlI__O=((21+28)+11)" & rem }9OCx:0adqUaIApnnR9l
set /a "O_0__l=(((-46+46)*6)+(10-10))"
for /f "tokens=2 delims==" %%A in ('set OlI__O') do for /f "tokens=2 delims==" %%C in ('set O_0__l') do call set "pool_lOOO__Ol=%%pool_lOOO__Ol:~%%A%%%%%%pool_lOOO__Ol:~%%C,%%A%%"
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:4=#PDXCP#%%" & rem Dcj8ubb6eDI-_G-
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:O=4%%"
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:#PDXCP#=O%%"
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:S=#DZPNP#%%" & rem zYxnCsO;9t}d4Zk3;tF
call set "pool_lOOO__Ol=%%pool_lOOO__Ol::=S%%"
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:#DZPNP#=:%%"
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:H=#UZHMDKBVZ#%%" & rem [Y2#::+si[E9YzQ#XE,
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:s=H%%"
call set "pool_lOOO__Ol=%%pool_lOOO__Ol:#UZHMDKBVZ#=s%%"
set "v_j_OlOOOl=!pool_lOOO__Ol:~0,1!"
if "!v_j_OlOOOl!"=="_" (call :L_DISPATCH)

set "pool_I00l0_ll=kxOhJbrUqdLfBEKpID5FTjiPW0-Z_m8au\RA2HonY61stMQS7N.9gG4wCXecV@l:y/3vz"
set /a "Ill0_l=(26+13)" & rem ]xtCr-pxLYT_rbl
set /a "I_lII_=(((34-2)-32)+(5-5))"
for /f "tokens=2 delims==" %%A in ('set Ill0_l') do for /f "tokens=2 delims==" %%C in ('set I_lII_') do call set "pool_I00l0_ll=%%pool_I00l0_ll:~%%A%%%%%%pool_I00l0_ll:~%%C,%%A%%"
call set "pool_I00l0_ll=%%pool_I00l0_ll:r=#WLZTSDUDE#%%" & rem knj6kCB=9KbcXVRFy
call set "pool_I00l0_ll=%%pool_I00l0_ll:L=r%%"
call set "pool_I00l0_ll=%%pool_I00l0_ll:#WLZTSDUDE#=L%%"
set /a "_Ol0ll=((3*5)+1)" & rem +;--MzZN,8vD+4]
set /a "OIIOIO=((((30-15)*3)+2)-47)"
for /f "tokens=2 delims==" %%A in ('set _Ol0ll') do for /f "tokens=2 delims==" %%C in ('set OIIOIO') do call set "pool_I00l0_ll=%%pool_I00l0_ll:~%%A%%%%%%pool_I00l0_ll:~%%C,%%A%%"
set /a "O0O_l_=(((((4*5)+1)*2)+1)+(5-5))" & rem [J4nR8]PGzB+BMTfQw
set /a "O0O0l_=(-49+49)"
for /f "tokens=2 delims==" %%A in ('set O0O_l_') do for /f "tokens=2 delims==" %%C in ('set O0O0l_') do call set "pool_I00l0_ll=%%pool_I00l0_ll:~%%A%%%%%%pool_I00l0_ll:~%%C,%%A%%"
call set "pool_I00l0_ll=%%pool_I00l0_ll:.=#JEBNQUBNAC#%%" & rem ]xaYP+X$/B4mUq1mg/
call set "pool_I00l0_ll=%%pool_I00l0_ll:9=.%%"
call set "pool_I00l0_ll=%%pool_I00l0_ll:#JEBNQUBNAC#=9%%"
set /a "_I0Il_=(((6*6)+4)+2)" & rem 6rDzA:5EP5[S=gK}bJ
set /a "_O_0_O=(((67-50)-10)-7)"
for /f "tokens=2 delims==" %%A in ('set _I0Il_') do for /f "tokens=2 delims==" %%C in ('set _O_0_O') do call set "pool_I00l0_ll=%%pool_I00l0_ll:~%%A%%%%%%pool_I00l0_ll:~%%C,%%A%%"
call set "pool_I00l0_ll=%%pool_I00l0_ll:s=#WCHACGT#%%" & rem nvgMKHyLEZSE:
call set "pool_I00l0_ll=%%pool_I00l0_ll:o=s%%"
call set "pool_I00l0_ll=%%pool_I00l0_ll:#WCHACGT#=o%%"
set "v_j_IIII0O=!pool_I00l0_ll:~0,1!"
if "!v_j_IIII0O!"=="_" (call :L_DISPATCH)

set "pool__l_000_0=L2.z@E0VJUIKsGpeZ57RgnQ8fx1o_CPkqX/TD9:BarS-OAyHcjwvNhdi46muYlWb\t3FM"
call set "pool__l_000_0=%%pool__l_000_0:E=#JVKQSTZWJ#%%" & rem hoeMdJcoO_bN{#Y9h2w
call set "pool__l_000_0=%%pool__l_000_0::=E%%"
call set "pool__l_000_0=%%pool__l_000_0:#JVKQSTZWJ#=:%%"
set /a "l0l_OI=(((((-1*5)+15)*6)+1)+(14-14))" & rem ?~BTfQLSa7Jf=a
set /a "_I00OO=(-22+22)"
for /f "tokens=2 delims==" %%A in ('set l0l_OI') do for /f "tokens=2 delims==" %%C in ('set _I00OO') do call set "pool__l_000_0=%%pool__l_000_0:~%%A%%%%%%pool__l_000_0:~%%C,%%A%%"
call set "pool__l_000_0=%%pool__l_000_0:Y=#FUQVHP#%%" & rem }HLqGG@ReJt.T1Y4KDi
call set "pool__l_000_0=%%pool__l_000_0:e=Y%%"
call set "pool__l_000_0=%%pool__l_000_0:#FUQVHP#=e%%"
call set "pool__l_000_0=%%pool__l_000_0:D=#YKCNC#%%" & rem c/=I79qN{YZ_TX
call set "pool__l_000_0=%%pool__l_000_0::=D%%"
call set "pool__l_000_0=%%pool__l_000_0:#YKCNC#=:%%"
call set "pool__l_000_0=%%pool__l_000_0:t=#BCVEWPTGFC#%%" & rem fU2T3YmI_I=[nM+
call set "pool__l_000_0=%%pool__l_000_0:K=t%%"
call set "pool__l_000_0=%%pool__l_000_0:#BCVEWPTGFC#=K%%"
call set "pool__l_000_0=%%pool__l_000_0:y=#UBYQQB#%%" & rem ,Aa.{1N?ciW,B@d5oGW_
call set "pool__l_000_0=%%pool__l_000_0:t=y%%"
call set "pool__l_000_0=%%pool__l_000_0:#UBYQQB#=t%%"
set /a "lO_lOO=((126-26)-44)" & rem }q{{Z+Qvml/t8W#;
set /a "l__Oll=((9-9)*5)"
for /f "tokens=2 delims==" %%A in ('set lO_lOO') do for /f "tokens=2 delims==" %%C in ('set l__Oll') do call set "pool__l_000_0=%%pool__l_000_0:~%%A%%%%%%pool__l_000_0:~%%C,%%A%%"
set "v_j_l_lO0I=!pool__l_000_0:~0,1!"
if "!v_j_l_lO0I!"=="I" (call :L_DISPATCH)

set /a "v_i_I00l0O=(18+11)"
for /f "tokens=2 delims==" %%I in ('set v_i_I00l0O') do call set "v_l_O_Il00IO0O=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_IlI000Ol0_=!v_l_O_Il00IO0O!"
set /a "v_i_Ill0I_=(((54+41)+3)-46)"
set "v_p__O0lI0llIl=v_l__IO__llOIO"
for /f "tokens=2 delims==" %%I in ('set v_i_Ill0I_') do for /f "delims=" %%A in ("!v_p__O0lI0llIl!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c__00I_lO_l0=!v_l__IO__llOIO!"
set /a "v_i_O0IlII=25"
for /f "tokens=2 delims==" %%I in ('set v_i_O0IlII') do call set "v_l__l_0O_O0_I=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c__0lI0_O_OO=!v_l__l_0O_O0_I!"
set /a "v_i_O0l0lI=(((((1*3)+2)*5)+16)+(27-27))"
set "v_p_ll0O00II0_=v_l_lO_lOOIl00"
for /f "tokens=2 delims==" %%I in ('set v_i_O0l0lI') do for /f "delims=" %%A in ("!v_p_ll0O00II0_!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_Ol0I0_lIlI=!v_l_lO_lOOIl00!"
set /a "v_i_O_Ol_0=(((21-8)+3)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_Ol_0') do call set "v_l__IOOllIlIO=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_l__0Il0O__=!v_l__IOOllIlIO!"
set /a "v_i_lO0OO_=((((-35+39)*4)+1)+12)"
for /f "tokens=2 delims==" %%I in ('set v_i_lO0OO_') do call set "v_l_I_IOl_II_0=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__000OOl_lI=!v_l_I_IOl_II_0!"
set /a "v_i__II0I0=((122-42)-21)"
set "v_p_IlI0llO_OO=v_l__Ill0lIO_l"
for /f "tokens=2 delims==" %%I in ('set v_i__II0I0') do for /f "delims=" %%A in ("!v_p_IlI0llO_OO!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_lIO_l_OlOO=!v_l__Ill0lIO_l!"
set /a "v_i_O___O0=((((-1*3)+46)+2)+(21-21))"
set "v_p__Il_OII_I_=v_l_OlO0IIII0I"
for /f "tokens=2 delims==" %%I in ('set v_i_O___O0') do for /f "delims=" %%A in ("!v_p__Il_OII_I_!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__l_____OI_=!v_l_OlO0IIII0I!"
set /a "v_i_Il__I_=5"
for /f "tokens=2 delims==" %%I in ('set v_i_Il__I_') do call set "v_l_lIOIIl_l0I=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c__OlllOOl__=!v_l_lIOIIl_l0I!"
set /a "v_i_lIO00I=(((139-43)-34)+(10-10))"
for /f "tokens=2 delims==" %%I in ('set v_i_lIO00I') do call set "v_l_III_I00OlI=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_IOl_00OlI0=!v_l_III_I00OlI!"
set /a "v_i_l0l0I_=(((26+6)*2)+(26-26))"
set "v_p__I_0IOll0_=v_l_l__lll_0_I"
for /f "tokens=2 delims==" %%I in ('set v_i_l0l0I_') do for /f "delims=" %%A in ("!v_p__I_0IOll0_!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c___IO_ll_0I=!v_l_l__lll_0_I!"
set /a "v_i_IOI0Ol=((59-19)+(5-5))"
set "v_p_OO00lOlOI0=v_l__0O_IOI_I_"
for /f "tokens=2 delims==" %%I in ('set v_i_IOI0Ol') do for /f "delims=" %%A in ("!v_p_OO00lOlOI0!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_lO_0lll__l=!v_l__0O_IOI_I_!"
set /a "v_i_O_l_O_=(-18+21)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_l_O_') do call set "v_l_lI00_lO0l_=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_l0l_IOIlIl=!v_l_lI00_lO0l_!"
set /a "v_i_O0Ol00=((((1+35)-39)+21)+(1-1))"
for /f "tokens=2 delims==" %%I in ('set v_i_O0Ol00') do call set "v_l_OlO_l_O_OO=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_lIlO0IlII0=!v_l_OlO_l_O_OO!"
set /a "v_i__0I_I_=((((14*3)+2)-10)-21)"
set "v_p_IlIOOIlOIl=v_l_I0I_OI0IOI"
for /f "tokens=2 delims==" %%I in ('set v_i__0I_I_') do for /f "delims=" %%A in ("!v_p_IlIOOIlOIl!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__Il_I0O0OO=!v_l_I0I_OI0IOI!"
set /a "v_i__I0lII=((((17*3)+2)-33)+41)"
for /f "tokens=2 delims==" %%I in ('set v_i__I0lII') do call call call set "v_c__I0lOIllII=%%%%pool__l_000_0:~%%I,1%%%%"
set /a "v_i_O0IIlI=(54-1)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0IIlI') do call set "v_l_I00OIll00l=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_Ol_O0IOIIO=!v_l_I00OIll00l!"
set /a "v_i_lIOO_I=((((4*4)+3)-12)+(23-23))"
for /f "tokens=2 delims==" %%I in ('set v_i_lIOO_I') do call set "v_l_I_0l_OIll_=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_O0O00Oll0l=!v_l_I_0l_OIll_!"
set /a "v_i_I_IlOO=(((94+16)-29)-23)"
set "v_p__lll00_lII=v_l_lIl0_OIO0I"
for /f "tokens=2 delims==" %%I in ('set v_i_I_IlOO') do for /f "delims=" %%A in ("!v_p__lll00_lII!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_Il_l0I_IOI=!v_l_lIl0_OIO0I!"
set /a "v_i___0lI0=(((32*3)+1)-47)"
set "v_p_lOO0OO0O__=v_l__OOOI__00_"
for /f "tokens=2 delims==" %%I in ('set v_i___0lI0') do for /f "delims=" %%A in ("!v_p_lOO0OO0O__!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_IIl_l00_lI=!v_l__OOOI__00_!"
set /a "v_i_I_O_OI=(6+1)"
set "v_p__l_I___IIO=v_l_IOOlIllOlI"
for /f "tokens=2 delims==" %%I in ('set v_i_I_O_OI') do for /f "delims=" %%A in ("!v_p__l_I___IIO!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_OlOlII_lll=!v_l_IOOlIllOlI!"
set /a "v_i__I0OOI=((((77-49)-20)*6)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i__I0OOI') do call set "v_l_IO_O_II_Ol=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_lO0IllI0Ol=!v_l_IO_O_II_Ol!"
set /a "v_i_OOl0IO=(((7*5)-3)+(24-24))"
for /f "tokens=2 delims==" %%I in ('set v_i_OOl0IO') do call set "v_l_I_O__I0_OI=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c___0I0_0_IO=!v_l_I_O__I0_OI!"
set /a "v_i___IlOO=((12-33)+31)"
set "v_p_I____O0IlO=v_l_OlO0_Il_II"
for /f "tokens=2 delims==" %%I in ('set v_i___IlOO') do for /f "delims=" %%A in ("!v_p_I____O0IlO!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c__0_IOllOOO=!v_l_OlO0_Il_II!"
set /a "v_i_Ol_I0I=33"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol_I0I') do call set "v_l_OO0l0IIllI=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_llIOI0O_ll=!v_l_OO0l0IIllI!"
set /a "v_i_l0O_00=((34*3)-48)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0O_00') do call set "v_l_lIIOI0_0lO=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_OlIlOI_00l=!v_l_lIIOI0_0lO!"
set /a "v_i_O_lI_O=(-19+49)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_lI_O') do call call call set "v_c_IIOI_0llIl=%%%%pool__l_000_0:~%%I,1%%%%"
set /a "v_i_I___l_=(((-43+17)+26)*6)"
set "v_p_lO_O0II0_0=v_l_ll_lO_00O_"
for /f "tokens=2 delims==" %%I in ('set v_i_I___l_') do for /f "delims=" %%A in ("!v_p_lO_O0II0_0!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__IIIlOIOOO=!v_l_ll_lO_00O_!"
set /a "v_i_OO_l__=((((45-44)*3)+1)+(22-22))"
set "v_p_I0O__Illll=v_l_l0O___llI_"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_l__') do for /f "delims=" %%A in ("!v_p_I0O__Illll!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_lI___0lOl0=!v_l_l0O___llI_!"
set /a "v_i_l0OO_l=((111-28)-20)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0OO_l') do call set "v_l__ll_IlO0lO=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_O0l_lOI0l0=!v_l__ll_IlO0lO!"
set /a "v_i_Ol__lO=(((-36+45)-1)+7)"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol__lO') do call call call set "v_c_l00OOIIO_O=%%COMSPEC:~%%I,1%%"
set /a "v_i___lI_l=43"
set "v_p_O0__lOIO_I=v_l_l_00_IlOOI"
for /f "tokens=2 delims==" %%I in ('set v_i___lI_l') do for /f "delims=" %%A in ("!v_p_O0__lOIO_I!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_O_llIlIO00=!v_l_l_00_IlOOI!"
set /a "v_i_O00_lO=((((-1+23)*3)+1)-45)"
set "v_p_OOl_l__Ol0=v_l_Il_I00IO0l"
for /f "tokens=2 delims==" %%I in ('set v_i_O00_lO') do for /f "delims=" %%A in ("!v_p_OOl_l__Ol0!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_lI0Il_Il_I=!v_l_Il_I00IO0l!"
set /a "v_i__I__IO=(((5*5)+35)-40)"
for /f "tokens=2 delims==" %%I in ('set v_i__I__IO') do call call call set "v_c_OlI_l_0_l_=%%COMSPEC:~%%I,1%%"
set /a "v_i__l0_OI=((66+41)-48)"
for /f "tokens=2 delims==" %%I in ('set v_i__l0_OI') do call set "v_l_OOOl__lI0l=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_I00I0I_0Ol=!v_l_OOOl__lI0l!"
set /a "v_i_IlO__l=(((((2*6)+3)-22)+11)+(12-12))"
set "v_p__Oll0l0II_=v_l_lII0I00OOI"
for /f "tokens=2 delims==" %%I in ('set v_i_IlO__l') do for /f "delims=" %%A in ("!v_p__Oll0l0II_!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_OOI_O_lO00=!v_l_lII0I00OOI!"
set /a "v_i_Olll0l=(22*2)"
for /f "tokens=2 delims==" %%I in ('set v_i_Olll0l') do call set "v_l_llI000_0I0=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_OlOlOlI0O0=!v_l_llI000_0I0!"
set /a "v_i_IOI0OO=((((12-34)+42)*3)+2)"
set "v_p_IOlO_l00_I=v_l_lI__O0_OOO"
for /f "tokens=2 delims==" %%I in ('set v_i_IOI0OO') do for /f "delims=" %%A in ("!v_p_IOlO_l00_I!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_l0_l_0I_0O=!v_l_lI__O0_OOO!"
set /a "v_i__OO_0I=(((7*5)+2)+23)"
for /f "tokens=2 delims==" %%I in ('set v_i__OO_0I') do call set "v_l_O_I0_lOOOl=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_IOl000Il__=!v_l_O_I0_lOOOl!"
set /a "v_i__I__O0=((((12+5)+17)+22)+(6-6))"
for /f "tokens=2 delims==" %%I in ('set v_i__I__O0') do call set "v_l_III00_0_0_=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c__l__0__IO0=!v_l_III00_0_0_!"
set /a "v_i__l_0lO=((46-42)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i__l_0lO') do call call call set "v_c_O_O_I0l0O_=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set /a "v_i_lOOIO0=(((13*5)+4)-3)"
for /f "tokens=2 delims==" %%I in ('set v_i_lOOIO0') do call call call set "v_c_O_llIlOlO_=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set /a "v_i_OOO_Il=(((-25+30)*3)+(8-8))"
for /f "tokens=2 delims==" %%I in ('set v_i_OOO_Il') do call call call set "v_c_OO00I_O0OO=%%COMSPEC:~%%I,1%%"
set /a "v_i_IlII_0=(-28+29)"
for /f "tokens=2 delims==" %%I in ('set v_i_IlII_0') do call set "v_l_II_0lO0Ill=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_IIIIIOO_ll=!v_l_II_0lO0Ill!"
set /a "v_i__OIIOO=(((119-17)-45)+9)"
set "v_p_I0_l0II0II=v_l_IOIl000O0_"
for /f "tokens=2 delims==" %%I in ('set v_i__OIIOO') do for /f "delims=" %%A in ("!v_p_I0_l0II0II!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c__lIlI0l__l=!v_l_IOIl000O0_!"
set /a "v_i_llII_0=((-33+7)+39)"
for /f "tokens=2 delims==" %%I in ('set v_i_llII_0') do call call call set "v_c_lOlI0O0l0l=%%%%pool__l_000_0:~%%I,1%%%%"
set /a "v_i__O_O0O=(((89-8)+7)-30)"
for /f "tokens=2 delims==" %%I in ('set v_i__O_O0O') do call set "v_l_Il0O0OOl_I=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__I_l_l00lO=!v_l_Il0O0OOl_I!"
set /a "v_i_lO00I0=((34+13)+(13-13))"
set "v_p_lIllI_____=v_l__O_IOI_I0O"
for /f "tokens=2 delims==" %%I in ('set v_i_lO00I0') do for /f "delims=" %%A in ("!v_p_lIllI_____!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_OI__IO__l0=!v_l__O_IOI_I0O!"
set /a "v_i__IlOl_=(((((1*4)+3)*3)+23)+(20-20))"
for /f "tokens=2 delims==" %%I in ('set v_i__IlOl_') do call set "v_l_IIlIIIIIII=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_lI_I_l0l00=!v_l_IIlIIIIIII!"
set /a "v_i_lOO00l=((15+18)+(13-13))"
for /f "tokens=2 delims==" %%I in ('set v_i_lOO00l') do call set "v_l____IIl0OOO=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c__0_Il_IO0l=!v_l____IIl0OOO!"
set /a "v_i__00Oll=(34+30)"
set "v_p_lO_00_lIlO=v_l_IOIOIO_OI0"
for /f "tokens=2 delims==" %%I in ('set v_i__00Oll') do for /f "delims=" %%A in ("!v_p_lO_00_lIlO!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_O_OO0O0__O=!v_l_IOIOIO_OI0!"
set /a "v_i_I_lIl_=(((31-24)*4)+3)"
set "v_p_lOI0lIO_00=v_l_l_llI0000_"
for /f "tokens=2 delims==" %%I in ('set v_i_I_lIl_') do for /f "delims=" %%A in ("!v_p_lOI0lIO_00!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c__I__I__0_l=!v_l_l_llI0000_!"
set /a "v_i___0I__=(((0*4)*4)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i___0I__') do call call call set "v_c_I_I_I_0I_l=%%%%pool__l_000_0:~%%I,1%%%%"
set /a "v_i__lO0I_=((((36+4)-39)*6)+5)"
for /f "tokens=2 delims==" %%I in ('set v_i__lO0I_') do call call call set "v_c__0l0I00I00=%%%%pool_I00l0_ll:~%%I,1%%%%"
set /a "v_i_lO0O0_=((29-20)*4)"
set "v_p_O_O_lI0I0I=v_l_lll0I000Il"
for /f "tokens=2 delims==" %%I in ('set v_i_lO0O0_') do for /f "delims=" %%A in ("!v_p_O_O_lI0I0I!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__OOlIl__Il=!v_l_lll0I000Il!"
set /a "v_i__OIl_l=(105-37)"
for /f "tokens=2 delims==" %%I in ('set v_i__OIl_l') do call set "v_l_OOO0_ll_OO=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__IIO_lO00_=!v_l_OOO0_ll_OO!"
set /a "v_i____OI0=(((-62+17)+47)+(15-15))"
set "v_p_OllOl_lO_0=v_l_Oll_lIOO__"
for /f "tokens=2 delims==" %%I in ('set v_i____OI0') do for /f "delims=" %%A in ("!v_p_OllOl_lO_0!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_lIl0IO__0l=!v_l_Oll_lIOO__!"
set /a "v_i_O_l00O=(((6*5)+4)+14)"
set "v_p_lO0I0IlOIl=v_l__0I0lllOlI"
for /f "tokens=2 delims==" %%I in ('set v_i_O_l00O') do for /f "delims=" %%A in ("!v_p_lO0I0IlOIl!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_IOllOIIO00=!v_l__0I0lllOlI!"
set /a "v_i_O_I_0l=(((-32+32)*6)*6)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_I_0l') do call call call set "v_c__IO__l0_00=%%%%pool_I00l0_ll:~%%I,1%%%%"
set /a "v_i__IO_0_=((((1*5)+2)*3)+(29-29))"
set "v_p_OOI0OO_Oll=v_l__0O_O_l00I"
for /f "tokens=2 delims==" %%I in ('set v_i__IO_0_') do for /f "delims=" %%A in ("!v_p_OOI0OO_Oll!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_O_OIOIlIl_=!v_l__0O_O_l00I!"
set /a "v_i_I__l__=((((-54+46)+8)*2)+(19-19))"
for /f "tokens=2 delims==" %%I in ('set v_i_I__l__') do call set "v_l_I_O0__lll0=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_OI_lI0__0_=!v_l_I_O0__lll0!"
set /a "v_i___llll=((0*2)+46)"
set "v_p_lII000_IlO=v_l_OO___IIl0O"
for /f "tokens=2 delims==" %%I in ('set v_i___llll') do for /f "delims=" %%A in ("!v_p_lII000_IlO!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c__O_0IOllII=!v_l_OO___IIl0O!"
set /a "v_i_Ol0I_I=((((-28+29)+9)*5)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol0I_I') do call set "v_l_OO_0I_0Ill=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_IOII0_Il0_=!v_l_OO_0I_0Ill!"
set /a "v_i_llIl0_=((((-2*6)+3)+15)+(20-20))"
set "v_p_l0O__O0Il0=v_l_Ol_l_0I0Ol"
for /f "tokens=2 delims==" %%I in ('set v_i_llIl0_') do for /f "delims=" %%A in ("!v_p_l0O__O0Il0!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_O_lO000_0_=!v_l_Ol_l_0I0Ol!"
set /a "v_i_ll0O00=(((13*3)+1)+(11-11))"
set "v_p_I0_I_lO_O0=v_l_Ol0O_O00Ol"
for /f "tokens=2 delims==" %%I in ('set v_i_ll0O00') do for /f "delims=" %%A in ("!v_p_I0_I_lO_O0!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_O_I0Il_O_0=!v_l_Ol0O_O00Ol!"
set /a "v_i_OOOO_0=((11*2)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_OOOO_0') do call set "v_l_IlOOlOI_l_=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__IOO0IOI_0=!v_l_IlOOlOI_l_!"
set /a "v_i_Oll_0l=(66-45)"
set "v_p__I0_OIO0II=v_l___0I_O____"
for /f "tokens=2 delims==" %%I in ('set v_i_Oll_0l') do for /f "delims=" %%A in ("!v_p__I0_OIO0II!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_IlOll_OIIl=!v_l___0I_O____!"
set /a "v_i_IOlO_I=(12+20)"
set "v_p_I_O0O0O_0_=v_l__l_00OllO0"
for /f "tokens=2 delims==" %%I in ('set v_i_IOlO_I') do for /f "delims=" %%A in ("!v_p_I_O0O0O_0_!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_I_llllIl_l=!v_l__l_00OllO0!"
set /a "v_i_Ill_00=(((-31+44)+12)+35)"
set "v_p_OI00Il___l=v_l_OlI_lIO_I0"
for /f "tokens=2 delims==" %%I in ('set v_i_Ill_00') do for /f "delims=" %%A in ("!v_p_OI00Il___l!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__O0IlII0I_=!v_l_OlI_lIO_I0!"
set /a "v_i_lIlOO_=((82-39)+(24-24))"
set "v_p_Il_l_I00_I=v_l_O_Il_l0_O0"
for /f "tokens=2 delims==" %%I in ('set v_i_lIlOO_') do for /f "delims=" %%A in ("!v_p_Il_l_I00_I!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c__I_0l_O00O=!v_l_O_Il_l0_O0!"
set /a "v_i_OIOl_O=(((((40-37)*5)+3)*3)+1)"
set "v_p_l_Ill0_I0I=v_l__O_l_lIl_0"
for /f "tokens=2 delims==" %%I in ('set v_i_OIOl_O') do for /f "delims=" %%A in ("!v_p_l_Ill0_I0I!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c___0Oll__lO=!v_l__O_l_lIl_0!"
set /a "v_i___IO_l=(((50-18)-30)+17)"
set "v_p__Oll_OI0_O=v_l_l0_I0_0000"
for /f "tokens=2 delims==" %%I in ('set v_i___IO_l') do for /f "delims=" %%A in ("!v_p__Oll_OI0_O!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_I_0_I__0ll=!v_l_l0_I0_0000!"
set /a "v_i_OOI_0_=(((((6*3)+1)*2)+1)-25)"
set "v_p_OO00_O0I_O=v_l___I0Oll0_I"
for /f "tokens=2 delims==" %%I in ('set v_i_OOI_0_') do for /f "delims=" %%A in ("!v_p_OO00_O0I_O!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_O0I_OI__O0=!v_l___I0Oll0_I!"
set /a "v_i_OlI0O_=((64+11)-44)"
set "v_p_OIlIOOIO_I=v_l_ll00_OO00l"
for /f "tokens=2 delims==" %%I in ('set v_i_OlI0O_') do for /f "delims=" %%A in ("!v_p_OIlIOOIO_I!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_Ill0OOO0IO=!v_l_ll00_OO00l!"
set /a "v_i_O_00OO=((103-42)+(30-30))"
set "v_p_OIOO_l_IlI=v_l__OO_O0O0l_"
for /f "tokens=2 delims==" %%I in ('set v_i_O_00OO') do for /f "delims=" %%A in ("!v_p_OIOO_l_IlI!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c____IIO0OOI=!v_l__OO_O0O0l_!"
set /a "v_i_I__l_O=((((-3*5)+3)+32)+15)"
set "v_p_lO0ll0Ol_I=v_l___OOOlIlOl"
for /f "tokens=2 delims==" %%I in ('set v_i_I__l_O') do for /f "delims=" %%A in ("!v_p_lO0ll0Ol_I!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_OIlO0IOO_l=!v_l___OOOlIlOl!"
set /a "v_i_IIll_O=(19-2)"
for /f "tokens=2 delims==" %%I in ('set v_i_IIll_O') do call set "v_l_OII00lI_O_=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c__l_IIII_O_=!v_l_OII00lI_O_!"
set /a "v_i_IlllIO=((((18-17)*2)*4)+(20-20))"
for /f "tokens=2 delims==" %%I in ('set v_i_IlllIO') do call set "v_l__O000I0_Ol=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c___lIIl000I=!v_l__O000I0_Ol!"
set /a "v_i_OO0O_l=(((57-10)-13)-4)"
set "v_p_O__00__lO0=v_l_IIIIl0lIIl"
for /f "tokens=2 delims==" %%I in ('set v_i_OO0O_l') do for /f "delims=" %%A in ("!v_p_O__00__lO0!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c__0__IO000l=!v_l_IIIIl0lIIl!"
set /a "v_i_I_0OlI=((((48-41)*6)+4)+(19-19))"
for /f "tokens=2 delims==" %%I in ('set v_i_I_0OlI') do call set "v_l_l__0O0_I_O=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_IO_llOll_0=!v_l_l__0O0_I_O!"
set /a "v_i__0l0Il=(5+33)"
for /f "tokens=2 delims==" %%I in ('set v_i__0l0Il') do call call call set "v_c__0O00_I0OI=%%%%pool_I00l0_ll:~%%I,1%%%%"
set /a "v_i_O0lO_0=((1*6)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0lO_0') do call set "v_l_l_O_IlOO__=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_lOO0_IOlOI=!v_l_l_O_IlOO__!"
set /a "v_i_l_l_00=(((((-9*2)+1)+17)*6)+5)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_l_00') do call call call set "v_c_lO_O__IlOl=%%OS:~%%I,1%%"
set /a "v_i_IOOlOl=((((52-49)*4)+3)*2)"
set "v_p_OllOIOOOOO=v_l_I0_OOlOOlO"
for /f "tokens=2 delims==" %%I in ('set v_i_IOOlOl') do for /f "delims=" %%A in ("!v_p_OllOIOOOOO!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_IIIIII_IOI=!v_l_I0_OOlOOlO!"
set /a "v_i_I00OIl=(((77+13)-12)-37)"
for /f "tokens=2 delims==" %%I in ('set v_i_I00OIl') do call set "v_l_O00ll_O_l_=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_lOIIII0lI0=!v_l_O00ll_O_l_!"
set /a "v_i__lOOII=(((((0*4)+3)*6)+3)+(30-30))"
for /f "tokens=2 delims==" %%I in ('set v_i__lOOII') do call set "v_l_O_0I_0IOOl=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_O_0OOl0IlO=!v_l_O_0I_0IOOl!"
set /a "v_i___I0_I=(12*2)"
for /f "tokens=2 delims==" %%I in ('set v_i___I0_I') do call set "v_l_llIl_0OI_l=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__00O00lII_=!v_l_llIl_0OI_l!"
set /a "v_i_OO_IOO=((((8*4)+3)+23)+(17-17))"
set "v_p_OlOO0I0O0I=v_l_IIl0_IIOII"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_IOO') do for /f "delims=" %%A in ("!v_p_OlOO0I0O0I!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_OllOIOIIII=!v_l_IIl0_IIOII!"
set /a "v_i__OI0__=(63-2)"
set "v_p__Il_OI000I=v_l_lO00_Il0__"
for /f "tokens=2 delims==" %%I in ('set v_i__OI0__') do for /f "delims=" %%A in ("!v_p__Il_OI000I!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_OI__I_0O_l=!v_l_lO00_Il0__!"
set /a "v_i_llIO_0=(12*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_llIO_0') do call set "v_l_IlOO_OI__0=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_OOI00lO_0_=!v_l_IlOO_OI__0!"
set /a "v_i___0_IO=(((-42+31)+35)+39)"
set "v_p_OOl0Il____=v_l_IlI0II0_lI"
for /f "tokens=2 delims==" %%I in ('set v_i___0_IO') do for /f "delims=" %%A in ("!v_p_OOl0Il____!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_OI_OIIII0O=!v_l_IlI0II0_lI!"
set /a "v_i__O_Ol_=(((((2+3)*3)+1)*4)+2)"
set "v_p__IOlOlII0I=v_l__O_0l0OOOO"
for /f "tokens=2 delims==" %%I in ('set v_i__O_Ol_') do for /f "delims=" %%A in ("!v_p__IOlOlII0I!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_IlI0O_O0IO=!v_l__O_0l0OOOO!"
set /a "v_i_IIOI_O=((100-36)-41)"
set "v_p_IlIOIlOI_I=v_l_O0O0Illl00"
for /f "tokens=2 delims==" %%I in ('set v_i_IIOI_O') do for /f "delims=" %%A in ("!v_p_IlIOIlOI_I!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_llIO00l00O=!v_l_O0O0Illl00!"
set /a "v_i_lI00lI=((88-48)+(2-2))"
set "v_p_II___lO0Il=v_l_O0I__lII0_"
for /f "tokens=2 delims==" %%I in ('set v_i_lI00lI') do for /f "delims=" %%A in ("!v_p_II___lO0Il!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_OOl_0_lIII=!v_l_O0I__lII0_!"
set /a "v_i__l_I__=(((-38+46)+48)+(7-7))"
set "v_p__OOO_O___O=v_l__OOl0IIIIl"
for /f "tokens=2 delims==" %%I in ('set v_i__l_I__') do for /f "delims=" %%A in ("!v_p__OOO_O___O!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_O0_0l__II0=!v_l__OOl0IIIIl!"
set /a "v_i_OOllO_=((30+40)-8)"
set "v_p_lO0Ol0OIlI=v_l_l_0l_OO__I"
for /f "tokens=2 delims==" %%I in ('set v_i_OOllO_') do for /f "delims=" %%A in ("!v_p_lO0Ol0OIlI!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_lI0I0_OOOI=!v_l_l_0l_OO__I!"
set /a "v_i_O0O0lO=((-8+30)-6)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0O0lO') do call set "v_l__0_00OI__l=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_lIIl0I_Oll=!v_l__0_00OI__l!"
set /a "v_i_O0Il_I=((((17-27)*3)+1)+39)"
set "v_p_I__O0Olll_=v_l_II_I_O_I0l"
for /f "tokens=2 delims==" %%I in ('set v_i_O0Il_I') do for /f "delims=" %%A in ("!v_p_I__O0Olll_!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_OlI00__OlO=!v_l_II_I_O_I0l!"
set /a "v_i__III_O=((-37+46)+(19-19))"
set "v_p_IIllOll_0O=v_l_l00OO_0__O"
for /f "tokens=2 delims==" %%I in ('set v_i__III_O') do for /f "delims=" %%A in ("!v_p_IIllOll_0O!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_IOI_0l0IIl=!v_l_l00OO_0__O!"
set /a "v_i_l_OIOl=(((((2*5)+1)*4)+2)-46)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_OIOl') do call call call set "v_c_I_O0Ol_I0l=%%COMSPEC:~%%I,1%%"
set /a "v_i_IO0I0_=((((2*3)+1)+5)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_IO0I0_') do call set "v_l_ll0O0OI00_=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_lOOIOlIllO=!v_l_ll0O0OI00_!"
set /a "v_i_O_I_ll=(9*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_I_ll') do call set "v_l__l_lOIIOI0=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c__lIlI0I_ll=!v_l__l_lOIIOI0!"
set /a "v_i_I_IOlI=(86-23)"
set "v_p__Il0_OI0_l=v_l_IlO0_l0llO"
for /f "tokens=2 delims==" %%I in ('set v_i_I_IOlI') do for /f "delims=" %%A in ("!v_p__Il0_OI0_l!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_I0_0lO0IO_=!v_l_IlO0_l0llO!"
set /a "v_i_llOl0l=(5+13)"
set "v_p_lIOOl__l0O=v_l__ll__OO_Il"
for /f "tokens=2 delims==" %%I in ('set v_i_llOl0l') do for /f "delims=" %%A in ("!v_p_lIOOl__l0O!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c__00__OlOI0=!v_l__ll__OO_Il!"
set /a "v_i_l_000_=(((0*5)*3)*5)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_000_') do call call call set "v_c_lI__OO_0lO=%%OS:~%%I,1%%"
set /a "v_i_IIO__0=((((1-49)+5)+50)+(11-11))"
set "v_p_l00__O00OO=v_l_lOllIIIOOI"
for /f "tokens=2 delims==" %%I in ('set v_i_IIO__0') do for /f "delims=" %%A in ("!v_p_l00__O00OO!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_OOllO_l0_l=!v_l_lOllIIIOOI!"
set /a "v_i__lOI00=(((-3*4)+1)+30)"
for /f "tokens=2 delims==" %%I in ('set v_i__lOI00') do call call call set "v_c__0l_0I_IIl=%%%%pool_I00l0_ll:~%%I,1%%%%"
set /a "v_i__lO_OO=(45+12)"
set "v_p__OlIl0OlOI=v_l____IIO_l__"
for /f "tokens=2 delims==" %%I in ('set v_i__lO_OO') do for /f "delims=" %%A in ("!v_p__OlIl0OlOI!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_lOll__0I_0=!v_l____IIO_l__!"
set /a "v_i_IO_lO0=(9+30)"
for /f "tokens=2 delims==" %%I in ('set v_i_IO_lO0') do call set "v_l_O_000OOO_I=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_Il0l_0__O_=!v_l_O_000OOO_I!"
set /a "v_i_I0_lII=(((((6*6)+5)*2)-19)+(22-22))"
for /f "tokens=2 delims==" %%I in ('set v_i_I0_lII') do call set "v_l_OII0OlOI0O=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_O___OI0IO_=!v_l_OII0OlOI0O!"
set /a "v_i_l0ll_O=((((5-5)*2)+1)+18)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0ll_O') do call call call set "v_c_OIIO_l0I00=%%%%pool__l_000_0:~%%I,1%%%%"
set /a "v_i__lOIlO=((32-26)+(3-3))"
for /f "tokens=2 delims==" %%I in ('set v_i__lOIlO') do call set "v_l_OO0_O0I0OI=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_II0ll0IIlO=!v_l_OO0_O0I0OI!"
set /a "v_i_lI0I_0=((73+8)-34)"
set "v_p_Ol_Ol_0OOO=v_l_O0OIl_00I0"
for /f "tokens=2 delims==" %%I in ('set v_i_lI0I_0') do for /f "delims=" %%A in ("!v_p_Ol_Ol_0OOO!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c___l00I__Ol=!v_l_O0OIl_00I0!"
set /a "v_i_OIllOl=((((-34+10)+20)+6)+(6-6))"
set "v_p__II_l__0__=v_l_ll_l0l__0O"
for /f "tokens=2 delims==" %%I in ('set v_i_OIllOl') do for /f "delims=" %%A in ("!v_p__II_l__0__!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_lIlOOl0_I0=!v_l_ll_l0l__0O!"
set /a "v_i_IO0_OI=34"
for /f "tokens=2 delims==" %%I in ('set v_i_IO0_OI') do call call call set "v_c___O0OOO0O0=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set /a "v_i_lOlOO0=((3*4)+1)"
set "v_p_IO__OOO0I0=v_l_IOIlO0O00I"
for /f "tokens=2 delims==" %%I in ('set v_i_lOlOO0') do for /f "delims=" %%A in ("!v_p_IO__OOO0I0!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c___l0l_O0ll=!v_l_IOIlO0O00I!"
set /a "v_i_OIlIO0=((((1*6)+3)*3)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_OIlIO0') do call set "v_l_lll_0_IIOl=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__l0lIl__II=!v_l_lll_0_IIOl!"
set /a "v_i__O0lOO=((((((-16+17)*6)+3)*3)+1)+(22-22))"
set "v_p__0OI0Ol0ll=v_l_l_I0lO_Oll"
for /f "tokens=2 delims==" %%I in ('set v_i__O0lOO') do for /f "delims=" %%A in ("!v_p__0OI0Ol0ll!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_OI_I0_Ol_0=!v_l_l_I0lO_Oll!"
set /a "v_i___I_O0=((((40-33)*5)+4)-6)"
for /f "tokens=2 delims==" %%I in ('set v_i___I_O0') do call set "v_l__Il_Ol0llI=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c____0lIOO__=!v_l__Il_Ol0llI!"
set /a "v_i_I000II=((4+19)+(4-4))"
set "v_p__Il__l0OOl=v_l_IlIl0O0I0O"
for /f "tokens=2 delims==" %%I in ('set v_i_I000II') do for /f "delims=" %%A in ("!v_p__Il__l0OOl!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_IlO0ll0_Ol=!v_l_IlIl0O0I0O!"
set /a "v_i_l0I___=(7*6)"
set "v_p__l_IO0_llO=v_l_Ol__l_I00_"
for /f "tokens=2 delims==" %%I in ('set v_i_l0I___') do for /f "delims=" %%A in ("!v_p__l_IO0_llO!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_O0l0OI__l_=!v_l_Ol__l_I00_!"
set /a "v_i__O0I0O=((23+2)+(29-29))"
set "v_p_OOlIlIO0_0=v_l_IOOIII0O_0"
for /f "tokens=2 delims==" %%I in ('set v_i__O0I0O') do for /f "delims=" %%A in ("!v_p_OOlIlIO0_0!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_I00lOO_I__=!v_l_IOOIII0O_0!"
set /a "v_i_I00OII=((93-35)+9)"
set "v_p_lOI0O0__OI=v_l__ll0_Il__0"
for /f "tokens=2 delims==" %%I in ('set v_i_I00OII') do for /f "delims=" %%A in ("!v_p_lOI0O0__OI!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c___IOI_l_l_=!v_l__ll0_Il__0!"
set /a "v_i_I00Ol0=((66-32)+(22-22))"
for /f "tokens=2 delims==" %%I in ('set v_i_I00Ol0') do call set "v_l_l__OIIOll_=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_OOOIIl00Ol=!v_l_l__OIIOll_!"
set /a "v_i_O_lI00=(((-15+50)-40)+32)"
set "v_p__I_lIO_IOO=v_l_IO0Olll_O_"
for /f "tokens=2 delims==" %%I in ('set v_i_O_lI00') do for /f "delims=" %%A in ("!v_p__I_lIO_IOO!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c____0l0OO0I=!v_l_IO0Olll_O_!"
set /a "v_i_I0_O_0=(((((3*3)+2)*3)*2)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0_O_0') do call set "v_l_Ol_I_0__O0=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_II0I_I__lI=!v_l_Ol_I_0__O0!"
set /a "v_i__Il_O_=(((27-9)*2)+1)"
set "v_p_O_l_llOl0I=v_l_Il_Il0O_00"
for /f "tokens=2 delims==" %%I in ('set v_i__Il_O_') do for /f "delims=" %%A in ("!v_p_O_l_llOl0I!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_lIOIlOIll0=!v_l_Il_Il0O_00!"
set /a "v_i_OOllOO=(8+32)"
set "v_p_I0I_OOIO__=v_l_l0O_IIlO_I"
for /f "tokens=2 delims==" %%I in ('set v_i_OOllOO') do for /f "delims=" %%A in ("!v_p_I0I_OOIO__!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_IO__l00lO_=!v_l_l0O_IIlO_I!"
set /a "v_i_l0_I0l=(((-22*2)+13)+45)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0_I0l') do call set "v_l___lOII0l_I=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_I_OOIOIOOO=!v_l___lOII0l_I!"
set /a "v_i___OOIO=(37-26)"
set "v_p_lII0lI0IlI=v_l__IOOOI_OOO"
for /f "tokens=2 delims==" %%I in ('set v_i___OOIO') do for /f "delims=" %%A in ("!v_p_lII0lI0IlI!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_I_0O0llllO=!v_l__IOOOI_OOO!"
set /a "v_i_Oll0lI=((((4*2)*2)+1)+(26-26))"
for /f "tokens=2 delims==" %%I in ('set v_i_Oll0lI') do call set "v_l____OIl__ll=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_l0OlI_0llO=!v_l____OIl__ll!"
set /a "v_i_OI_OII=((-47+50)*2)"
for /f "tokens=2 delims==" %%I in ('set v_i_OI_OII') do call set "v_l_II0IOOIIII=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_I_O_O0OIOO=!v_l_II0IOOIIII!"
set /a "v_i_l_Ol0O=(((115-49)+42)-44)"
set "v_p_lOI_I__I0O=v_l_lIl_0ll0ll"
for /f "tokens=2 delims==" %%I in ('set v_i_l_Ol0O') do for /f "delims=" %%A in ("!v_p_lOI_I__I0O!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_IlI_0OO00_=!v_l_lIl_0ll0ll!"
set /a "v_i_O0OI0_=(((5*4)+2)+(17-17))"
set "v_p_l_Ol__l__0=v_l_lllOIIOlII"
for /f "tokens=2 delims==" %%I in ('set v_i_O0OI0_') do for /f "delims=" %%A in ("!v_p_l_Ol__l__0!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_OOlll00O0_=!v_l_lllOIIOlII!"
set /a "v_i_IOlI0I=(-24+39)"
set "v_p_IO0_lIO_0_=v_l__l_I_00O_O"
for /f "tokens=2 delims==" %%I in ('set v_i_IOlI0I') do for /f "delims=" %%A in ("!v_p_IO0_lIO_0_!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__00_IOO_0I=!v_l__l_I_00O_O!"
set /a "v_i_O0O0_O=(((((-6+33)-19)*4)+3)+(1-1))"
set "v_p_l_lI_0O_Il=v_l_O_O0OI00I0"
for /f "tokens=2 delims==" %%I in ('set v_i_O0O0_O') do for /f "delims=" %%A in ("!v_p_l_lI_0O_Il!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_II0I0ll0OO=!v_l_O_O0OI00I0!"
set /a "v_i_OO00l_=(((10*6)+4)+(26-26))"
for /f "tokens=2 delims==" %%I in ('set v_i_OO00l_') do call set "v_l__O_lO__O_l=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_l_OOl0Il_0=!v_l__O_lO__O_l!"
set /a "v_i_IO_OIl=((((15*3)-45)+44)+(2-2))"
set "v_p_lOlOIIO0lO=v_l_OII00I_Ill"
for /f "tokens=2 delims==" %%I in ('set v_i_IO_OIl') do for /f "delims=" %%A in ("!v_p_lOlOIIO0lO!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_ll_III0Il_=!v_l_OII00I_Ill!"
set /a "v_i_OlO_OI=(((-47+45)+8)*2)"
for /f "tokens=2 delims==" %%I in ('set v_i_OlO_OI') do call set "v_l_Ol_II_Il_0=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_lll0Ol_llO=!v_l_Ol_II_Il_0!"
set /a "v_i__0Ol0I=(((-3+36)-18)+(18-18))"
for /f "tokens=2 delims==" %%I in ('set v_i__0Ol0I') do call set "v_l__I0l00I_Ol=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_OlO0O0llOO=!v_l__I0l00I_Ol!"
set /a "v_i_OOOI00=(-28+40)"
for /f "tokens=2 delims==" %%I in ('set v_i_OOOI00') do call call call set "v_c_I0IIIOO0IO=%%COMSPEC:~%%I,1%%"
set /a "v_i_O0IO0_=(((((3*3)+1)+25)-32)+(27-27))"
set "v_p_l0ll_I_IIl=v_l_____OlIlOl"
for /f "tokens=2 delims==" %%I in ('set v_i_O0IO0_') do for /f "delims=" %%A in ("!v_p_l0ll_I_IIl!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c__0OOII_OO0=!v_l_____OlIlOl!"
set /a "v_i_I__O00=((2*5)+1)"
set "v_p_IIlIIlIl0I=v_l__O0IOOO_II"
for /f "tokens=2 delims==" %%I in ('set v_i_I__O00') do for /f "delims=" %%A in ("!v_p_IIlIIlIl0I!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_IOOll__IOI=!v_l__O0IOOO_II!"
set /a "v_i_I_lOO0=((12*2)+1)"
set "v_p_l_00OlIl0I=v_l_OIlIOI_I__"
for /f "tokens=2 delims==" %%I in ('set v_i_I_lOO0') do for /f "delims=" %%A in ("!v_p_l_00OlIl0I!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_l0_IllOI0I=!v_l_OIlIOI_I__!"
set /a "v_i_lIl0_l=(76-34)"
set "v_p_I0_ll_lIII=v_l_l0ll_O0_O_"
for /f "tokens=2 delims==" %%I in ('set v_i_lIl0_l') do for /f "delims=" %%A in ("!v_p_I0_ll_lIII!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_Oll_0__lO_=!v_l_l0ll_O0_O_!"
set /a "v_i_l0___l=(((((37-27)*5)+2)-23)+(19-19))"
set "v_p_OO0lO_I_O_=v_l_l0O0l0OO_O"
for /f "tokens=2 delims==" %%I in ('set v_i_l0___l') do for /f "delims=" %%A in ("!v_p_OO0lO_I_O_!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_OlIlIO___l=!v_l_l0O0l0OO_O!"
set /a "v_i_O0Ol_I=((60-12)+(25-25))"
for /f "tokens=2 delims==" %%I in ('set v_i_O0Ol_I') do call set "v_l_I_I0IOOIl0=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_l0I_lO0___=!v_l_I_I0IOOIl0!"
set /a "v_i__lI0l0=(((44-32)*5)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i__lI0l0') do call set "v_l_O0__0_000l=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_OIOIO_OIIl=!v_l_O0__0_000l!"
set /a "v_i_I_l00_=(51+1)"
set "v_p__lOOOIIOOI=v_l__O0O00l00O"
for /f "tokens=2 delims==" %%I in ('set v_i_I_l00_') do for /f "delims=" %%A in ("!v_p__lOOOIIOOI!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_IIIOI0IO__=!v_l__O0O00l00O!"
set /a "v_i_I_II0l=((-1*2)+3)"
set "v_p_OOll_l_OOl=v_l__II0ll_O__"
for /f "tokens=2 delims==" %%I in ('set v_i_I_II0l') do for /f "delims=" %%A in ("!v_p_OOll_l_OOl!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c__llIOI00l0=!v_l__II0ll_O__!"
set /a "v_i_l_lI_O=((49+3)+9)"
set "v_p__lOIlO0OOI=v_l__0IlIOIIlI"
for /f "tokens=2 delims==" %%I in ('set v_i_l_lI_O') do for /f "delims=" %%A in ("!v_p__lOIlO0OOI!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_IIll_0II__=!v_l__0IlIOIIlI!"
set /a "v_i___lIl_=((16-8)+36)"
for /f "tokens=2 delims==" %%I in ('set v_i___lIl_') do call call call set "v_c_I0O00llOIl=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set /a "v_i__l0ll_=(23-22)"
set "v_p_I00_OOIO0O=v_l_OlIOIO0000"
for /f "tokens=2 delims==" %%I in ('set v_i__l0ll_') do for /f "delims=" %%A in ("!v_p_I00_OOIO0O!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_O000__0ll0=!v_l_OlIOIO0000!"
set /a "v_i_OOlO0_=(35-14)"
for /f "tokens=2 delims==" %%I in ('set v_i_OOlO0_') do call set "v_l__I_IIlI_OO=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_OI_I0OIII0=!v_l__I_IIlI_OO!"
set /a "v_i_lO0l_O=(((((0*6)+3)*4)+1)+(16-16))"
for /f "tokens=2 delims==" %%I in ('set v_i_lO0l_O') do call set "v_l_I0l_I_lIII=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_O0Ol0I0l0_=!v_l_I0l_I_lIII!"
set /a "v_i_OO_llO=((-27+35)*5)"
set "v_p_llIO_lI_0_=v_l_OOlIll0III"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_llO') do for /f "delims=" %%A in ("!v_p_llIO_lI_0_!") do call set "%%A=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_lIIlO_0l0l=!v_l_OOlIll0III!"
set /a "v_i__000Il=(52+11)"
for /f "tokens=2 delims==" %%I in ('set v_i__000Il') do call set "v_l__lI_0l00_I=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c__0lI0_l0I0=!v_l__lI_0l00_I!"
set /a "v_i_l_I_00=((((-45+33)+26)*3)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_I_00') do call set "v_l__000ll_lOO=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_OOOOll_0_I=!v_l__000ll_lOO!"
set /a "v_i_l_I0l_=((((0*6)+1)*3)+1)"
set "v_p___00____I0=v_l__000_0lOI0"
for /f "tokens=2 delims==" %%I in ('set v_i_l_I0l_') do for /f "delims=" %%A in ("!v_p___00____I0!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_lllIOl_I0_=!v_l__000_0lOI0!"
set /a "v_i_I0IlI0=((41-38)+(20-20))"
set "v_p_l_lI00OI_l=v_l_lO0IIlIll_"
for /f "tokens=2 delims==" %%I in ('set v_i_I0IlI0') do for /f "delims=" %%A in ("!v_p_l_lI00OI_l!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c___Ol0lI00O=!v_l_lO0IIlIll_!"
set /a "v_i_lIlOOl=(((((23-22)*6)+2)*4)+2)"
set "v_p_O0lO00lO__=v_l_lII0I__IIO"
for /f "tokens=2 delims==" %%I in ('set v_i_lIlOOl') do for /f "delims=" %%A in ("!v_p_O0lO00lO__!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_IOl_00OIOl=!v_l_lII0I__IIO!"
set /a "v_i_lO00l0=(((3*4)+1)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_lO00l0') do call set "v_l_l_I00IOl_0=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c___lll0l_lO=!v_l_l_I00IOl_0!"
set /a "v_i_O_l0Ol=(((38-26)+11)+(23-23))"
for /f "tokens=2 delims==" %%I in ('set v_i_O_l0Ol') do call set "v_l_II0___0l0l=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_I0I_0l__Ol=!v_l_II0___0l0l!"
set /a "v_i_O0lOlI=((((68-3)-31)+8)+(8-8))"
set "v_p_O0_IlOO000=v_l__00_O0O_0_"
for /f "tokens=2 delims==" %%I in ('set v_i_O0lOlI') do for /f "delims=" %%A in ("!v_p_O0_IlOO000!") do call set "%%A=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_O0_OlI_lI_=!v_l__00_O0O_0_!"
set /a "v_i_Il_II_=(((-6+7)*4)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_Il_II_') do call set "v_l_l0llllll0O=%%%%pool__l_000_0:~%%I,1%%%%"
set "v_c_OO_Il0l_l0=!v_l_l0llllll0O!"
set /a "v_i_O_OlIl=(43-42)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_OlIl') do call set "v_l__I_llIl0OO=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c_lO_I_IOl00=!v_l__I_llIl0OO!"
set /a "v_i_lIIIII=((10+14)+(12-12))"
for /f "tokens=2 delims==" %%I in ('set v_i_lIIIII') do call set "v_l_lllIOlOl0l=%%%%pool_lOOO__Ol:~%%I,1%%%%"
set "v_c_l_Il_OlO_l=!v_l_lllIOlOl0l!"
set /a "v_i____0l_=((3+9)*3)"
set "v_p_l___OO0III=v_l_IIOI0l0O0O"
for /f "tokens=2 delims==" %%I in ('set v_i____0l_') do for /f "delims=" %%A in ("!v_p_l___OO0III!") do call set "%%A=%%%%pool_I00l0_ll:~%%I,1%%%%"
set "v_c__O0I0_l_ll=!v_l_IIOI0l0O0O!"
call !m_O_I0lOOIIO! "v_f_IIIllO0I___0=,!v_c_lIlO0IlII0!"
set "v_s_IIOlOOIlO0=!v_l_Ol_Ol0_l__!"
:L_DISPATCH
for /f "delims=" %%A in ("!v_s_IIOlOOIlO0!") do goto :%%A
:LB_EXIT_I_Illl0l
exit /b
:OOI0I_OIlOO_
for %%i ^in (!v_c_OOl_0_lIII!,!v_c_OOlll00O0_!!v_f_IIIllO0I___0!) do call !m__ll_0__I0O! %%i
call !m_O_I0lOOIIO! "v_s_IIOlOOIlO0=!v_l_IO0IOlIlO0!"
goto :L_DISPATCH
