@echo off
setlocal enabledelayedexpansion
chcp 65001 >nul 2>&1
set "m__O_O000_ll=pa^use"
set "p1_OlOlOI_I00=m__O_O000_ll"
set "p2__lO00llOO0=p1_OlOlOI_I00"
set "m_I_l0_lIl0I=ca^ll"
set "p1_I_0IIOl_0O=m_I_l0_lIl0I"
set "p2_O_II0lO_lI=p1_I_0IIOl_0O"
set "m_I__IO_IIlO=set"
set "p1__IIIlO0lOI=m_I__IO_IIlO"
set "p2_O0___IIIIl=p1__IIIlO0lOI"
set "m_IlIlO_00IO=echo"
set "p1_lOO0_I0l_0=m_IlIlO_00IO"
set "p2_I__0IllI_I=p1_lOO0_I0l_0"
set "m_O_I0OI_0I_=goto"
set "p1__OOO_0OO0I=m_O_I0OI_0I_"
set "p2_l_l___O_I0=p1__OOO_0OO0I"
set "m__00_00l0_I=ch^cp"
set "p1_III_Ol0lIO=m__00_00l0_I"
set "p2__OO__0I0l_=p1_III_Ol0lIO"
set "m_II0_I_0OII=rem"
set "p1_OIOOOll_00=m_II0_I_0OII"
set "p2_O0l_O_l_ll=p1_OIOOOll_00"
set "m__0_I_lOl_0=titl^e"
set "p1_III0llIOOO=m__0_I_lOl_0"
set "p2_O_0_Il___O=p1_III0llIOOO"
set "m_lO___0lO0l=exit"
set "p1_IOO_I0lO_l=m_lO___0lO0l"
set "p2_O_OlI0Ol_0=p1_IOO_I0lO_l"
set "v_l_OlIOOl0Oll=l__l_00IOI0I"
set "v_l_O0_0I0lOll=_l000_IOlll0"
set "v_l_OOl0OOI_IO=OI0OO_I___IO"
set "v_l__0O00OOlO0=LB_EXIT__II__O__"
set "pool_O0O_OlI0=@9:4MbJNSpze0.WFw-ZqUVıdmy/cQYTahgvLs7ABtK8x6oHnrD5IGCEjXukl_P12iR3Of\"
set /a "O0OI_I=(-11+35)" & rem R71tHz@s:d#rm
set /a "l_0lI0=((-7-13)+20)"
for /f "tokens=2 delims==" %%A in ('set O0OI_I ^^^| findstr /b /c:"O0OI_I="') do for /f "tokens=2 delims==" %%C in ('set l_0lI0 ^^^| findstr /b /c:"l_0lI0="') do call set "pool_O0O_OlI0=%%pool_O0O_OlI0:~%%A%%%%%%pool_O0O_OlI0:~%%C,%%A%%"
call set "pool_O0O_OlI0=%%pool_O0O_OlI0:d=#IATKJ#%%" & rem m6TDm
call set "pool_O0O_OlI0=%%pool_O0O_OlI0:\=d%%"
call set "pool_O0O_OlI0=%%pool_O0O_OlI0:#IATKJ#=\%%"
call set "pool_O0O_OlI0=%%pool_O0O_OlI0:f=#AYIEQSFU#%%" & rem dY]HYvAWx9@q4:
call set "pool_O0O_OlI0=%%pool_O0O_OlI0:Q=f%%"
call set "pool_O0O_OlI0=%%pool_O0O_OlI0:#AYIEQSFU#=Q%%"
set /a "lI0_OI=((((7-8)*6)+4)+15)" & rem -r2tUv
set /a "_I00lO=((9-9)*4)"
for /f "tokens=2 delims==" %%A in ('set lI0_OI ^^^| findstr /b /c:"lI0_OI="') do for /f "tokens=2 delims==" %%C in ('set _I00lO ^^^| findstr /b /c:"_I00lO="') do call set "pool_O0O_OlI0=%%pool_O0O_OlI0:~%%A%%%%%%pool_O0O_OlI0:~%%C,%%A%%"
set /a "_00_l0=((3*6)+2)" & rem F#s4iiAT
set /a "_0O_0_=((((6-24)-10)+28)+(10-10))"
for /f "tokens=2 delims==" %%A in ('set _00_l0 ^^^| findstr /b /c:"_00_l0="') do for /f "tokens=2 delims==" %%C in ('set _0O_0_ ^^^| findstr /b /c:"_0O_0_="') do call set "pool_O0O_OlI0=%%pool_O0O_OlI0:~%%A%%%%%%pool_O0O_OlI0:~%%C,%%A%%"
set /a "_O0O0O=((((2*6)+4)*2)+1)" & rem ,P:QoO9wg
set /a "OOIlOl=(12-12)"
for /f "tokens=2 delims==" %%A in ('set _O0O0O ^^^| findstr /b /c:"_O0O0O="') do for /f "tokens=2 delims==" %%C in ('set OOIlOl ^^^| findstr /b /c:"OOIlOl="') do call set "pool_O0O_OlI0=%%pool_O0O_OlI0:~%%A%%%%%%pool_O0O_OlI0:~%%C,%%A%%"
call set "pool_O0O_OlI0=%%pool_O0O_OlI0:_=#YWEGBNLC#%%" & rem ~wk4?Jb
call set "pool_O0O_OlI0=%%pool_O0O_OlI0:k=_%%"
call set "pool_O0O_OlI0=%%pool_O0O_OlI0:#YWEGBNLC#=k%%"
set "pool_lO0OlOll=/ap9qRyKGE3bTJg_m.lCfxVzd2cNS0ODY@vı5\X814rtk-BI6FiwZusehWMAjH:nQPUoL7"
set /a "IOIl0O=(((90+39)-24)-46)" & rem EN6SR4i9myv/
set /a "_0II0l=(((5*4)+3)-23)"
for /f "tokens=2 delims==" %%A in ('set IOIl0O ^^^| findstr /b /c:"IOIl0O="') do for /f "tokens=2 delims==" %%C in ('set _0II0l ^^^| findstr /b /c:"_0II0l="') do call set "pool_lO0OlOll=%%pool_lO0OlOll:~%%A%%%%%%pool_lO0OlOll:~%%C,%%A%%"
set /a "IO0IO0=((116-35)-36)" & rem niHpq=stI_HRI
set /a "_l0OO0=(((-25+47)-22)*6)"
for /f "tokens=2 delims==" %%A in ('set IO0IO0 ^^^| findstr /b /c:"IO0IO0="') do for /f "tokens=2 delims==" %%C in ('set _l0OO0 ^^^| findstr /b /c:"_l0OO0="') do call set "pool_lO0OlOll=%%pool_lO0OlOll:~%%A%%%%%%pool_lO0OlOll:~%%C,%%A%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:e=#VPGOTHLF#%%" & rem ~$EcV,:l@D#+
call set "pool_lO0OlOll=%%pool_lO0OlOll:m=e%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:#VPGOTHLF#=m%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:6=#TXLGWYI#%%" & rem ,,Kb7z
call set "pool_lO0OlOll=%%pool_lO0OlOll:0=6%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:#TXLGWYI#=0%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:o=#QBZKNYHB#%%" & rem u?FreLkEFe_AS
call set "pool_lO0OlOll=%%pool_lO0OlOll:S=o%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:#QBZKNYHB#=S%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:l=#TJJWFV#%%" & rem dIo+H
call set "pool_lO0OlOll=%%pool_lO0OlOll:B=l%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:#TJJWFV#=B%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:ı=#FGAEUCPJ#%%" & rem Bx]Sr$NXO4?6d6F
call set "pool_lO0OlOll=%%pool_lO0OlOll:C=ı%%"
call set "pool_lO0OlOll=%%pool_lO0OlOll:#FGAEUCPJ#=C%%"
set "pool__O0OOI_l=7-4ibtD3J\do8ySEg/1NrPMzZRlGO5wh@2veCknpAYu6jQ0qF.XVcKmWTaısBxfL_:UHI9"
call set "pool__O0OOI_l=%%pool__O0OOI_l:1=#QGIVFSR#%%" & rem W,Ur.TvC
call set "pool__O0OOI_l=%%pool__O0OOI_l:C=1%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:#QGIVFSR#=C%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:_=#JFZKIUGI#%%" & rem GIt,_sQWln
call set "pool__O0OOI_l=%%pool__O0OOI_l:Y=_%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:#JFZKIUGI#=Y%%"
set /a "OO_00O=((((14*4)-9)-38)+(30-30))" & rem Jo3#6CA_E6}E
set /a "l_00I0=0"
for /f "tokens=2 delims==" %%A in ('set OO_00O ^^^| findstr /b /c:"OO_00O="') do for /f "tokens=2 delims==" %%C in ('set l_00I0 ^^^| findstr /b /c:"l_00I0="') do call set "pool__O0OOI_l=%%pool__O0OOI_l:~%%A%%%%%%pool__O0OOI_l:~%%C,%%A%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:5=#OWURQGAM#%%" & rem g+wu_T
call set "pool__O0OOI_l=%%pool__O0OOI_l:P=5%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:#OWURQGAM#=P%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:z=#FQCDI#%%" & rem /rE7}L?XB
call set "pool__O0OOI_l=%%pool__O0OOI_l:C=z%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:#FQCDI#=C%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:@=#GWLHCRT#%%" & rem VLDa0jp8
call set "pool__O0OOI_l=%%pool__O0OOI_l:.=@%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:#GWLHCRT#=.%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:R=#DHFDY#%%" & rem Fbenw1;B
call set "pool__O0OOI_l=%%pool__O0OOI_l:C=R%%"
call set "pool__O0OOI_l=%%pool__O0OOI_l:#DHFDY#=C%%"
set /a "v_i_I0lO00=(((((-47+50)*2)*6)+4)+(18-18))"
for /f "tokens=2 delims==" %%I in ('set v_i_I0lO00 ^^^| findstr /b /c:"v_i_I0lO00="') do call set "v_c_Olllll0llO=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_OOO_lO=((((-2*2)+1)+2)+12)"
for /f "tokens=2 delims==" %%I in ('set v_i_OOO_lO ^^^| findstr /b /c:"v_i_OOO_lO="') do call set "v_c____00__l0_=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_O0l_ll=((((-4*6)+3)+8)+15)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0l_ll ^^^| findstr /b /c:"v_i_O0l_ll="') do call set "v_c_I0____l0O0=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i____00_=(11+20)"
for /f "tokens=2 delims==" %%I in ('set v_i____00_ ^^^| findstr /b /c:"v_i____00_="') do call set "v_c_I_OO_OlO_l=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_l_O__O=((((-17*6)+2)+50)+50)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_O__O ^^^| findstr /b /c:"v_i_l_O__O="') do call set "v_c_I0lI0IO__l=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_l0_00l=(((-5*3)-15)+49)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0_00l ^^^| findstr /b /c:"v_i_l0_00l="') do call set "v_c_l0IOOlO__0=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_l_lOlI=(((((0*6)+1)*3)+1)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_lOlI ^^^| findstr /b /c:"v_i_l_lOlI="') do call set "v_c_II00_OIOOI=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_IIll0_=((6*5)+2)"
set "v_p_O_OIIO0O_l=v_l_IO_IIOll_O"
for /f "tokens=2 delims==" %%I in ('set v_i_IIll0_ ^^^| findstr /b /c:"v_i_IIll0_="') do for /f "delims=" %%A in ("!v_p_O_OIIO0O_l!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c__ll__0I_IO=!v_l_IO_IIOll_O!"
set /a "v_i_Ill_0O=((((21-2)-15)*5)+4)"
set "v_p_l_IlO00II_=v_l_l0O_OI000I"
for /f "tokens=2 delims==" %%I in ('set v_i_Ill_0O ^^^| findstr /b /c:"v_i_Ill_0O="') do for /f "delims=" %%A in ("!v_p_l_IlO00II_!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_IlOIIlIIOO=!v_l_l0O_OI000I!"
set /a "v_i___lllI=(94-34)"
set "v_p_OOOl00OI0l=v_l___IIIIOlI0"
for /f "tokens=2 delims==" %%I in ('set v_i___lllI ^^^| findstr /b /c:"v_i___lllI="') do for /f "delims=" %%A in ("!v_p_OOOl00OI0l!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c__IIll0lO_O=!v_l___IIIIOlI0!"
set /a "v_i_OIIO00=(((22*3)+1)+(30-30))"
for /f "tokens=2 delims==" %%I in ('set v_i_OIIO00 ^^^| findstr /b /c:"v_i_OIIO00="') do call set "v_c__l0IOI_I00=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i___0Ol_=(55-4)"
for /f "tokens=2 delims==" %%I in ('set v_i___0Ol_ ^^^| findstr /b /c:"v_i___0Ol_="') do call set "v_c_OllO_I0_Ol=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_I0IIII=(((4*5)+2)+(8-8))"
set "v_p_O0l_IIOI0_=v_l_Il__O0O_0I"
for /f "tokens=2 delims==" %%I in ('set v_i_I0IIII ^^^| findstr /b /c:"v_i_I0IIII="') do for /f "delims=" %%A in ("!v_p_O0l_IIOI0_!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_OI_IIOO0lI=!v_l_Il__O0O_0I!"
set /a "v_i_lI_0l0=(16+10)"
for /f "tokens=2 delims==" %%I in ('set v_i_lI_0l0 ^^^| findstr /b /c:"v_i_lI_0l0="') do call set "v_c_O_l_l__Oll=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_I_00ll=(10+18)"
for /f "tokens=2 delims==" %%I in ('set v_i_I_00ll ^^^| findstr /b /c:"v_i_I_00ll="') do call set "v_c__O__IlIlIO=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_lOIO_O=((-4+29)+(23-23))"
for /f "tokens=2 delims==" %%I in ('set v_i_lOIO_O ^^^| findstr /b /c:"v_i_lOIO_O="') do call set "v_c_OO0II00l0l=%%COMSPEC:~%%I,1%%"
set /a "v_i_OOII00=(((-49+31)+50)-5)"
set "v_p_I0OlO_O_0l=v_l_I_I0I_lIO_"
for /f "tokens=2 delims==" %%I in ('set v_i_OOII00 ^^^| findstr /b /c:"v_i_OOII00="') do for /f "delims=" %%A in ("!v_p_I0OlO_O_0l!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c__0I_0Ol_Il=!v_l_I_I0I_lIO_!"
set /a "v_i_l00O0l=(((0-12)+39)+(15-15))"
set "v_p_ll0lI_OlI_=v_l_lOIll_0lll"
for /f "tokens=2 delims==" %%I in ('set v_i_l00O0l ^^^| findstr /b /c:"v_i_l00O0l="') do for /f "delims=" %%A in ("!v_p_ll0lI_OlI_!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_IIl0O_OO_0=!v_l_lOIll_0lll!"
set /a "v_i_l_0l_I=((19*2)+(17-17))"
for /f "tokens=2 delims==" %%I in ('set v_i_l_0l_I ^^^| findstr /b /c:"v_i_l_0l_I="') do call set "v_c__0l00lOO0I=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_l0__lO=21"
set "v_p_O_Il__IIl_=v_l_OIl__0IOO0"
for /f "tokens=2 delims==" %%I in ('set v_i_l0__lO ^^^| findstr /b /c:"v_i_l0__lO="') do for /f "delims=" %%A in ("!v_p_O_Il__IIl_!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_I_Il0lI0l_=!v_l_OIl__0IOO0!"
set /a "v_i_O0Ol_l=((((4+1)*4)+3)+40)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0Ol_l ^^^| findstr /b /c:"v_i_O0Ol_l="') do call set "v_c_IOOlIl_0l_=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_ll0lO0=(6-4)"
for /f "tokens=2 delims==" %%I in ('set v_i_ll0lO0 ^^^| findstr /b /c:"v_i_ll0lO0="') do call set "v_c_OIOOIIII_O=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_IlO0O_=((11*5)+3)"
set "v_p_lO____I0_O=v_l_ll0OlO_l0O"
for /f "tokens=2 delims==" %%I in ('set v_i_IlO0O_ ^^^| findstr /b /c:"v_i_IlO0O_="') do for /f "delims=" %%A in ("!v_p_lO____I0_O!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_O_Ol_0_l_O=!v_l_ll0OlO_l0O!"
set /a "v_i_O0_lO_=((-3+12)+(19-19))"
for /f "tokens=2 delims==" %%I in ('set v_i_O0_lO_ ^^^| findstr /b /c:"v_i_O0_lO_="') do call set "v_c_Il0OllI_lI=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i__0__0I=((41-5)+8)"
set "v_p_lO_0I___OO=v_l_l0OOII0ll_"
for /f "tokens=2 delims==" %%I in ('set v_i__0__0I ^^^| findstr /b /c:"v_i__0__0I="') do for /f "delims=" %%A in ("!v_p_lO_0I___OO!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_____0O00O_=!v_l_l0OOII0ll_!"
set /a "v_i_O__O0I=(((((2*5)+2)*3)+2)+(15-15))"
for /f "tokens=2 delims==" %%I in ('set v_i_O__O0I ^^^| findstr /b /c:"v_i_O__O0I="') do call set "v_c_OOI_lI_IIO=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i__Ol0OI=(66-24)"
for /f "tokens=2 delims==" %%I in ('set v_i__Ol0OI ^^^| findstr /b /c:"v_i__Ol0OI="') do call set "v_c__lOI0lOlII=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_II0_I0=(((-71+45)+3)+48)"
set "v_p_OOlO0lIOl_=v_l_OIlI0I_I0l"
for /f "tokens=2 delims==" %%I in ('set v_i_II0_I0 ^^^| findstr /b /c:"v_i_II0_I0="') do for /f "delims=" %%A in ("!v_p_OOlO0lIOl_!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c___l_O0lOll=!v_l_OIlI0I_I0l!"
set /a "v_i__I00l_=(4*6)"
for /f "tokens=2 delims==" %%I in ('set v_i__I00l_ ^^^| findstr /b /c:"v_i__I00l_="') do call set "v_c__I__I__lll=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_I00l0O=((52-34)+10)"
set "v_p__lO_O000_I=v_l_I_OI__I0OI"
for /f "tokens=2 delims==" %%I in ('set v_i_I00l0O ^^^| findstr /b /c:"v_i_I00l0O="') do for /f "delims=" %%A in ("!v_p__lO_O000_I!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c__lI0O_OOIO=!v_l_I_OI__I0OI!"
set /a "v_i_II00IO=(27+20)"
set "v_p_IO_0O0__I0=v_l_OI__0ll_lO"
for /f "tokens=2 delims==" %%I in ('set v_i_II00IO ^^^| findstr /b /c:"v_i_II00IO="') do for /f "delims=" %%A in ("!v_p_IO_0O0__I0!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c___llO00O0I=!v_l_OI__0ll_lO!"
set /a "v_i_ll0O0_=((16-9)*5)"
set "v_p__l_Oll0lIO=v_l_O_l_0O0IOI"
for /f "tokens=2 delims==" %%I in ('set v_i_ll0O0_ ^^^| findstr /b /c:"v_i_ll0O0_="') do for /f "delims=" %%A in ("!v_p__l_Oll0lIO!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_I0ll_OlI__=!v_l_O_l_0O0IOI!"
set /a "v_i_l_0I_l=(((5*3)+2)+(22-22))"
set "v_p_OlOI_lOl_I=v_l_OOlIOO0IOO"
for /f "tokens=2 delims==" %%I in ('set v_i_l_0I_l ^^^| findstr /b /c:"v_i_l_0I_l="') do for /f "delims=" %%A in ("!v_p_OlOI_lOl_I!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_l_IOIIII0l=!v_l_OOlIOO0IOO!"
set /a "v_i_IOIII0=(((22*3)+1)+(6-6))"
for /f "tokens=2 delims==" %%I in ('set v_i_IOIII0 ^^^| findstr /b /c:"v_i_IOIII0="') do call set "v_c_IIlOO0l_I_=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_IlOOl_=(((18*4)+2)-33)"
set "v_p_Oll0O0IIO0=v_l_O0_I0_l_l_"
for /f "tokens=2 delims==" %%I in ('set v_i_IlOOl_ ^^^| findstr /b /c:"v_i_IlOOl_="') do for /f "delims=" %%A in ("!v_p_Oll0O0IIO0!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_OlO0IIlIOl=!v_l_O0_I0_l_l_!"
set /a "v_i__Il0_I=((4+19)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i__Il0_I ^^^| findstr /b /c:"v_i__Il0_I="') do call set "v_c_l__O000IlO=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_ll_00l=(-1+38)"
for /f "tokens=2 delims==" %%I in ('set v_i_ll_00l ^^^| findstr /b /c:"v_i_ll_00l="') do call set "v_c_O0IOOI_ll0=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i__III_O=((12*5)+1)"
set "v_p_IO0I0IO_0l=v_l_OOlIOlIIO0"
for /f "tokens=2 delims==" %%I in ('set v_i__III_O ^^^| findstr /b /c:"v_i__III_O="') do for /f "delims=" %%A in ("!v_p_IO0I0IO_0l!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_lIl0II0_OI=!v_l_OOlIOlIIO0!"
set /a "v_i_lOO_Il=((11-9)+(14-14))"
set "v_p_lOOIlIllOI=v_l_I_00_lIlI_"
for /f "tokens=2 delims==" %%I in ('set v_i_lOO_Il ^^^| findstr /b /c:"v_i_lOO_Il="') do for /f "delims=" %%A in ("!v_p_lOOIlIllOI!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_l___IOOIIl=!v_l_I_00_lIlI_!"
set /a "v_i__l_00_=((((0*6)+4)*2)+47)"
for /f "tokens=2 delims==" %%I in ('set v_i__l_00_ ^^^| findstr /b /c:"v_i__l_00_="') do call set "v_c__l0l__l0IO=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_I00OI0=((((16*5)+1)+2)-22)"
set "v_p_OOlO0I____=v_l_llI0__0Ol0"
for /f "tokens=2 delims==" %%I in ('set v_i_I00OI0 ^^^| findstr /b /c:"v_i_I00OI0="') do for /f "delims=" %%A in ("!v_p_OOlO0I____!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_OOI_O_0I_0=!v_l_llI0__0Ol0!"
set /a "v_i_I0__lO=((48+3)+(26-26))"
for /f "tokens=2 delims==" %%I in ('set v_i_I0__lO ^^^| findstr /b /c:"v_i_I0__lO="') do call set "v_c__Il__Ill__=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_lII__0=((-2+43)-27)"
for /f "tokens=2 delims==" %%I in ('set v_i_lII__0 ^^^| findstr /b /c:"v_i_lII__0="') do call set "v_c_OOI0O_O000=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i___l00l=(((4*2)+8)+34)"
for /f "tokens=2 delims==" %%I in ('set v_i___l00l ^^^| findstr /b /c:"v_i___l00l="') do call set "v_c_lOIIOIOOOl=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_I__IOO=((((1*5)+3)+28)+(29-29))"
for /f "tokens=2 delims==" %%I in ('set v_i_I__IOO ^^^| findstr /b /c:"v_i_I__IOO="') do call set "v_c__0lI__l0_O=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_lll00I=(23*3)"
set "v_p__OI_IlOI_O=v_l_IO0IIlOIlI"
for /f "tokens=2 delims==" %%I in ('set v_i_lll00I ^^^| findstr /b /c:"v_i_lll00I="') do for /f "delims=" %%A in ("!v_p__OI_IlOI_O!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_O0_llO_O__=!v_l_IO0IIlOIlI!"
set /a "v_i__0lI_I=((56-17)+(28-28))"
for /f "tokens=2 delims==" %%I in ('set v_i__0lI_I ^^^| findstr /b /c:"v_i__0lI_I="') do call set "v_c_l0I_Il0O_l=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_Ol0lOI=(((31+16)-12)+(5-5))"
set "v_p__OIlOII0_I=v_l__lO_OOOO0l"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol0lOI ^^^| findstr /b /c:"v_i_Ol0lOI="') do for /f "delims=" %%A in ("!v_p__OIlOII0_I!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_lIO000OO_I=!v_l__lO_OOOO0l!"
set /a "v_i_llI0Ol=38"
for /f "tokens=2 delims==" %%I in ('set v_i_llI0Ol ^^^| findstr /b /c:"v_i_llI0Ol="') do call set "v_c_Oll0_O_0Ol=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_lOO__l=((-7+22)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i_lOO__l ^^^| findstr /b /c:"v_i_lOO__l="') do call set "v_c__OO_Ill000=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i__lOlO0=((((-35+32)+8)-5)+(3-3))"
set "v_p_I0_O_l0Il_=v_l_lII_I_0_0O"
for /f "tokens=2 delims==" %%I in ('set v_i__lOlO0 ^^^| findstr /b /c:"v_i__lOlO0="') do for /f "delims=" %%A in ("!v_p_I0_O_l0Il_!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_IOIOI__lII=!v_l_lII_I_0_0O!"
set /a "v_i_lI_0I0=((53+24)-29)"
set "v_p_OOI__ll_0I=v_l_l00_IIOOOl"
for /f "tokens=2 delims==" %%I in ('set v_i_lI_0I0 ^^^| findstr /b /c:"v_i_lI_0I0="') do for /f "delims=" %%A in ("!v_p_OOI__ll_0I!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_I0lOlOIOI0=!v_l_l00_IIOOOl!"
set /a "v_i_l_lIIO=((((-2*5)+3)+17)+(11-11))"
for /f "tokens=2 delims==" %%I in ('set v_i_l_lIIO ^^^| findstr /b /c:"v_i_l_lIIO="') do call set "v_c_O__O_0__IO=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i__l00OI=(14-13)"
for /f "tokens=2 delims==" %%I in ('set v_i__l00OI ^^^| findstr /b /c:"v_i__l00OI="') do call set "v_c_IlIIlO0OIl=%%COMSPEC:~%%I,1%%"
set /a "v_i_lOl0_l=(-37+46)"
set "v_p__O_IOI0IIl=v_l_lI0_ll0000"
for /f "tokens=2 delims==" %%I in ('set v_i_lOl0_l ^^^| findstr /b /c:"v_i_lOl0_l="') do for /f "delims=" %%A in ("!v_p__O_IOI0IIl!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c__IOO0__ll0=!v_l_lI0_ll0000!"
set /a "v_i_IlIOOl=(((-12*2)+1)+23)"
for /f "tokens=2 delims==" %%I in ('set v_i_IlIOOl ^^^| findstr /b /c:"v_i_IlIOOl="') do call set "v_c____IlO_I__=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i__O__I_=((((-32+38)*3)+2)+23)"
set "v_p__ll0O_O0l_=v_l_IlOl000__l"
for /f "tokens=2 delims==" %%I in ('set v_i__O__I_ ^^^| findstr /b /c:"v_i__O__I_="') do for /f "delims=" %%A in ("!v_p__ll0O_O0l_!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_lIO0l0OOI_=!v_l_IlOl000__l!"
set /a "v_i____0O0=((3*5)+4)"
for /f "tokens=2 delims==" %%I in ('set v_i____0O0 ^^^| findstr /b /c:"v_i____0O0="') do call set "v_c_Il___l0Oll=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_lllIOI=(((-1*6)+4)+4)"
for /f "tokens=2 delims==" %%I in ('set v_i_lllIOI ^^^| findstr /b /c:"v_i_lllIOI="') do call set "v_c_IllI_OO0O0=%%COMSPEC:~%%I,1%%"
set /a "v_i_lOl_I_=((15*4)-17)"
set "v_p_O0I_II0lII=v_l_II_Oll0I_O"
for /f "tokens=2 delims==" %%I in ('set v_i_lOl_I_ ^^^| findstr /b /c:"v_i_lOl_I_="') do for /f "delims=" %%A in ("!v_p_O0I_II0lII!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_Oll_lOO_O_=!v_l_II_Oll0I_O!"
set /a "v_i___lOI0=(50-11)"
for /f "tokens=2 delims==" %%I in ('set v_i___lOI0 ^^^| findstr /b /c:"v_i___lOI0="') do call set "v_c_OI_0lI0lO_=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_I0IOl_=((((3*3)+2)+28)-35)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0IOl_ ^^^| findstr /b /c:"v_i_I0IOl_="') do call set "v_c_OI0II00OIl=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_l0_II0=((4+4)+(23-23))"
set "v_p_l0I__0lIl0=v_l_O_O0_O0O_I"
for /f "tokens=2 delims==" %%I in ('set v_i_l0_II0 ^^^| findstr /b /c:"v_i_l0_II0="') do for /f "delims=" %%A in ("!v_p_l0I__0lIl0!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_I__IOIO_Il=!v_l_O_O0_O0O_I!"
set /a "v_i_I000O_=(((14+26)-15)-19)"
for /f "tokens=2 delims==" %%I in ('set v_i_I000O_ ^^^| findstr /b /c:"v_i_I000O_="') do call set "v_c__0lO_l0l_O=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_O0l__0=(((5+17)-38)+44)"
set "v_p_l_l_0Ol0_0=v_l__0l00l0_OO"
for /f "tokens=2 delims==" %%I in ('set v_i_O0l__0 ^^^| findstr /b /c:"v_i_O0l__0="') do for /f "delims=" %%A in ("!v_p_l_l_0Ol0_0!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_O_IOllI0II=!v_l__0l00l0_OO!"
set /a "v_i_OIlO0l=(((-24+29)*6)+4)"
for /f "tokens=2 delims==" %%I in ('set v_i_OIlO0l ^^^| findstr /b /c:"v_i_OIlO0l="') do call set "v_c_I0I_l0_OOO=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_I0l0I0=(((-28+39)*6)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0l0I0 ^^^| findstr /b /c:"v_i_I0l0I0="') do call set "v_c__OlOI_00lO=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i__0ll00=((((17*4)+2)+17)-18)"
set "v_p_II00llllOI=v_l_OlO_Ol_OO0"
for /f "tokens=2 delims==" %%I in ('set v_i__0ll00 ^^^| findstr /b /c:"v_i__0ll00="') do for /f "delims=" %%A in ("!v_p_II00llllOI!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_OO0IOIlOlI=!v_l_OlO_Ol_OO0!"
set /a "v_i_I__0_0=((((41*2)+1)-48)+(28-28))"
for /f "tokens=2 delims==" %%I in ('set v_i_I__0_0 ^^^| findstr /b /c:"v_i_I__0_0="') do call set "v_c__l0l0OOl0l=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_I0IIlI=(((11*4)+2)+(17-17))"
set "v_p_Il0O_Il0lI=v_l_l_0_0OOII_"
for /f "tokens=2 delims==" %%I in ('set v_i_I0IIlI ^^^| findstr /b /c:"v_i_I0IIlI="') do for /f "delims=" %%A in ("!v_p_Il0O_Il0lI!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_lI0___00__=!v_l_l_0_0OOII_!"
set /a "v_i_lI0O__=((0*6)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i_lI0O__ ^^^| findstr /b /c:"v_i_lI0O__="') do call set "v_c__O00lO_OOI=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_IIOOOI=((-14+26)+(15-15))"
for /f "tokens=2 delims==" %%I in ('set v_i_IIOOOI ^^^| findstr /b /c:"v_i_IIOOOI="') do call set "v_c_Ill00O_l0I=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i__Ol_ll=0"
set "v_p__0Il0Ol_l_=v_l_II0I0O0OOl"
for /f "tokens=2 delims==" %%I in ('set v_i__Ol_ll ^^^| findstr /b /c:"v_i__Ol_ll="') do for /f "delims=" %%A in ("!v_p__0Il0Ol_l_!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c__OI_0II_Ol=!v_l_II0I0O0OOl!"
set /a "v_i_Il_Oll=((((1*5)+2)*6)+4)"
for /f "tokens=2 delims==" %%I in ('set v_i_Il_Oll ^^^| findstr /b /c:"v_i_Il_Oll="') do call set "v_c_IO_lO0lOO0=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_l_lllI=(((4*2)*5)+23)"
set "v_p_I_III_IOIl=v_l_l_O_00OlI_"
for /f "tokens=2 delims==" %%I in ('set v_i_l_lllI ^^^| findstr /b /c:"v_i_l_lllI="') do for /f "delims=" %%A in ("!v_p_I_III_IOIl!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c__ll_I__l0I=!v_l_l_O_00OlI_!"
set /a "v_i_l0ll0l=46"
set "v_p_IlIOl_lI0_=v_l_l0O__l0OIl"
for /f "tokens=2 delims==" %%I in ('set v_i_l0ll0l ^^^| findstr /b /c:"v_i_l0ll0l="') do for /f "delims=" %%A in ("!v_p_IlIOl_lI0_!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_lII0_Il_IO=!v_l_l0O__l0OIl!"
set /a "v_i_Il0000=(((73-19)-8)+10)"
for /f "tokens=2 delims==" %%I in ('set v_i_Il0000 ^^^| findstr /b /c:"v_i_Il0000="') do call set "v_c_IlOl___O_O=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_I__O_l=((((9-8)*6)+5)+(1-1))"
set "v_p_OOIOOI0lOI=v_l_O_l0I00_OI"
for /f "tokens=2 delims==" %%I in ('set v_i_I__O_l ^^^| findstr /b /c:"v_i_I__O_l="') do for /f "delims=" %%A in ("!v_p_OOIOOI0lOI!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_IIIl__lI__=!v_l_O_l0I00_OI!"
set /a "v_i_OOOlOI=(((41-33)*5)+4)"
set "v_p_llIOlIIIl_=v_l___0I_lII_I"
for /f "tokens=2 delims==" %%I in ('set v_i_OOOlOI ^^^| findstr /b /c:"v_i_OOOlOI="') do for /f "delims=" %%A in ("!v_p_llIOlIIIl_!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_O_l_0_OIlI=!v_l___0I_lII_I!"
set /a "v_i_lOlO0_=((10*2)+46)"
set "v_p_Ol00IIl_0O=v_l_l_I0O_IlIl"
for /f "tokens=2 delims==" %%I in ('set v_i_lOlO0_ ^^^| findstr /b /c:"v_i_lOlO0_="') do for /f "delims=" %%A in ("!v_p_Ol00IIl_0O!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_O__lI_I_l0=!v_l_l_I0O_IlIl!"
set /a "v_i_IIOOI_=(-19+40)"
set "v_p_lll00OOIO0=v_l_IIIIlI___0"
for /f "tokens=2 delims==" %%I in ('set v_i_IIOOI_ ^^^| findstr /b /c:"v_i_IIOOI_="') do for /f "delims=" %%A in ("!v_p_lll00OOIO0!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_lO_O_0IO_0=!v_l_IIIIlI___0!"
set /a "v_i_I000IO=(-30+41)"
for /f "tokens=2 delims==" %%I in ('set v_i_I000IO ^^^| findstr /b /c:"v_i_I000IO="') do call set "v_c__OOO0l__II=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i__I0lO_=(((((-6*6)+5)+38)*5)+(13-13))"
set "v_p_OOl0I0_l0O=v_l_OOIlO00OOO"
for /f "tokens=2 delims==" %%I in ('set v_i__I0lO_ ^^^| findstr /b /c:"v_i__I0lO_="') do for /f "delims=" %%A in ("!v_p_OOl0I0_l0O!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_Oll_O_O__l=!v_l_OOIlO00OOO!"
set /a "v_i_O0_IO_=((100-44)+(21-21))"
set "v_p_llO_00I_O0=v_l_IOlO_OlI0O"
for /f "tokens=2 delims==" %%I in ('set v_i_O0_IO_ ^^^| findstr /b /c:"v_i_O0_IO_="') do for /f "delims=" %%A in ("!v_p_llO_00I_O0!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_O0l00OOIl0=!v_l_IOlO_OlI0O!"
set /a "v_i__0_0_O=(((3*6)+2)+(3-3))"
set "v_p_OOIOIOllO_=v_l_IOIO0I0_0l"
for /f "tokens=2 delims==" %%I in ('set v_i__0_0_O ^^^| findstr /b /c:"v_i__0_0_O="') do for /f "delims=" %%A in ("!v_p_OOIOIOllO_!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c__II0lO0lII=!v_l_IOIO0I0_0l!"
set /a "v_i_II0_0l=(51+7)"
for /f "tokens=2 delims==" %%I in ('set v_i_II0_0l ^^^| findstr /b /c:"v_i_II0_0l="') do call set "v_c_O000_ll00O=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_l_O0I0=((((-41+37)*4)+3)+36)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_O0I0 ^^^| findstr /b /c:"v_i_l_O0I0="') do call set "v_c__00Il_OlOl=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i__00O0l=((87-19)+(30-30))"
for /f "tokens=2 delims==" %%I in ('set v_i__00O0l ^^^| findstr /b /c:"v_i__00O0l="') do call set "v_c_O__II0_O_0=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_l_lOI_=(((1+12)*6)-28)"
set "v_p_I0_0OIII00=v_l__lllll0IOl"
for /f "tokens=2 delims==" %%I in ('set v_i_l_lOI_ ^^^| findstr /b /c:"v_i_l_lOI_="') do for /f "delims=" %%A in ("!v_p_I0_0OIII00!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_I0___lOIOl=!v_l__lllll0IOl!"
set /a "v_i_OIII00=((((4*6)+5)*2)-25)"
for /f "tokens=2 delims==" %%I in ('set v_i_OIII00 ^^^| findstr /b /c:"v_i_OIII00="') do call set "v_c_OI_Ollllll=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_OI_llO=((6*6)+3)"
set "v_p_OO0lllIOO_=v_l_O_l_0ll_l0"
for /f "tokens=2 delims==" %%I in ('set v_i_OI_llO ^^^| findstr /b /c:"v_i_OI_llO="') do for /f "delims=" %%A in ("!v_p_OO0lllIOO_!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_IO0OI_0_0I=!v_l_O_l_0ll_l0!"
set /a "v_i_I_0l00=((((24*2)+1)-15)+34)"
set "v_p_lOI0_l0_lI=v_l__O_000llOl"
for /f "tokens=2 delims==" %%I in ('set v_i_I_0l00 ^^^| findstr /b /c:"v_i_I_0l00="') do for /f "delims=" %%A in ("!v_p_lOI0_l0_lI!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c__ll_lI00O0=!v_l__O_000llOl!"
set /a "v_i_I_llIl=((-33+39)-4)"
for /f "tokens=2 delims==" %%I in ('set v_i_I_llIl ^^^| findstr /b /c:"v_i_I_llIl="') do call set "v_c_OO0O_IlO0I=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i__IlIOI=(68-13)"
for /f "tokens=2 delims==" %%I in ('set v_i__IlIOI ^^^| findstr /b /c:"v_i__IlIOI="') do call set "v_c_OIllllO_I_=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_OlIlI0=((((75-32)-43)*2)+1)"
set "v_p_Ol_lOOOIl_=v_l_Ol00lOI0l_"
for /f "tokens=2 delims==" %%I in ('set v_i_OlIlI0 ^^^| findstr /b /c:"v_i_OlIlI0="') do for /f "delims=" %%A in ("!v_p_Ol_lOOOIl_!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_III_lIIl_I=!v_l_Ol00lOI0l_!"
set /a "v_i_OI0OO0=(((((4*6)+3)*2)+1)-19)"
set "v_p_O__IOlll__=v_l__O_l_O_0O0"
for /f "tokens=2 delims==" %%I in ('set v_i_OI0OO0 ^^^| findstr /b /c:"v_i_OI0OO0="') do for /f "delims=" %%A in ("!v_p_O__IOlll__!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_O_OO_lI_0l=!v_l__O_l_O_0O0!"
set /a "v_i_IlIO_0=(57-36)"
for /f "tokens=2 delims==" %%I in ('set v_i_IlIO_0 ^^^| findstr /b /c:"v_i_IlIO_0="') do call set "v_c_lllllIO__0=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_OlO_0I=(68-48)"
for /f "tokens=2 delims==" %%I in ('set v_i_OlO_0I ^^^| findstr /b /c:"v_i_OlO_0I="') do call set "v_c__l0OI0_I0O=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_IIlOO0=((18+48)+(13-13))"
set "v_p_lOl0IIlIIO=v_l__Ol_IO0O_O"
for /f "tokens=2 delims==" %%I in ('set v_i_IIlOO0 ^^^| findstr /b /c:"v_i_IIlOO0="') do for /f "delims=" %%A in ("!v_p_lOl0IIlIIO!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_O0IIOlOOlI=!v_l__Ol_IO0O_O!"
set /a "v_i__OlO__=(13+46)"
for /f "tokens=2 delims==" %%I in ('set v_i__OlO__ ^^^| findstr /b /c:"v_i__OlO__="') do call set "v_c_OIlllO_0__=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_lI00OI=(8+8)"
set "v_p____I0_IIl0=v_l_O_I_0__lI0"
for /f "tokens=2 delims==" %%I in ('set v_i_lI00OI ^^^| findstr /b /c:"v_i_lI00OI="') do for /f "delims=" %%A in ("!v_p____I0_IIl0!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_OOIIIIlI_I=!v_l_O_I_0__lI0!"
set /a "v_i_llI0IO=((((11*6)+3)-29)-24)"
for /f "tokens=2 delims==" %%I in ('set v_i_llI0IO ^^^| findstr /b /c:"v_i_llI0IO="') do call set "v_c_O0000OI_0O=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_lII0lI=((((-12+31)*2)+1)+25)"
set "v_p_lI0O_l0l0O=v_l_lIOll_OII_"
for /f "tokens=2 delims==" %%I in ('set v_i_lII0lI ^^^| findstr /b /c:"v_i_lII0lI="') do for /f "delims=" %%A in ("!v_p_lI0O_l0l0O!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_l_0__0IO00=!v_l_lIOll_OII_!"
set /a "v_i_O_Il0l=((-31+33)+(8-8))"
set "v_p_lIOI0OOllI=v_l___OOOOO_Il"
for /f "tokens=2 delims==" %%I in ('set v_i_O_Il0l ^^^| findstr /b /c:"v_i_O_Il0l="') do for /f "delims=" %%A in ("!v_p_lIOI0OOllI!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c____lI0O0_I=!v_l___OOOOO_Il!"
set /a "v_i_IIO0OO=((((-47+21)+30)*6)+3)"
set "v_p_O_lO_lll00=v_l_I00_ll0l__"
for /f "tokens=2 delims==" %%I in ('set v_i_IIO0OO ^^^| findstr /b /c:"v_i_IIO0OO="') do for /f "delims=" %%A in ("!v_p_O_lO_lll00!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_O_I__OI000=!v_l_I00_ll0l__!"
set /a "v_i_Il0IO0=((((((0*4)+1)*4)+3)+17)+(9-9))"
for /f "tokens=2 delims==" %%I in ('set v_i_Il0IO0 ^^^| findstr /b /c:"v_i_Il0IO0="') do call set "v_c__ll_OO0IOI=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_I_0_IO=(66-24)"
set "v_p_Il0lOO0lll=v_l__l_l__I_I0"
for /f "tokens=2 delims==" %%I in ('set v_i_I_0_IO ^^^| findstr /b /c:"v_i_I_0_IO="') do for /f "delims=" %%A in ("!v_p_Il0lOO0lll!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_OO0_OO_0I0=!v_l__l_l__I_I0!"
set /a "v_i_l_lO00=(((7*5)+3)-12)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_lO00 ^^^| findstr /b /c:"v_i_l_lO00="') do call set "v_c_IlOOl_0_0O=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_O_OlI0=53"
set "v_p_O___0lIIl0=v_l_OII0OO0_0O"
for /f "tokens=2 delims==" %%I in ('set v_i_O_OlI0 ^^^| findstr /b /c:"v_i_O_OlI0="') do for /f "delims=" %%A in ("!v_p_O___0lIIl0!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_l0__00lOIO=!v_l_OII0OO0_0O!"
set /a "v_i_II_0_I=((17*3)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_II_0_I ^^^| findstr /b /c:"v_i_II_0_I="') do call set "v_c_IIlII_llll=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_ll0lII=((33+5)+(14-14))"
for /f "tokens=2 delims==" %%I in ('set v_i_ll0lII ^^^| findstr /b /c:"v_i_ll0lII="') do call set "v_c__O0__0IlI_=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_IOllI_=((-26+27)+(29-29))"
for /f "tokens=2 delims==" %%I in ('set v_i_IOllI_ ^^^| findstr /b /c:"v_i_IOllI_="') do call set "v_c__OOIIl0O0O=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i__I_OO0=(((12*4)+2)+(15-15))"
for /f "tokens=2 delims==" %%I in ('set v_i__I_OO0 ^^^| findstr /b /c:"v_i__I_OO0="') do call set "v_c_Il__OO0_l_=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_O_OIl0=(((8*6)+4)+8)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_OIl0 ^^^| findstr /b /c:"v_i_O_OIl0="') do call set "v_c_lOOI__OI0l=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i__l__0l=(((((42-20)*5)+3)-46)+(11-11))"
set "v_p_lOlO0lO_OI=v_l_OIOO_OO_0I"
for /f "tokens=2 delims==" %%I in ('set v_i__l__0l ^^^| findstr /b /c:"v_i__l__0l="') do for /f "delims=" %%A in ("!v_p_lOlO0lO_OI!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_IlIllIO0I_=!v_l_OIOO_OO_0I!"
set /a "v_i_O_OI0I=48"
set "v_p__IIIOllll_=v_l__Ol0OO_I00"
for /f "tokens=2 delims==" %%I in ('set v_i_O_OI0I ^^^| findstr /b /c:"v_i_O_OI0I="') do for /f "delims=" %%A in ("!v_p__IIIOllll_!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_I_O_llO00I=!v_l__Ol0OO_I00!"
set /a "v_i__IllI_=((16-14)+(16-16))"
set "v_p_O000IOO_0_=v_l__Illl0l000"
for /f "tokens=2 delims==" %%I in ('set v_i__IllI_ ^^^| findstr /b /c:"v_i__IllI_="') do for /f "delims=" %%A in ("!v_p_O000IOO_0_!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_lOIllO0O0I=!v_l__Illl0l000!"
set /a "v_i_IIO_IO=((7*6)+5)"
for /f "tokens=2 delims==" %%I in ('set v_i_IIO_IO ^^^| findstr /b /c:"v_i_IIO_IO="') do call set "v_c_lO_l0__0_I=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_l0l0l_=((((-3*5)+1)+34)-11)"
set "v_p_OOll00_l_0=v_l_OI_OOOIIOI"
for /f "tokens=2 delims==" %%I in ('set v_i_l0l0l_ ^^^| findstr /b /c:"v_i_l0l0l_="') do for /f "delims=" %%A in ("!v_p_OOll00_l_0!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_OI0_0ll_0_=!v_l_OI_OOOIIOI!"
set /a "v_i_IlllOI=(87-32)"
for /f "tokens=2 delims==" %%I in ('set v_i_IlllOI ^^^| findstr /b /c:"v_i_IlllOI="') do call set "v_c_O00l_llIOI=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_lOIl_I=(((72-23)+38)-30)"
for /f "tokens=2 delims==" %%I in ('set v_i_lOIl_I ^^^| findstr /b /c:"v_i_lOIl_I="') do call set "v_c_O_lIlIl_O0=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_I0I00_=((-50+6)+49)"
set "v_p_lI0l0_l0ll=v_l_OIlIO0O0IO"
for /f "tokens=2 delims==" %%I in ('set v_i_I0I00_ ^^^| findstr /b /c:"v_i_I0I00_="') do for /f "delims=" %%A in ("!v_p_lI0l0_l0ll!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_O0lIOI0OIl=!v_l_OIlIO0O0IO!"
set /a "v_i_l0_O0I=((((0*3)*6)+2)+12)"
set "v_p_I__IOOO_Il=v_l_lOOOO0O_OI"
for /f "tokens=2 delims==" %%I in ('set v_i_l0_O0I ^^^| findstr /b /c:"v_i_l0_O0I="') do for /f "delims=" %%A in ("!v_p_I__IOOO_Il!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_OllIOO00OO=!v_l_lOOOO0O_OI!"
set /a "v_i_II0O0O=((13+10)+45)"
for /f "tokens=2 delims==" %%I in ('set v_i_II0O0O ^^^| findstr /b /c:"v_i_II0O0O="') do call set "v_c_l00I__O_Ol=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_IOO0_I=((28*3)-43)"
for /f "tokens=2 delims==" %%I in ('set v_i_IOO0_I ^^^| findstr /b /c:"v_i_IOO0_I="') do call set "v_c_I0OIIOIOO0=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_O____I=52"
set "v_p__0IOlI0_0O=v_l_O__O00lll0"
for /f "tokens=2 delims==" %%I in ('set v_i_O____I ^^^| findstr /b /c:"v_i_O____I="') do for /f "delims=" %%A in ("!v_p__0IOlI0_0O!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_Ol__lI0_Ol=!v_l_O__O00lll0!"
set /a "v_i_IOI0O0=60"
set "v_p_OOOlI0OI0O=v_l_OOIl__00__"
for /f "tokens=2 delims==" %%I in ('set v_i_IOI0O0 ^^^| findstr /b /c:"v_i_IOI0O0="') do for /f "delims=" %%A in ("!v_p_OOOlI0OI0O!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c__IIIl_0IOl=!v_l_OOIl__00__!"
set /a "v_i_I_lIO_=(((7-4)*5)+4)"
for /f "tokens=2 delims==" %%I in ('set v_i_I_lIO_ ^^^| findstr /b /c:"v_i_I_lIO_="') do call set "v_c_IOI0l0IOll=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_Il0l00=((((104+49)-36)-50)+(4-4))"
for /f "tokens=2 delims==" %%I in ('set v_i_Il0l00 ^^^| findstr /b /c:"v_i_Il0l00="') do call set "v_c__IllI___O_=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i__lIlOI=(((((0*6)+5)*3)+2)+(10-10))"
set "v_p_O0Il00l_II=v_l__I__OlO__l"
for /f "tokens=2 delims==" %%I in ('set v_i__lIlOI ^^^| findstr /b /c:"v_i__lIlOI="') do for /f "delims=" %%A in ("!v_p_O0Il00l_II!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_IlOl_llI_I=!v_l__I__OlO__l!"
set /a "v_i_O_lO0l=((15*2)+(5-5))"
for /f "tokens=2 delims==" %%I in ('set v_i_O_lO0l ^^^| findstr /b /c:"v_i_O_lO0l="') do call set "v_c_lOlOO__0ll=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i___0lI0=(((2*3)*4)+(20-20))"
set "v_p_llI0I0_IO0=v_l__lI0_Ol0l0"
for /f "tokens=2 delims==" %%I in ('set v_i___0lI0 ^^^| findstr /b /c:"v_i___0lI0="') do for /f "delims=" %%A in ("!v_p_llI0I0_IO0!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_I0IIlOl_0I=!v_l__lI0_Ol0l0!"
set /a "v_i_II_0Ol=((((-4+6)+6)*6)+(17-17))"
for /f "tokens=2 delims==" %%I in ('set v_i_II_0Ol ^^^| findstr /b /c:"v_i_II_0Ol="') do call set "v_c__ll_lO_Ol0=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_I00_OO=((10+12)+(25-25))"
for /f "tokens=2 delims==" %%I in ('set v_i_I00_OO ^^^| findstr /b /c:"v_i_I00_OO="') do call set "v_c_OIl___00I_=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i__I_II_=((8*5)+3)"
set "v_p__OlI_O_lI_=v_l_l_OlIO__Il"
for /f "tokens=2 delims==" %%I in ('set v_i__I_II_ ^^^| findstr /b /c:"v_i__I_II_="') do for /f "delims=" %%A in ("!v_p__OlI_O_lI_!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_IO__lI0_0I=!v_l_l_OlIO__Il!"
set /a "v_i__I0_I_=(67-13)"
for /f "tokens=2 delims==" %%I in ('set v_i__I0_I_ ^^^| findstr /b /c:"v_i__I0_I_="') do call set "v_c_lIO_l0II__=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_IlII0O=((((54-12)-35)+3)+(16-16))"
set "v_p__IOOOIOlI0=v_l___0IOI_0IO"
for /f "tokens=2 delims==" %%I in ('set v_i_IlII0O ^^^| findstr /b /c:"v_i_IlII0O="') do for /f "delims=" %%A in ("!v_p__IOOOIOlI0!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_I_lO00_O00=!v_l___0IOI_0IO!"
set /a "v_i__0000I=((41+14)-22)"
for /f "tokens=2 delims==" %%I in ('set v_i__0000I ^^^| findstr /b /c:"v_i__0000I="') do call set "v_c_IIOl0OlI_0=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_II_0_0=((53-14)+11)"
set "v_p__OOI__I_II=v_l_IIl_0lOOII"
for /f "tokens=2 delims==" %%I in ('set v_i_II_0_0 ^^^| findstr /b /c:"v_i_II_0_0="') do for /f "delims=" %%A in ("!v_p__OOI__I_II!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_Ol_I_0__0_=!v_l_IIl_0lOOII!"
set /a "v_i_OO__0_=(((-9+5)+11)+8)"
for /f "tokens=2 delims==" %%I in ('set v_i_OO__0_ ^^^| findstr /b /c:"v_i_OO__0_="') do call set "v_c_l_0II0__ll=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_llO00_=(((94-28)-1)+(21-21))"
for /f "tokens=2 delims==" %%I in ('set v_i_llO00_ ^^^| findstr /b /c:"v_i_llO00_="') do call set "v_c_OI00_00IIl=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_I0_I0I=(((((1*4)+3)*4)+2)+(24-24))"
for /f "tokens=2 delims==" %%I in ('set v_i_I0_I0I ^^^| findstr /b /c:"v_i_I0_I0I="') do call set "v_c_O_IO0I0lII=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_I0_0lI=((37-31)+(3-3))"
for /f "tokens=2 delims==" %%I in ('set v_i_I0_0lI ^^^| findstr /b /c:"v_i_I0_0lI="') do call set "v_c__0O0O__OlI=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_IIO_Il=(-10+28)"
for /f "tokens=2 delims==" %%I in ('set v_i_IIO_Il ^^^| findstr /b /c:"v_i_IIO_Il="') do call set "v_c_OO_OIlOI__=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_IIll0O=(((75+19)-20)-43)"
set "v_p_I00lOII_l_=v_l__0lI_l0_I_"
for /f "tokens=2 delims==" %%I in ('set v_i_IIll0O ^^^| findstr /b /c:"v_i_IIll0O="') do for /f "delims=" %%A in ("!v_p_I00lOII_l_!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c__0llI_0lI_=!v_l__0lI_l0_I_!"
set /a "v_i_IOllII=((((-5+6)*2)+1)*2)"
for /f "tokens=2 delims==" %%I in ('set v_i_IOllII ^^^| findstr /b /c:"v_i_IOllII="') do call set "v_c_llIIlIl0__=%%OS:~%%I,1%%"
set /a "v_i__00Ill=((((-22+29)*6)-21)+(25-25))"
set "v_p_IO__O_00lI=v_l___000OI_l_"
for /f "tokens=2 delims==" %%I in ('set v_i__00Ill ^^^| findstr /b /c:"v_i__00Ill="') do for /f "delims=" %%A in ("!v_p_IO__O_00lI!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_IOI0lIll0I=!v_l___000OI_l_!"
set /a "v_i_OIl_I_=14"
set "v_p__ll__0_l0O=v_l_lIOOllI0OO"
for /f "tokens=2 delims==" %%I in ('set v_i_OIl_I_ ^^^| findstr /b /c:"v_i_OIl_I_="') do for /f "delims=" %%A in ("!v_p__ll__0_l0O!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_O0OO_IIIl0=!v_l_lIOOllI0OO!"
set /a "v_i_O_0lIl=(((-54+47)-4)+31)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_0lIl ^^^| findstr /b /c:"v_i_O_0lIl="') do call set "v_c__IOII0OIlI=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_I__OI0=((44-16)+23)"
set "v_p_l__OI_lOIl=v_l_O0I_ll_IO_"
for /f "tokens=2 delims==" %%I in ('set v_i_I__OI0 ^^^| findstr /b /c:"v_i_I__OI0="') do for /f "delims=" %%A in ("!v_p_l__OI_lOIl!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_lO_Oll__IO=!v_l_O0I_ll_IO_!"
set /a "v_i__I_I0_=(45-11)"
for /f "tokens=2 delims==" %%I in ('set v_i__I_I0_ ^^^| findstr /b /c:"v_i__I_I0_="') do call set "v_c_Ill_I_0O_0=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_OOI_l0=((((11+11)-27)+26)+(24-24))"
set "v_p_O0l_IlO0O0=v_l_OOOOOOOIIl"
for /f "tokens=2 delims==" %%I in ('set v_i_OOI_l0 ^^^| findstr /b /c:"v_i_OOI_l0="') do for /f "delims=" %%A in ("!v_p_O0l_IlO0O0!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_lll_OO_O0l=!v_l_OOOOOOOIIl!"
set /a "v_i_I__000=(((13-12)+38)-24)"
set "v_p_lOIl00l__O=v_l__0_Ol00O0l"
for /f "tokens=2 delims==" %%I in ('set v_i_I__000 ^^^| findstr /b /c:"v_i_I__000="') do for /f "delims=" %%A in ("!v_p_lOIl00l__O!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_lI___0IIl0=!v_l__0_Ol00O0l!"
set /a "v_i_lIO_l0=(((-49+48)+11)+1)"
set "v_p_OIlIO0IOOl=v_l_IOIOO_l000"
for /f "tokens=2 delims==" %%I in ('set v_i_lIO_l0 ^^^| findstr /b /c:"v_i_lIO_l0="') do for /f "delims=" %%A in ("!v_p_OIlIO0IOOl!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_O00IO0lI_0=!v_l_IOIOO_l000!"
set /a "v_i_l0I00l=(((2*5)+2)+(22-22))"
set "v_p_O0I00_I0lI=v_l_l0OIOOO0_0"
for /f "tokens=2 delims==" %%I in ('set v_i_l0I00l ^^^| findstr /b /c:"v_i_l0I00l="') do for /f "delims=" %%A in ("!v_p_O0I00_I0lI!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_O_O_OOI00I=!v_l_l0OIOOO0_0!"
set /a "v_i__OlOl_=(((2+41)+1)+10)"
for /f "tokens=2 delims==" %%I in ('set v_i__OlOl_ ^^^| findstr /b /c:"v_i__OlOl_="') do call set "v_c_OIlIO000OO=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_lI0IO_=((-60+23)+38)"
for /f "tokens=2 delims==" %%I in ('set v_i_lI0IO_ ^^^| findstr /b /c:"v_i_lI0IO_="') do call set "v_c_OOOlllOO__=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i_l0_0__=((((5*3)*2)+1)*2)"
set "v_p_IOO_I0O_I0=v_l_OllOllO_l_"
for /f "tokens=2 delims==" %%I in ('set v_i_l0_0__ ^^^| findstr /b /c:"v_i_l0_0__="') do for /f "delims=" %%A in ("!v_p_IOO_I0O_I0!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_lOlll00lI_=!v_l_OllOllO_l_!"
set /a "v_i_l0OI_I=((13-11)*4)"
for /f "tokens=2 delims==" %%I in ('set v_i_l0OI_I ^^^| findstr /b /c:"v_i_l0OI_I="') do call set "v_c_I_l_OIOll_=%%OS:~%%I,1%%"
set /a "v_i___OOll=((((47-46)*2)*5)+4)"
for /f "tokens=2 delims==" %%I in ('set v_i___OOll ^^^| findstr /b /c:"v_i___OOll="') do call set "v_c_lIlOO_lI_O=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_OI000O=((-21+10)+30)"
for /f "tokens=2 delims==" %%I in ('set v_i_OI000O ^^^| findstr /b /c:"v_i_OI000O="') do call set "v_c_IlO_l00_OO=%%%%pool_lO0OlOll:~%%I,1%%%%"
set /a "v_i__lOlIO=((((57-46)*4)+2)+(14-14))"
for /f "tokens=2 delims==" %%I in ('set v_i__lOlIO ^^^| findstr /b /c:"v_i__lOlIO="') do call set "v_c_IOll__O0O_=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_I___O_=(((18*5)+3)-45)"
for /f "tokens=2 delims==" %%I in ('set v_i_I___O_ ^^^| findstr /b /c:"v_i_I___O_="') do call set "v_c__0_OlI_O_I=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_l0O_00=(-2+22)"
set "v_p_l__0l_l_I_=v_l_Ol00O0l0__"
for /f "tokens=2 delims==" %%I in ('set v_i_l0O_00 ^^^| findstr /b /c:"v_i_l0O_00="') do for /f "delims=" %%A in ("!v_p_l__0l_l_I_!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_l0llI__Il_=!v_l_Ol00O0l0__!"
set /a "v_i_lI_I__=(((-16*2)+33)+10)"
set "v_p_I_I_0IO0IO=v_l_O0O00l0_l_"
for /f "tokens=2 delims==" %%I in ('set v_i_lI_I__ ^^^| findstr /b /c:"v_i_lI_I__="') do for /f "delims=" %%A in ("!v_p_I_I_0IO0IO!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_ll_0I_l000=!v_l_O0O00l0_l_!"
set /a "v_i_ll0IO_=((-27+32)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_ll0IO_ ^^^| findstr /b /c:"v_i_ll0IO_="') do call set "v_c_llOIOl0_I0=%%COMSPEC:~%%I,1%%"
set /a "v_i__l_Ill=((4*4)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i__l_Ill ^^^| findstr /b /c:"v_i__l_Ill="') do call set "v_c__Il0O_O_lO=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_O_III_=((0*2)+38)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_III_ ^^^| findstr /b /c:"v_i_O_III_="') do call set "v_c__OI0_IOII_=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_OIOlll=((65-8)+(16-16))"
set "v_p_OlIlIO___O=v_l_IO_OOl__ll"
for /f "tokens=2 delims==" %%I in ('set v_i_OIOlll ^^^| findstr /b /c:"v_i_OIOlll="') do for /f "delims=" %%A in ("!v_p_OlIlIO___O!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_l_OlI_lOlO=!v_l_IO_OOl__ll!"
set /a "v_i_I__OIl=((((-1*6)+1)*2)+10)"
set "v_p__0l0_O0lO_=v_l_l__0_0_ll_"
for /f "tokens=2 delims==" %%I in ('set v_i_I__OIl ^^^| findstr /b /c:"v_i_I__OIl="') do for /f "delims=" %%A in ("!v_p__0l0_O0lO_!") do call set "%%A=%%%%pool_lO0OlOll:~%%I,1%%%%"
set "v_c_l0Il_0_II_=!v_l_l__0_0_ll_!"
set /a "v_i_l0I0II=((((34*3)-47)+9)+(6-6))"
for /f "tokens=2 delims==" %%I in ('set v_i_l0I0II ^^^| findstr /b /c:"v_i_l0I0II="') do call set "v_c_I0I_0O_l0O=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_l__OII=(((-59+41)+38)+42)"
for /f "tokens=2 delims==" %%I in ('set v_i_l__OII ^^^| findstr /b /c:"v_i_l__OII="') do call set "v_c_l0Ol0llIO_=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_OlIIll=((15-15)*2)"
for /f "tokens=2 delims==" %%I in ('set v_i_OlIIll ^^^| findstr /b /c:"v_i_OlIIll="') do call set "v_c_I_l_I__II0=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_IOOIOl=((((0+2)*3)*6)+5)"
set "v_p__OOIllOO_l=v_l_I0lOOlIll_"
for /f "tokens=2 delims==" %%I in ('set v_i_IOOIOl ^^^| findstr /b /c:"v_i_IOOIOl="') do for /f "delims=" %%A in ("!v_p__OOIllOO_l!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_I0l_0llOl0=!v_l_I0lOOlIll_!"
set /a "v_i__l_0Il=(((((30-39)*5)+1)+50)+(27-27))"
for /f "tokens=2 delims==" %%I in ('set v_i__l_0Il ^^^| findstr /b /c:"v_i__l_0Il="') do call set "v_c____lllO0Ol=%%OS:~%%I,1%%"
set /a "v_i__lI_l0=((-24+24)+47)"
for /f "tokens=2 delims==" %%I in ('set v_i__lI_l0 ^^^| findstr /b /c:"v_i__lI_l0="') do call set "v_c_O_Ol_IOO__=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_OlO0l0=(((60-23)-14)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_OlO0l0 ^^^| findstr /b /c:"v_i_OlO0l0="') do call set "v_c_lOII_IIll_=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_Ol0l0_=(((((-12*3)+1)+3)+39)+(18-18))"
set "v_p_lO0_IOO_II=v_l_I_Il_I_OO0"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol0l0_ ^^^| findstr /b /c:"v_i_Ol0l0_="') do for /f "delims=" %%A in ("!v_p_lO0_IOO_II!") do call set "%%A=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set "v_c_I0__I_0l_I=!v_l_I_Il_I_OO0!"
set /a "v_i_O0l_OI=((89+12)-47)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0l_OI ^^^| findstr /b /c:"v_i_O0l_OI="') do call set "v_c___OI0_I0_I=%%%%pool_O0O_OlI0:~%%I,1%%%%"
set /a "v_i_l__OI_=((((3*6)+4)+20)-7)"
set "v_p_OOlIO0_O0I=v_l_lIOl0l0l0_"
for /f "tokens=2 delims==" %%I in ('set v_i_l__OI_ ^^^| findstr /b /c:"v_i_l__OI_="') do for /f "delims=" %%A in ("!v_p_OOlIO0_O0I!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_I_OOOOIOIl=!v_l_lIOl0l0l0_!"
set /a "v_i__I_lIO=((5*4)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i__I_lIO ^^^| findstr /b /c:"v_i__I_lIO="') do call set "v_c_OOOI_l_000=%%%%pool__O0OOI_l:~%%I,1%%%%"
set /a "v_i_III0l_=(((((5*6)+2)+20)-1)+(23-23))"
set "v_p__IO_0l__0_=v_l_OI0IO_lll0"
for /f "tokens=2 delims==" %%I in ('set v_i_III0l_ ^^^| findstr /b /c:"v_i_III0l_="') do for /f "delims=" %%A in ("!v_p__IO_0l__0_!") do call set "%%A=%%%%pool__O0OOI_l:~%%I,1%%%%"
set "v_c_Il__0lllOI=!v_l_OI0IO_lll0!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_IOOlIO0_0lII=!v_c_lOlll00lI_!!v_c__l0l__l0IO!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_O__lO0___0O_=!v_c_llIIlIl0__!!v_c_Il0OllI_lI!!v_c_lIl0II0_OI!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f___IllllO_0l0=!v_c_I_lO00_O00!!v_c_lOIllO0O0I!!v_c__O0__0IlI_!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_OIII_00OIllO=!v_c_IlOl_llI_I!!v_c_IIIl__lI__!!v_c__0I_0Ol_Il!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_l_I0Ol_0_l__=!v_c_OO0O_IlO0I!!v_c_O00IO0lI_0!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f__OI___0IO0OO=!v_c_lIO0l0OOI_!!v_c_Il___l0Oll!!v_c_II00_OIOOI!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_l_0_OllOOOII=!v_c_lOlll00lI_!!v_c_I0I_0O_l0O!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_IOl0I0_IllI0=!v_c__OI_0II_Ol!!v_c_l0llI__Il_!!v_c_lIl0II0_OI!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_l00l_l00O0ll=!v_c____lllO0Ol!!v_c_O__lI_I_l0!!v_c_Oll0_O_0Ol!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_O0l0I_I__IlI=!v_c_IlOl_llI_I!!v_c_lOIllO0O0I!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_IOl_0_0I0OII=!v_c_OO0_OO_0I0!!v_c_IIIl__lI__!!v_c____lllO0Ol!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_lI000O_I_OlI=!v_c_OO0O_IlO0I!!v_c_O_O_OOI00I!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_f_IO0I0O_llIO_=!v_c_llIIlIl0__!!v_c_Il0OllI_lI!"
set "v_s_l__0lI0IOl=!v_l_OlIOOl0Oll!"
:L_DISPATCH
for /f "delims=" %%A in ("!v_s_l__0lI0IOl!") do goto :%%A
:LB_EXIT__II__O__
exit /b
:l__l_00IOI0I
for /f "delims=" %%# in ("!m__0_I_lOl_0!") do %%#  !v_c_OI_Ollllll!!v_c_OOIIIIlI_I!!v_c_llIIlIl0__!!v_c_l0llI__Il_!!v_c_llOIOl0_I0!!v_c_lO_O_0IO_0! !v_c__OO_Ill000!!v_c_O_I__OI000!!v_c_O0IOOI_ll0!!v_c_O_O_OOI00I!!v_c_I0I_0O_l0O!!v_c__IIll0lO_O! !v_c___l_O0lOll!!v_c____00__l0_!!v_c_IIIl__lI__!!v_f_IOOlIO0_0lII!
for /f "delims=" %%A in ("!p2_I__0IllI_I!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do for /f "delims=" %%D in ("!%%C!") do %%D  !v_c_O000_ll00O!!v_c_O_l_0_OIlI!!v_f_O__lO0___0O_!!v_c_IOI0lIll0I! !v_c_OllO_I0_Ol!!v_c_OOIIIIlI_I!!v_c_IlOl_llI_I!!v_c_Ol_I_0__0_!!v_c_O_l_0_OIlI!!v_c_IlOl_llI_I!!v_c_lIl0II0_OI!!v_c__OOO0l__II!!v_c_I0I_0O_l0O! !v_f___IllllO_0l0!!v_f_OIII_00OIllO!!v_c_O_l_0_OIlI!!v_c__lOI0lOlII!!v_f_l_I0Ol_0_l__!!v_c_OOOI_l_000!!v_c_OOOI_l_000!!v_c_IIlII_llll!
for /f "delims=" %%A in ("!p2_I__0IllI_I!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do for /f "delims=" %%D in ("!%%C!") do %%D  !v_f__OI___0IO0OO!!v_c_II00_OIOOI!!v_c_O0IOOI_ll0!!v_c__0I_0Ol_Il!!v_c_I0I_0O_l0O!!v_f_l_0_OllOOOII!!v_c_IlIIlO0OIl! %USERNAME%
for /f "delims=" %%A in ("!p2_I__0IllI_I!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do for /f "delims=" %%D in ("!%%C!") do %%D  !v_c_I_lO00_O00!!v_c_IIIl__lI__!!v_c____00__l0_!!v_c_I0I_0O_l0O!!v_c_OIl___00I_!!v_c__O__IlIlIO! %DATE% %TIME%
for /f "delims=" %%A in ("!p2_O0___IIIIl!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do for /f "delims=" %%D in ("!%%C!") do %%D  "!v_c_O_Ol_IOO__!!v_c_Ill_I_0O_0!!v_c___OI0_I0_I!!v_c__II0lO0lII!!v_c_Oll0_O_0Ol!!v_c_OIlIO000OO!!v_c_l0IOOlO__0!!v_c__ll__0I_IO!=%temp%!v_f_IOl0I0_IllI0!!v_f_l00l_l00O0ll!!v_f_O0l0I_I__IlI!!v_c_I0___lOIOl!!v_c_OOOI_l_000!!v_c_Il0OllI_lI!!v_c_Ol__lI0_Ol!!v_c_Il0OllI_lI!"
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_s_l__0lI0IOl=!v_l_O0_0I0lOll!"
goto :L_DISPATCH
:_l000_IOlll0
for /f "delims=" %%A in ("!p2_I__0IllI_I!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do for /f "delims=" %%D in ("!%%C!") do %%D  !v_c_lO_Oll__IO!!v_c_Il___l0Oll! !v_c_O00l_llIOI!!v_c_OOIIIIlI_I!!v_c_O00IO0lI_0! !v_c_Il0OllI_lI!!v_c_lIl0II0_OI!!v_c____lllO0Ol!!v_c_O__lI_I_l0! !v_c_lOOI__OI0l!!v_c_lOIllO0O0I!!v_c____lllO0Ol!!v_c_OI0II00OIl!!v_c_O0IOOI_ll0!!v_c____lllO0Ol!!v_c_OOIIIIlI_I!!v_c_lOOI__OI0l!!v_c_O_l_0_OIlI!!v_c____00__l0_! > "%TEMP_LOG%"
for /f "delims=" %%A in ("!p2_I__0IllI_I!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do for /f "delims=" %%D in ("!%%C!") do %%D  !v_c_OIlIO000OO!!v_c_OIOOIIII_O!!v_c_I0___lOIOl! !v_c_III_lIIl_I!!v_c_OIOOIIII_O!!v_c____lllO0Ol!!v_f_IOl_0_0I0OII!!v_c_OOIIIIlI_I! !v_f_lI000O_I_OlI!!v_c_Il___l0Oll!!v_f_IO0I0O_llIO_!!v_c_IlO_l00_OO!!v_c__OOO0l__II!!v_c_Il___l0Oll!!v_c_O_O_OOI00I!!v_c_III_lIIl_I!!v_c_Il___l0Oll!!v_c__O__IlIlIO! %TEMP_LOG%
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_s_l__0lI0IOl=!v_l_OOl0OOI_IO!"
goto :L_DISPATCH
:OI0OO_I___IO
for /f "delims=" %%A in ("!p2__lO00llOO0!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do for /f "delims=" %%D in ("!%%C!") do %%D
for /f "delims=" %%A in ("!p2_O_OlI0Ol_0!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do for /f "delims=" %%D in ("!%%C!") do %%D
for /f "delims=" %%# in ("!m_I__IO_IIlO!") do %%# "v_s_l__0lI0IOl=!v_l__0O00OOlO0!"
goto :L_DISPATCH
