[package]
name = "rustpolymorphic"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
rand = "0.8"
proc-macro2 = "1.0"